### ISSUE TITLE
1846 - "Always include the ends of a route" has no workaround if company has the mail contract

### ISSUE THREAD

**Issue by pence** [tobymao/18xx#1002]
https://github.com/tobymao/18xx/blob/bb418cd9e72b441b32ea49c08faba8f822905f46/lib/engine/route.rb#L148-L149

**Comment by pence** [comment]
It is likely / common for a train using the mail contract to include extra "unnecessary" stops for the mail contract's revenue bonus in 1846. The assumption that both ends of a route should be included for maximum revenue in the route calculation is incorrect in this particular instance.

**Comment by tobymao** [comment]
i'm aware of this issue but it's a tough fix

**Comment by Azuureth** [comment]
What about:
1. Add possible East-West bonus to offboard location revenues
2. Sort by revenue
3. Pick highest with token (manadatory 1 token on N/M)
4. Pick highest N-1 location per revenue
5. Add mailcontract as per up to M

**Comment by Warbanner1** [comment]
Am I to understand there is a workaround if you are not using the mail contract? Because I was just coming to file a bug about a 4/6 train with 5 stops, and when I added a 6th stop the total payout went down, and I *don't* have the mail contract. Now I realize it's due to this "Always include the ends of a route" rule. 

Obviously, in a F2F game, I wouldn't bother with the 6th stop, but online, I might (and did) just make the connection while considering options, and was quite surprised by the resulting drop in payout.

I don't understand the reason for the rule - couldn't you only include the ends if the ends are E/W (to guarantee the bonus), and then otherwise sort the stops in value order, ignoring the (M-N) lowest value stops from the list?

**Comment by adamranderson** [comment]
Here is a game state for testing against. https://gist.github.com/adamranderson/6e215ec713819a0609b7fc3fe1630366

The NYC hits this issue running a 3/5 with mail from Port Huron to Erie.

**Comment by cheesinglee** [comment]
In 1846 the maximum number of possible stop combinations for an N/M train is 15 (a 4/6 train passing through 6 cities). A brute force search doesn't seem too outrageous if the alternative is an overly complicated heuristic.
