### ISSUE TITLE
[1822CA West] Winnipeg Issue #1

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#10131]
Major comp CNOR is able to build track on the eastern side of Winnipeg, even all station slots there are full.

https://18xx.games/game/148405?action=640

**Comment by michaeljb** [comment]
The spot reserved for GNWR's destination token is open, so companies can still pass through. Compare with NTR's destination token, also in Winnipeg.

I'll keep this open because it would be nice to have a more clear way to represent that a city slot is reserved for a destination, but the destination token is not there yet.

**Comment by toolgames** [comment]
There are no actual slots reserved for destination tokens in this way. Also see https://github.com/tobymao/18xx/issues/10147

**Comment by TheTagoreler** [comment]
Hello, another report of this issue in https://18xx.games/game/147916#info - GNWR taking its destination in winnipeg created an extra, "3rd" token in Winnipeg NE that shouldn't be there.

**Comment by michaeljb** [comment]
This should be fixed by #10192
