### ISSUE TITLE
18CZ 3E trains scrapped with export of second 5i train

### ISSUE THREAD

**Issue by aktiengeier91** [tobymao/18xx#10154]
**What's your Game ID?**
147934
https://18xx.games/game/147934

https://18xx.games/game/147934?action=856

**How to Reproduce the Bug?**
let the game export the second 5i train (I guess)

According to the rules 3E should only be scrapped if a 6E train is sold/exported. The exported 5i train wasn‘t even the first one, so there was no phase change

![IMG_0677](https://github.com/tobymao/18xx/assets/66421418/b54af9f2-9501-420b-9782-81f0c20c8da1) 

![IMG_0678](https://github.com/tobymao/18xx/assets/66421418/754ac837-d198-4716-abc8-b2ba72e618a1)

![IMG_0679](https://github.com/tobymao/18xx/assets/66421418/b0524248-9a5f-435a-a6de-51e7237fd5cd)

**Which Browser / Platform?**

all

**Comment by benjaminxscott** [comment]
I think the implemented behavior is correct, when a train exports it triggers all rusting for all types (small/med/large) in that "phase" (in this case `i`) . Like you mentioned if a train is purchased it only triggers rusting for the relevant type (e.g. small trains)

It's more apparent in the physical game, since the train cards are multi-sided and show three train types on each card, so when a train exports you rust all the types rusted on that card

```
When a train is sold to a foreign country (exported) at the end of a set of operating rounds, it is handled as if a
train of each type is removed from the game. 

e.g. if the train that is sold to a foreign
country is an h-train, scrap any trains that would be scrapped by the sale of a red 5-train: a blue
5+5 train, and a green 5E train.
```

**Comment by aktiengeier91** [comment]
Thank you, didn‘t catch that part in the rules.

Matter solved.
