### ISSUE TITLE
1817NA: 100% shown in log when 40% president share is bought

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#10320]
![image](https://github.com/tobymao/18xx/assets/2631151/dc357dcf-389a-4d83-a25b-04205c49e0f2)

Game: https://18xx.games/game/152000

Everything looks OK, although the log states:
[16:11] davpe023 buys a 100% share of NYOW from the Treasury for $400
even though it was the 40% share in a 5 share corporation.

**Comment by MrSkinny** [comment]
Technically, the way 17 works is first you win the President's Certificate by auction and then you decide how many shares the company should issue. The game actions also reflect that.  First, you win the auction and get the cert. The game log prints "[player] buys a 100% share of [company]". Then you're given an action prompt for 2 or 5 shares.  Game log prints "NYOW floats...".

Since they're two separate actions, you wouldn't want to go back and alter the log from 100% to 40% after share issuance decision.  Solution (if needed) could be to write logic where the game log prints out differently for share purchases specifically when it's the President's Cert from treasury.  Something like:

> [Player] buys the President's Certificate of [Company] from the Treasury for $[amount]

**Comment by perwestling** [comment]
I agree. I was thinking that it might be possible to change it generally to show President's Certificate and not show the percentage. But there is probably still a small problem that if you switch view to show all corporations it would still need to show either 2 or 5 (or 5 or 10, later in the game).
Anyway, I thought the log text was a bit confusing for beginners, but maybe not worth the effort.
Unless it is a simple one liner or so.

So maybe we should keep it as is?

**Comment by perwestling** [comment]
Closing it as it is a small thing.
