### ISSUE TITLE
Game: 1822CA (beta) Id: 154117 Minor acquisition in 1822CA still having issues

### ISSUE THREAD

**Issue by Seraphin06** [tobymao/18xx#10409]
Id: 154117

https://18xx.games/game/154117

https://18xx.games/game/154117?action=1436

I have reported this before...I swear between share value of both minor, major, connection, and cash in the company.  I should be able to acquire Minor #1 into Great Western Railway.  The option isn't there.  

![Screenshot (1)](https://github.com/tobymao/18xx/assets/113114593/65aaf31f-ccd9-4c7f-813c-5c54e6e852ac)
![Screenshot (3)](https://github.com/tobymao/18xx/assets/113114593/ba0e6eab-6706-44e5-b256-3e528e8c4a45)
![Screenshot (4)](https://github.com/tobymao/18xx/assets/113114593/16dd8d58-c18b-479a-b76b-69132f13dc51)

**Comment by michaeljb** [comment]
Just for reference, the other issue you reported was #10245, in that case the Major did not have the assets to acquire the Minor.

Running down the list here...

* Minor 1's share price is $245, so total cost to acquire is $490
* GWR's share price is $165, it can contribute $330 in shares, it does have the cash ($290) to cover the remaining $160
* GWR and Minor 1 are connected

...

Found the problem -- you're already at the certificate limit, so GWR can only pay for the acquisition with one share and cash, since two shares puts you over the limit after the Minor 1 cert is removed. One share ($165) plus the cash ($290) is $455, just short of the needed $490.

**Comment by Seraphin06** [comment]
Yep, sorry. There is always something.  Lol. User error.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
