### ISSUE TITLE
[18Neb] P1 and P4 tile reservation UI (bars) s.b. removed in phase 3

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10571]
http://18xx.games/game/157964?action=152

C&S was able to build on B8 while I owned P1 which should not be allowed.

https://gist.github.com/benjaminxscott/48373f4fcc304eb8212f230326288661

**Comment by benjaminxscott** [comment]
Looks like this is operating as expected, the rules indicate P1 (DPR) as well as P4 only block those hexes until phase 3 (green)

We should remove the bars on the tile in phase 3, it's likely the UI doesn't remove those since idk if there are any other games that work that way

We should also add that info to the private descriptions

**Comment by scottredracecar** [comment]
1861 has a rule like that too for all the privates that block hexes.

**Comment by crericha** [comment]
Okay, will remove reservations. @scottredracecar thanks for the tip on what game I can mimic.

**Comment by crericha** [comment]
Found out that the `blocks_hexes` ability (for all games) doesn't remove the block from the hex during its teardown. I fixed the core code.
