### ISSUE TITLE
Makes game tabs CTRL-clickable to open in new tab

### ISSUE THREAD

**Issue by zurfarosa** [tobymao/18xx#1060]
Currently you can use the browser context menu to open game tabs (e.g. Spreadsheet, Entities) in a new browser tab. Two problems: 
1. The newly opened Chrome tab defaults to Game view
2. You have to use the context menu - you can't CTRL-click

**Comment by tobymao** [comment]
do you happen to know how to solve this html wise?

**Comment by AnthonyPAlicea** [comment]
I believe since there is JavaScript intercepting the click (i.e. on-click='return false') this will not work, as Ctrl+click is native browser behavior. In the code you would have to manually detect that the CTRL key is held down and window.open into a new tab to mimic what the browser would normally do.

**Comment by tobymao** [comment]
thanks @AnthonyPAlicea 

won't fix this for now given that information
