### ISSUE TITLE
[18NL] NZO_HOME_HEX: uninitialized constant

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#10614]
edit: last working action
https://18xx.games/game/158741?action=41

https://gist.github.com/benjaminxscott/ad06f957072bf0b3f32be0e1015a03fb

**Comment by benjaminxscott** [comment]
seems like a regression from https://github.com/tobymao/18xx/pull/10594

**Comment by benjaminxscott** [comment]
Game should be continuable after fix is deployed

Check this page to see when fix is deployed, a recent timestamp would imply it's been deployed
https://18xx.games/about

**Comment by philcampeau** [comment]
Ahhh you know what? No, that wouldn't be continuable. Constants are defined when the game is initially loaded. I created that constant because it was "better coding", but unfortunately, it will leave their game unplayable. 

In the end, whether or not we pinned the game it would have still been dead in the water. All you can do at this point is delete this game and start a new one, unfortunately.

**Comment by philcampeau** [comment]
@benjaminxscott with the fix! Looks like this game will be working again once his patch is applied.
