### ISSUE TITLE
[18ESP] Wrongly applied restrictions to buy a train

### ISSUE THREAD

**Issue by DarthIA** [tobymao/18xx#10627]
**What's your Game ID?**
https://18xx.games/game/153910?action=968

**How to Reproduce the Bug?**
I have to buy a mandatory train with CFLG, but the system thinks that it is a southern company, so cannot buy a +train. Actually, it is a northern company with token in the south and in the mountain pass, so it should be able to buy both I think.

**Comment by kepakiano** [comment]
This issue is fixed in the current master, it just needs to be rolled out.
Loading this game in hotseat mode on 18xx.games yields:
![image](https://github.com/tobymao/18xx/assets/1355029/5c6eb2f2-d9f0-4f0d-b352-b7326c97f989)

Locally with the current master:
![image](https://github.com/tobymao/18xx/assets/1355029/0ea7741c-a748-4f55-8995-7635fc7dd326)

**Comment by benjaminxscott** [comment]
fixed by https://github.com/tobymao/18xx/pull/10587
