### ISSUE TITLE
[1882] Cannot buy president's certificate of CN after neutral token has been placed with NWR ability.

### ISSUE THREAD

**Issue by M-Kristof** [tobymao/18xx#10641]
**Game ID**: 157830

During OR4, a neutral token is placed in Prince Albert (D8) with the ability of private NWR. In the stock round that follows, president's certificate of CN cannot be bought.

**Comment by philcampeau** [comment]
I just imported this game to my development server and I was able to purchase the president's certificate of CN as user Spookie:

![image](https://github.com/tobymao/18xx/assets/26125362/474bf558-497d-487e-90c9-0ee435ac214e)

Is it possible that it was user CP who was trying to par the corp and couldn't? Because user CP only has $4, which would be the reason he couldn't.

**Comment by M-Kristof** [comment]
It was me (KRIKKE), but I was also a few $ short for the cheapest option, so it didn't show any option to par. This can be closed, false alarm.

**Comment by philcampeau** [comment]
Glad we figured it out! cheers
