### ISSUE TITLE
In game chat notification and punctuation  

### ISSUE THREAD

**Issue by MatthewDeKoning** [tobymao/18xx#10675]
**How to Reproduce the Problem?**
Alert a player with @<tag> 
but if you say @<tag>, - no notification is sent due to the attached comma. I do not entirely know what constitutes a valid user name so sanitizing punctuation off the end of @<x> statements may not be safe. Just something noticed. If usernames cannot have punctuation it may be useful to trim it off the end in such a case.

**Comment by benjaminxscott** [comment]
I think we handle this here, so likely include? isn't checking a stripped message here
https://github.com/tobymao/18xx/blob/master/routes/game.rb#L120

**Comment by benjaminxscott** [comment]
I wasn't able to repro this on a local build, it successfully sent a (webhook) notif in these two cases where a comma / period were included:

![image](https://github.com/tobymao/18xx/assets/1711810/9ea7a3b3-c375-4206-a193-0e274b63a0cc)

Was there a specific case you noticed?

One factor is that email notifs aren't sent if the player has 18xx.games open in any tab, or if it's been too soon since the last notif (small number of seconds). Webhook notifs are not subject to those limits
