### ISSUE TITLE
[18Mag + expansion] CIWL doesn’t give income to the route

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#10673]
On game 160016 company 5 have run from red hex to red hex. The total of the route is 130 (30+40+40+20 of RABA company) on green phase. CIWL company has received 30. 
However, the total of the route should also earn 30 for running from red hex to red hex when CIWL company is in play.

Thanks,

Enrique Trigueros.

**Comment by philcampeau** [comment]
In the future, it would help if you could link to the action where this happened, or at least say which round it was. 
I found it here: https://18xx.games/game/160016?action=887

It looks like currently, CIWL is configured to add the bonus as a subsidy to the minor, rather than adding the value to the run. Looking at the expansion rules, it seems like a case of ambiguous phrasing: 

![image](https://github.com/tobymao/18xx/assets/26125362/17b43a6d-2038-4170-baba-179b9cff56ce)

I created a post on the BGG page for clarification: https://boardgamegeek.com/thread/3309608/is-the-ciwl-bonus-added-to-the-run-or-is-it-added

**Comment by philcampeau** [comment]
lonny replied in the thread above and confirmed it should be a revenue bonus. I'm submitting the fix, @bentziaxl can verify that it's correct.
