### ISSUE TITLE
[18ESP] Game doesn't load "GameError: Blocking step Buy Trains"

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#10672]
https://18xx.games/game/155800?action=887

The game won't load and displays the error message "We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 888
Broken action: { "type": "pass", "entity": "CFEA", "entity_type": "corporation", "id": 888, "created_at": 1712932190 } 

I'd assumed that Enrique (the designer) had filed a bug as he is playing in the game, but I don't see an existing report for this bug.

**Comment by queroscia** [comment]
Hello,

I am Enrique (co-author of 18ESP), and I didn't report any bug about this game. But, maybe, it is because an update I asked for some time ago, although I don't know if it was already implemented or not.
The current scenario obliges CFEA to purchase a train because it has a train that it cannot run. A few time ago the rule was that a company should have a train at the end of an OR **that can run.**
But the update rules say: at the end of an OR, any company that hasn't a train must purchase one, but it is not necessary that the train can run (although every time the company doesn't run a train, its value drops, as usual in many 18xx games).

Is it possible the game is broken due to a this update on the rules? I really don't know it.

Thanks,

Enrique Trigueros.

**Comment by benjaminxscott** [comment]
The issue queroscia is referring to is:
https://github.com/tobymao/18xx/issues/10640
which hasn't been patched, and I don't think would cause this issue anyway

IMO it's likely due to this other patch, which was deployed recently and this particular game may not have gotten archived
https://github.com/tobymao/18xx/pull/10587

**Comment by benjaminxscott** [comment]
alpha games that are likely out of sync won't get debugged

**Comment by slapphappyjazz** [comment]
@queroscia Please can you manually end or delete the game?

**Comment by queroscia** [comment]
Sorry, I cannot, program doesn’t allow me.
I opened an issue about deleting this game and also game 155563, both broken but that appear on the main page because they cannot be deleted manually.
