### ISSUE TITLE
[18RoyalGorge] metal_investor discount handling function passes nil to shares_bundle initializer

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10733]
https://18xx.games/game/162858

**Comment by jasonab** [comment]
also 161776

**Comment by Aposky** [comment]
Map tab loads, however the game doesn't
https://18xx.games/game/161776#map
I noticed it happened after I tried to sell gold mine share

**Comment by BellmakerSA** [comment]
It may be a stock round issue had a different game work okay until the end of the set

**Comment by ollybh** [comment]
There's an exception being thrown from the ShareBundle code:

> Uncaught RuntimeError: All shares must be from the same corporation

**Comment by benjaminxscott** [comment]
JFYI that error from the share_bundle code is a bit misleading since it also fires if passed a nil shares object (as .one? returns false if the array is empty, the same way as if the passed in `shares` has multiple owners)

https://github.com/tobymao/18xx/blob/master/lib/engine/share_bundle.rb#L10

I confirmed that in this case the game code is passing in a nil shares object for whatever reason
https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_royal_gorge/step/buy_sell_par_shares.rb#L71
