### ISSUE TITLE
1846 (and possibly other games): Game temporarily soft-locks if all companies close

### ISSUE THREAD

**Issue by Qaimaqam** [tobymao/18xx#10743]
I'm not sure how to copy the hotseat JSON data but it's easy to replicate. 

Create a game of 1846. Open all the companies, get to the Brown phase which eliminates all private companies, then keep holding until all companies are closed. Make sure the bank does not break (when I tested this I had a bank at over $7,000 in a 5P game when I was able to make the bug happen). 

When the last company is operating at share price $10, if you withhold, the game soft-locks and you cannot access 18xx.games on your device for a few minutes. 

What I suspect is happening is an endless loop of "Player has no valid actions and passes" where nobody can respond with game input. 

It's a rather ridiculous set of circumstances, but it can technically happen. 

Suggestion: If "no valid actions" loops for all players 10 times without a change from SR to OR, OR to next OR, or OR to SR, the game should be ended immediately.

Soft lock ends after about 10-20 minutes and goes back to the previous action.

**Comment by ollybh** [comment]
@Qaimaqam can you please save a copy of the hotseat game that shows this issue?

You get the raw game data by using the `Tools` tab and `Copy Game Data`. Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**Comment by Qaimaqam** [comment]
I have no idea if I did this right as I've never done this before (and had trouble copying something this big on my phone, which I then copied from the email draft on a PC to make it easier on myself), but here's my attempt:

https://gist.github.com/Qaimaqam/1ad70c054a3890403a96e77f1c793c51

**Comment by benjaminxscott** [comment]
Looks like your repro game works, I put `minor bug` since it's such an edge case

**Comment by benjaminxscott** [comment]
oh yeah it's not fixed so it'll keep doing that (this issue would eventually be closed as fixed, or as wontfix)

When you say it freezes the entire site, do you mean in other tabs?
(like if it's softlocked in the one tab w/ the game, do other tabs with the site loaded also freeze? does it freeze other tabs w/ other sites loaded?)

**Comment by Qaimaqam** [comment]
I cannot load any other tabs in the same browser for 18xx.games (even the main site) when the hotseat game softlocks. I have to wait several minutes. 

I can log in on another machine or browser, but those won't have the hotseat game, as it's unique to the device it was created on.

**Comment by benjaminxscott** [comment]
Ah so the browser hanging all tabs from the same domain is behavior on the browser's part that `18xx.games` can't influence since it's related to how the browser decides to sandbox tabs

You can actually move the hotseat game over by `Copy` the game data from the `Tools` game tab of the old browser (same way you posted it in the gist link above) and create a 'new game' by pasting it into the "Import" option in the new browser

Just to clarify, the hotseat game triggering this issue won't work until/unless this issue ticket is resolved as fixed, and the game would just end anyway at that point so it's not really playable

If you want to keep the old browser running rather than killing its entire process you can try closing that one tab manually or if the entire browser is hung then [kill the sub-process running that tab](https://stackoverflow.com/a/27261978) using the task manager of whichever browser/OS you're using.

**Comment by Qaimaqam** [comment]
Huh? I don't think this is browser-specific behavior (other than not being able to open a new tab to 18xx.games). It's Android DuckDuckGo, for the record. Kind of wish I went through all this on a PC instead of my phone! 

The game "works" in that it seems to reset to the last "valid" state (last company at $10 and about to hold route money) after a few minutes. It doesn't hang forever, just temporarily, maybe 10-20 minutes. 

I can get back in after this, so I don't actually need to close anything, I was documenting it in case there's ever a game where all the companies closing could be part of the ending. 

I could try to do a shorter 3p on PC Firefox and see what happens if that helps?

**Comment by benjaminxscott** [comment]
To clarify, the game hanging at all is a bug in 18xx.games, but the browser hanging other tabs for 18xx.games while that game tab is hanging is a browser behavior

What I meant by "game won't work" is it won't progress until/unless bug is fixed, and either way the game is over anyway

What happens is the browser tab gets into an infinite loop running the game's javascript, until the browser decides it's had enough and kills the running JS

It's super helpful to report edge cases btw

A shorter game would result in the same bug, so no worries

**Comment by michaeljb** [comment]
While setting up my own repro case, I stumbled upon another bug; Player 1 is president of the IC, sells a share so that its price drops and it closes. Before the time of the sale, Player 2 had two shares, so it logs that Player 2 becomes president, which doesn't really make sense at that point, but the real bug is that on Player 2's turn, they have no valid actions, but the game blocks for them to take their turn.

Since pass is not valid, the pass button is not visible and the game cannot proceed.

I think this is because company closures are handled in `action_processed()`, at the end of processing an action, so there's probably some weird interactions where Player 2's valid actions are checked before the corporation is closed, and it's determined that Player 2 could sell a share, but after the closure is executed, they no longer could sell that share.

https://gist.github.com/michaeljb/bcd0437bba665def8052b5080a3b9efc

**Comment by michaeljb** [comment]
I've opened #10820, which handles the case in the specific game linked by @Qaimaqam (in fact I've added that gist as a fixture in the PR) but it does not address the case where privates should drain the bank. I'll keep this issue open to track that case, and I've opened #10821 for the other bug I found.

**Comment by michaeljb** [comment]
I settled on just ending the game at SR 100 as a universal fix. While trying to properly catch end games for 1846, more scenarios kept occurring to me that made it more complicated to handle something that just doesn't matter, e.g:
* private companies still open to empty the bank
* but not the mail contract since it makes $0
* the Michigan Southern or Big 4 might also make $0, if they have less than $20 and no route
* hmm could there still be one or more corporations available to start, while all private companies are closed (or making $0), and all players have less than $80?

So eventually catching the degenerate scenario, whatever it is, seems better and is 100% simpler as well as universally applicable
