### ISSUE TITLE
[18RoyalGorge] cannot use gold cube on D6, C5 adds a gold cube when it should not

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#10846]
https://18xx.games/game/165364?action=574

The two bugs may be connected?

**Comment by BellmakerSA** [comment]
C7 also adds a gold cube when it should not

**Comment by michaeljb** [comment]
Thanks for reporting this, they are indeed connected. Looks like the gold cube isn't being properly removed from a tile when the tile is upgraded from yellow to green.

D6 was only supposed to ever have one gold on it, and it was already shipped by the time your linked turn happened. It appeared to have two gold cubes on it when it was laid because of this bug--the tile had previously been laid on M15.
