### ISSUE TITLE
1846 issuing shares just before train purchase

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1087]
In practice the president will probably just wind back the turn and issue at the greatest value, but if they're going bankrupt anyway and want to tank the price for any remaining shareholders, shares should be issued from the corporation before triggering bankruptcy.

GMT rules (the part about closing a corporation during EMR has been errata'd away, unfortunately I don't have a link for that at the moment):

> **6.86 Forced Train Purchase**: A corporation must buy a train if it has none after
> running its routes (if any) and removing any phased out trains. If it is unable
> to buy a train from another corporation or the bank with its treasury funds, it
> must buy a currently available train, of either type, from the bank using all of
> its treasury with the remainder coming first from issuing shares up to the
> normal limit (see 6.31 and below) and then, if needed, from its President’s cash
> on hand.

> *NOTES: A forced train purchase is the only time when a corporation may mix its*
> *funds with its President’s funds. Typically, making a corporation’s decisions*
> *benefits its President; this is balanced by the potential liability of the*
> *President possibly having to purchase trains for it “out of pocket”.*

> To issue shares, first shift its stock price one column left for each share that
> it will issue. The corporation receives one value lower than this new stock
> price for all shares issued. If its stock price drops to $0, close the
> corporation (see section 8).

> *TIP: Since issuing shares for a forced train purchase results in a reduced stock*
> *price and less money received per share, it is almost always better to have*
> *issued shares fully (or to not redeem any) earlier in the turn.*

> **6.87** A corporation which can afford an available train of one type, but not the
> other, may issue shares but may not use cash from its President to buy the more
> expensive train. Similarly, if an earlier train type is available for purchase
> (from being turned in by a corporation that exceeded the train limit) and the
> corporation can afford that train but cannot, after issuing shares, afford a
> current phase train, the corporation may not use cash from its President to buy
> a current phase train.

> However, once a corporation has to use cash from its President to purchase a
> required train, then it may freely buy from the bank any available phase or type
> of train.

**Comment by JEBrosius** [comment]
Just to provide one example:  Last week I playing in an 1846 game in which a player launched the NYC, buying only 2 shares at $150/share.  He wanted to spend $120 on track and a station and buy a 5T but issuing 2 more shares at the start of the NYC's OR turn would have generated $274 in cash and left the NYC with $300 + $274 - $120 = $454, meaning that he would have been forced to buy a 4/6T.

So he issued one share for $137 and spent $120 on track and a station, leaving $317 in treasury. The price fell back to $137 when the corporation paid no dividends, and he was then in EMR status.  He issued the second share, dropping the price to $124, and getting $112 for the share (one box lower,) leaving the NYC with $317 + $112 = $429.  Since he did not have enough in treasury to buy either kind of brown train from the bank, he was free to add personal cash ($71) to purchase a 5T for $500.
