### ISSUE TITLE
1870 online game FW Destination is not showing up.

### ISSUE THREAD

**Issue by LocomoEngSon** [tobymao/18xx#10950]
**What's your Game ID?** LocomoEngSon

**How to Reproduce the Bug?** Open 1870 and compare Destinations of all other public companies’ Destinations to the FW.

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
Here's the actual game I'd: https://18xx.games/game/165192?action=420#map

Looks like at this point, before the connection was made, the FW destination was showing on A2. 

![Screenshot_20240623_104712_Chrome](https://github.com/tobymao/18xx/assets/26125362/e9d38a9c-54c0-476c-87f4-bf1715c3c5e2)

After the connection was made, a destination run occurred, and the owner chose not to place the destination token.

![Screenshot_20240623_104648_Chrome](https://github.com/tobymao/18xx/assets/26125362/2b5343d7-5a3c-48e5-b0d0-2dee3f1e0060)


 Maybe that's why the destination ability isn't showing on the charter? Still seems wrong, but a different issue than what is reported.

**Comment by philcampeau** [comment]
Actually, no, there's nothing wrong. The ability on the charter indicates that either the corporation hasn't reached its destination, or that the corp has a destination bonus. If you decline to put the bonus token down, there's no ability to show. 

Closing this report, there is no issue here.
