### ISSUE TITLE
1822CA Small/Large mail contracts not paying with LP run.

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#11147]
https://18xx.games/game/173776

GT is starting.  They acquire a small mail contract (P24) and run the LP train, but no subsidy is paid.  Tried with large mail contract too, and no subsidy paid with that either.

Rules for small mail contract just require that you operate a train, which the LP is a train that operates.  E.g., it counts for whether you go backwards for paying dividend.

Large mail contract arguably should pay as well, but it's not clear.  1822MX is explicit that an L train can deliver mail within a single city.  I don't see that in 1822CA either way.

Thanks again!

**Comment by WayneWWms** [comment]
Thanks Michael.

**Comment by WayneWWms** [comment]
What's the ETA on the update Michael?  Thanks!

**Comment by michaeljb** [comment]
Finally taking a crack at this, so the ETA is sometime this week.

Per https://boardgamegeek.com/thread/2640241/article/43680986#43680986 the LP should not work with the large mail contract, and 1822MX needs an update for that as well--they need to be changed to not even work if the LP runs to a city and town.

I see no reason why the small mail contract should not work if the LP runs to a single city, so that will also need fixing.
