### ISSUE TITLE
[18Ardennes] Train limit not enforced during growing to 10-share

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#11360]
https://18xx.games/game/186643

In OR5.1, P grew to 10-share and absorbed two minors (#6 & #10).
P already had two trains (3 & 5), the minors had a 3 and a 4. The train limit was 2.
P discarded the 3 from #6 and accepted the 4 from #10. At this point, P is over train limit, but the program didn't insist to discard a train.
P then ran its 3 & 5 (not the 4, since it had already run that round).
After that, P had to discard (and chose to discard the 3).

So - there needs to be an extra train-limit check after the grow-to-10-share step.

**Comment by ollybh** [comment]
I believe that this is the correct behaviour. The last paragraph of section 6.1 of the rules (_5-share to 10-share conversion_) reads:

> If a Company acquires additional trains from exchanged Minor Companies, these are placed face-down and may not be used to earn revenue during the current Operating Round. After the Company has adjusted its Current Market Value, turn any such trains face-up. If the Company is now over its current Train Limit, it must discard excess trains of its choosing to the Open Market, whence they may be bought. A train inherited in this manner may be used in an exchange for a 4D-train.


So the check against the train limit doesn't happen until after the trains are run and dividends paid. I guess this is done so that the company still gets to run a couple of trains in the round it grows up.

**Comment by ianwilson156** [comment]
Amazing - I've been playing it wrong all these years!
