### ISSUE TITLE
18TN: Birmingham overlaps revenue for off board town

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#1357]
This is the mid south part of the 18TN map:

![Screenshot from 2020-08-06 01-02-33](https://user-images.githubusercontent.com/2631151/89472453-c50d7280-d780-11ea-9153-97de113694e5.png)

**Comment by perwestling** [comment]
According to Steve U this should fix itself when #1290 fix is merged.

**Comment by roseundy** [comment]
Two problems here: multi-revenue label is being drawn at the wrong vertical position. This will be fixed by #1290. The second problem, unique to 18TN (or any game with a "pointy" layout), is that the revenue label rendering ignores layout and assumes flat.

**Comment by roseundy** [comment]
There is a third issue here: multi-revenue text is not centered horizontally on the tile. This should be a problem for any game with a pointy layout.

**Comment by roseundy** [comment]
Possibly root cause to that last issue:

For the city name we have:
<g transform="rotate(-30)"><g class="tile__text" transform="scale(1.1) translate(0 40)" stroke-width="0.5">...

For the revenue we have:
<g transform="translate(0 69) rotate(-30)">...

It looks like the two elements may have the translation and rotation operations in a different order. This doesn't show up if the for "flat" layouts or if revenue is in the center of the tile (as it is for most off-board locations, but not for all locations in 18TN).

**Comment by perwestling** [comment]
Birmingham label have now moved on master so it looks good. 
Probably fixed by 1290.
