### ISSUE TITLE
[1846] Steamboat will NOT change locations

### ISSUE THREAD

**Issue by PedroRCSequeira** [tobymao/18xx#1375]
game: https://www.18xx.games/game/5794

Steamboat token won't change locations after being assigned (note: in the game it may not be assigned at all, since we decided to skip the first, temporary, assignment to reduce the impact

I've tried without success to change the location of the token:

-in another OR
-after buying with the 1st assigned company
-after buying with another company (it switches the assigned company, but still won't change the location

**Comment by michaeljb** [comment]
I cloned game 5794 and was able to assign the Steamboat as expected. How are you trying to reassign the location?

After clicking on the company name so that the ability is visible, you can click on a hex map to assign it to that location.

I can't upload a video to GitHub, so screenshots will have to do...

After clicking "Steamboat Company":

![Screenshot from 2020-08-06 20-44-58](https://user-images.githubusercontent.com/1045173/89603245-f3915900-d825-11ea-9d92-029066868799.png)

After clicking on D14:

![Screenshot from 2020-08-06 20-45-15](https://user-images.githubusercontent.com/1045173/89603282-06a42900-d826-11ea-9ac9-438f7f9d2c3d.png)

The route showing the bonus revenue in the total:

![Screenshot from 2020-08-06 20-45-30](https://user-images.githubusercontent.com/1045173/89603301-128feb00-d826-11ea-941a-556db8d36f2c.png)

**Comment by PedroRCSequeira** [comment]
hey, i was doing the same as you, and could also assign it the first time. but changing it, in another OR, or even after purchasing the private proved impossible (using the same method

**Comment by michaeljb** [comment]
I cloned game 5794 and basically passed actions until PRR's turn, I was able to reassign SBC then - https://www.dropbox.com/s/l30148rpzsc50gh/sbc-prr.mp4?dl=0

What device and browser are you using?

**Comment by PedroRCSequeira** [comment]
I used Chrome.
Another player also tried first and couldn't, but now he tried again and said it worked!
Guess magic happened? :D

**Comment by michaeljb** [comment]
My best guess is the first try may have happened before the fix was deployed? Anyway, glad it's working for you now! :tada:
