### ISSUE TITLE
18AL - Mongomery (L5) should have an M label.

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#1526]
The map for 18AL doesn't show an M on Montgomery (L5), but there are special reserved tiles in both green and brown for the city. Having that label as a reminder would be helpful.

Additionally, it would be ideal if the M label could also be overlaid onto whichever yellow tile gets placed on the city, again so that it's clear that there are special green and brown M tiles.

Cheers!

**Comment by perwestling** [comment]
In the physical map there is no M label on Montgomery. Instead the M label appear at first with the green tiles.

In the first versions of 18AL at 18xx.games it was tried to add a label to the hex when a yellow tile was added there, but it caused problems internally as the label remained on that yellow tile when it was upgraded. Now this would probably possible to fix, removing the label when upgrading the tile, but I choose instead to go back to how it is handled in the physical game.

Having a label on the Montgomery hex from the beginning is of course possible but would it be clear to the players that they could use any yellow tile there?

 So the solution that is now is as follows:

- When upgrading in Montgomery M tiles is the only allowed for green, and the M label will be kept for brown.
- In the Tiles manifest, if you click on any standard yellow city you will see that the green M tile is a possible upgrade, while on the map testing upgrade on any standard yellow city show the green M tile only on the Montgomery hex
- On the 18AL wiki page the Montgomery upgrade is explained so that players should be aware
- Birmingham has a B label as it special tiles for all colors
- How this is handled is the same in other games, such as 18TN and 18GA for similar tiles.
- 18MEX with Guadalajara does not have any label until the very last, brown, tile

So for implementation reasons, to keep the game as similar to the physical ones, and with the other enhancements that has done, I think the current solution is good enough.

**Comment by perwestling** [comment]
@philcampeau The hexes of Memphis and Nashville is a special case that should be considered.

- Memphis in 18xx.games start out as an empty hex. You upgrade it to normal yellow and normal green. Then you can upgrade it to a brown P and maybe a gray P. So should it then use a P label from the start?
- Nashville in 18xx.games start out as an empty hex. You upgrade it to normal yellow. When upgrading to green it gets an N label. And to brown/gray P. So should it use a N or P label from the start? Or N/P?
- Chesapeake is a bit similar to Nashville but starts as a yellow hex with a C label. But should it have C/P instead?

**Comment by philcampeau** [comment]
I’m thinking of the Mayfair edition of 1844. There are two hexes like this, which use a regular yellow tile, but then specific green/brown tiles. Their solution was to include a token with the B and Z labels on them that you could place on the yellow tile. 

Personally, I would think the advantage to a digital medium is that we aren’t restrained by physical limitations. The symbols on the board that indicate reserved hexes don’t disappear on the physical board when the private is bought in, but 18xx.games is able to achieve that. Why not do the same for labels on the board and yellow tiles?

**Comment by perwestling** [comment]
Thinking of the general case here.

So what do you think about the Mephis hex in 18TN? Should it have P label all the way?
Should Nashville have N label from the start, or N / P? 

Or do you mean it should just be added in the upgrade level just before?

If the latter then
Memphis (and Guadalajara in 18MEX) hex would be
  white - no label
  yellow - no label
  green - label P added
  brown - P tile

If having a label that does not appear on the next level of tiles, might be confusing.

**Comment by philcampeau** [comment]
I’ve always found the Guadalajara tile easily forgotten in 18Mex. I made a custom G token to put on that hex until the special tile comes out specifically for that case. 

I think any time you can be clear, you should. Given the flexible nature of digital design, why not have a label affixed to the hex, and shown on tiles that are used prior to specific ones. Maybe make the label red or another colour so it stands out?

**Comment by perwestling** [comment]
I think it might be technical difficulties with this one, but I will consider it for the future.

**Comment by perwestling** [comment]
It would maybe be possible to put an M icon on the Montgomery hex, and make it stick so it remains. When upgrading to green the icon can be removed.

This could also be used in 18MEX, 18TN and 18GA.

**Comment by ChrisTheCat** [comment]
The reason the M token doesn't appear in Montgomery is because, the way the rules are written, it is illegal to place a non-lettered tile on a lettered hex. Thus, it would not be legal to place a yellow tile in Montgomery.

Not sure that is as much a concern in 18xx.games, since the system will offer the legal tiles, but it might be a consideration.

**Comment by perwestling** [comment]
@ChrisTheCat But the rules does allow for a green M tile to be put in Montgomery even though there is no M label on the yellow tile...

The idea here, as I understand it, is to make it clearer for the users which tiles that will be possible to put in the hex in the future.  So by adding an M symbol you could tell the users that M tiles will be used in the future on this hex.  But it should not be the same M label as is used on the tiles as that might confuse the user to look for a yellow M tile.

An example where this would be very helpful is Guadalajara in 18MEX. Everyone seem to forget that it has a special tile. I think I even played a game where someone put a non-labeled brown tile in Guadaljara.
Now the 18xx,games tiles should stop you from playing a non-labeled hex when there is a labeled-hex available according to the game rules, but still it is not clear by looking at the map which special tiles will be used in the future.
