### ISSUE TITLE
St Louis: meat-packing token shouldn't hide W

### ISSUE THREAD

**Issue by chrispday** [tobymao/18xx#1699]
https://www.18xx.games/game/9764

Meat-packing was applied to St Louis (I1) this replaces the W.  The W should be retained to indicate this is a valid terminus for an E-W route.

AFAIK this does not affect payouts and should be considered a low-priority cosmetic issue.

**Comment by dfannius** [comment]
To be sure I understand, the issue is just that the display of the meat-packing token is hiding the W on the tile and there aren't any issues with the gameplay?

**Comment by dfannius** [comment]
There's a similar problem with Chicago, where the meat-packing token hides the city value:

<img width="123" alt="Screen Shot 2020-09-21 at 11 56 37" src="https://user-images.githubusercontent.com/1295244/93791028-b03a5080-fc01-11ea-947f-c04ccd0f32e7.png">

Maybe the meat-packing token should be placed on the "you can put the meat-packing token here" symbol in both cases, since it's not hiding any information by doing so.

**Comment by roseundy** [comment]
That is one busy tile. I think placing the token on the corresponding symbol makes sense.

**Comment by roseundy** [comment]
Part of the problem is that the code _always_ puts these kinds of markers (assignments) in only one location for pointy maps (as 1846 is). Part of the solution is to give the rendering more options of where to put it. This will still be a problem for Chicago as there's not a lot of good real estate left for a marker because of all the cities, track, labels and icons.

**Comment by benjaminxscott** [comment]
Maybe the 'marker location' can be changed to 9 o'clock rather than ~11 o'clock ? 
(then it doesn't cover the chi revenue or the StL "West" marker)

**Comment by roseundy** [comment]
There's no need to force it into any one position. The code has the ability to see where other placements have occurred on that tile and make a choice. I've been slowly modifying the code to make placement on pointy map tiles as flexible as on flat map tiles. It's assignment.rb's turn.

**Comment by roseundy** [comment]
With fix:
![1846_StLouis_Assignment](https://user-images.githubusercontent.com/8494213/94217047-49859300-fe9e-11ea-97fa-4dc70ca18ee5.png)
![1846_Chicago_Assignment](https://user-images.githubusercontent.com/8494213/94217050-4be7ed00-fe9e-11ea-8fab-982e05c80892.png)
