### ISSUE TITLE
1846 - remove unused icons

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#1762]
Companies/Corporations that can be removed from the game that currently leave icons behind:

* Steamboat Company
* Meat Packing Company
* Lake Shore Line
* Illinois Central (can only be removed in 2p Variant)

**Comment by benjaminxscott** [comment]
[LSL gets removed as expected](https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1846.rb#L132), I believe

It looks like the [corresponding company](https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1846.rb#L146) gets removed in the 2P variant, haven't tested

I think the [token removal logic](https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1846.rb#L443) can be added to `setup()` in order to implement the SC and MPC cases

**Comment by benjaminxscott** [comment]
I made https://github.com/benjaminxscott/18xx/tree/1846_remove_icons for after the feature freeze is thawn

**Comment by dfannius** [comment]
See also #5647 (Boomtown).

**Comment by benjaminxscott** [comment]
I have a PR for this
