### ISSUE TITLE
Ability to see popularity of a title over time

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#1826]
Sometimes Toby posts the popularity graph, would be nice if this could be automated and available for users

Might need some caching to avoid destroying the server.

**Comment by perwestling** [comment]
I think this does not have to be current numbers, but could be calculated maybe once per day or so.
It could show completed games, although ongoing games might also be of interest.

Think games abandoned before the end OR 1 might be ignored. At least those abandoned before end of SR1 or even before the end of initial auction, as there seem to be a fair amount of games that are quickly abandoned.

Also, I would like to see the graph over time, so it would be nice to have some historical data.

**Comment by scottredracecar** [comment]
I have been posting data Toby provides me for the top 10 games of the week on Twitter.

https://twitter.com/aag18xx/status/1358821594332880898
https://twitter.com/aag18xx/status/1356687529660084225

![image](https://user-images.githubusercontent.com/29106780/107878099-0d2af180-6e96-11eb-8d96-018a3ce54a4b.png)

Note that this ranks by actions, not games. This shows what people are actually playing rather than just games that started (which may or may not progress). The rankings appear to be somewhat heavily influenced by ongoing tournaments, but that is a true reflection of how the site is being used.

I think ideally, this would be autogenerated and posted from a dedicated 18xx.games Twitter bot.

I think it would also be nice to post this somewhere information including history on the site, but Toby said he doesn't want a UI for it on the site right now.

**Comment by dfannius** [comment]
I imagine that some games have a different density of actions than others (e.g., 1817 probably has a lot), but I dunno how much that really affects things.

I recommend using different colors for the up and down arrows in those tweets (and/or use negative numbers for downward movement); they all basically look the same to me unless I look at each one carefully.

**Comment by scottredracecar** [comment]
I don't have data on actions per game, but in general longer games are going to have more actions of course (1817 is the longest game on the site currently). Operational (OR-focused) games seem to me to drive actions as there are many steps that a player can do consecutively vs SR actions that require player switching between 1/2 actions.

The arrows are emoji which don't have color variations (AFAIK), but I will switch to using 📈 and 📉 because they are easier to differentiate. However, even those can be a little misleading as a game's popularity might go up over time, but if it goes up less than another game, its rank might still go down.

**Comment by jenf** [comment]
It'd be good to provide an automatic way for you to get the data, i'll pop it onto my queue for a bit.

I think the league table approach is probably best for both actions and new games

**Comment by scottredracecar** [comment]
There is some manual effort to not produce bad data. For example, I think Toby filters out migrations that shift actions to the recent week.

**Comment by jenf** [comment]
After discussion with Toby
`use redis to store
so create a new docker container like the queue
but all it does is rufus scheduler stuff
you could also put it in queue maybe`
