### ISSUE TITLE
1817 Liquidity should include private companies

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#1835]
In 1817, on the player boards and spreadsheet, the private companies should be included in the Liquidity calculation. They are available just like cash to use toward floating a company.

**Comment by jenf** [comment]
Probably should be 'Buying Power'

**Comment by tobymao** [comment]
companies are not a part of liquidity, and should not be reflected in that calculation. they would fit in buying power, but then you'd need another row for it in the ui

**Comment by ChrisTheCat** [comment]
Then please revise the request to add "Buying power" which is incredibly
useful. We always calculate it at the end of the auction.

**Comment by daniel-sousa-me** [comment]
I think that in 1817 it makes sense to just include them in liquidity. There is no case where you are interested in the liquidity excluding the privates.
And technically they are liquid assets, because you can sell them instantly to the companies you open

**Comment by jenf** [comment]
They are different values
Liquidity = how many shares could be purchased
Emergency Liquidity = how much a player can raise in EMR/Cash Crisis
Bidding power = how much can a player bid for

**Comment by daniel-sousa-me** [comment]
But you never care about that Liquidity on SR1 (because you can't have 5/10 share corporations) and you won't have privates after SR2. Technically you can have, but in practice you won't.

The difference with Emergency liquidity is just that you can't cause a change of presidency? If so, maybe we could still just have one row and show different values during an SR and during an OR to simplify the interface.

**Comment by jenf** [comment]
You cannot guarantee that every private will be sold in SR1 so they are different.
