### ISSUE TITLE
[18MEX] Player Should Be Allowed to "upgrade" 5% share of NdM for a 10% Share

### ISSUE THREAD

**Issue by TIE53** [tobymao/18xx#1921]
https://gist.github.com/TIE53/7a0b026e26209670a4c66a1d95908d63

A player owning a 5% share of the NdM should be able to purchase a 10% share of the NdM from the open market by "trading in" their 5% share for a 10% share and paying the difference in cost (rule 3.2.C.5).  This does not appear to be implemented.

**Comment by SmithInMN** [comment]
I believe that’s the 1.0 Trade-in shares which are shown. I’m working through a gabe also and you can sell 0.5 (if you have a half share) and buy a full share, but nothing about trading up that half-share.

I would need to pull the box to make sure, but can you buy a full share before trading your half-share up? I seem to remember there being something in the rules about this if you are close to 60%, that the trade-in is actually buying 10% and selling 5%, so if you are at 55%, you can’t since that would put you momentarily over 60%, but again, I‘ve not played this one in a while and that may not be entirely accurate.

**Comment by TIE53** [comment]
No.  There does not seem to be any way for me in this scenario for me to get from 45% ownership to 60% ownership. No combination of buying/selling will get me there.

**Comment by perwestling** [comment]
The trade-in ones is for minors close and NdM merge respectively, so they cannot be used until those events apply, in which cases they are given to the owners of the minors/merged. (If NdM merge does not result in a merge, the last trade-in becomes a regular IPO share.)

Swapping a 5% to a 10%, and vice versa, is not yet supported. On the wiki page one direction is mentioned to not being supported yet, but I believe neither direction is supported.
It is probably a bad idea to get rid of a 5% share but I suppose there might be reasons for doing this. But downgrading from a 10% to a 5% is a good one.

**Comment by TIE53** [comment]
I could see a scenario in which there are enough yellow companies that I don't care about cert limit and I'd rather just have that extra 5% ownership. 

Regardless, I just wanted to make sure it was being worked on. Thanks!

**Comment by perwestling** [comment]
Gist is no longer possible to be used, too much has changed, and original game has been deleted.
