### ISSUE TITLE
18MEX: Crash after selling 0.5 NdM share during emergency buy

### ISSUE THREAD

**Issue by nigelsandwich** [tobymao/18xx#1939]
I tried to sell some shares including my 0.5 share of NdM to emergency buy a 4D and it let me buy it, but I got an error message saying I didn't have the money. The other players couldn't go forward and every time I refreshed the page it went back to my corp's train buy phase.
https://gist.github.com/nigelsandwich/221c409da1195ba6b500566429c44b9f

**Comment by perwestling** [comment]
@nigelsandwich I backed the game until MC's turn, and could sell 5% without any problem, so I was not able to recreate it.

**Comment by nigelsandwich** [comment]
@perwestling Hi. Yes. I could actually sell it, but it would crash when I bought the 4D train and give me the error. I would refresh and it would go back to the train buy phase. It wouldn't crash when sold different shares.

**Comment by pstone1** [comment]
The error appearred to be caused by the money earned from selling the half share not properly registering. To reproduce, start here: https://www.18xx.games/game/13132?action=662 Sell the half share of NdM and then the full share, then purchase a 4D. We got the error message saying that nigel could not contribute $180 because he did not have enough funds, despite having $202 at that point. it was as if the $40 from the half share did not register, despite displaying as if it did. Any combination of selling that did not include the half share did work. 

I tried again this morning on a cloned game and could not reproduce, so perhaps something has been changed since.

**Comment by tobymao** [comment]
If this is a server error, cloning the game will not be able to reproduce
the issue.

**Comment by perwestling** [comment]
Right, it is a problem that is probably caused by the 5% share. Have been trying to solve that with an issue from pre-alpha testing but have still not solved it. 
But I can use this game as a test game for that, so I think this issue should be kept open until I solve the bug.

Thanks for the feedback.

**Comment by bjstover** [comment]
I got the same issue with selling a 1/2 share and trying to buy a 4D.
