### ISSUE TITLE
[1817] Coal tile placement restrictions

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2082]
When you use a coal private, the games allow you to place any tile in any hex in the list. It should only allow placing a tile you would normally be able to place. Furthermore it needs to be directly adjacent to a city

**Comment by SmithInMN** [comment]
1.2.6 says:  'When the owning company lays yellow track tile in any mountain hex adjacent to a city or red off-board location, it may also place one of its coal mine tokens. If it does so, it does not pay the usual $15 mountain tile fee. The yellow tile underlying the coal mine may not be upgraded. Coal mines must directly connect to a city or red off-board location, or be placed adjacent to a city such that if the adjacent city were sufficiently upgraded, it could directly connect to the coal mine.'

So there are some issues with the coal mines tiles, but my understanding of the rule has always been that if you built on Pittsburgh with a yellow E/W city tile, you could still place a coal mine yellow straight (for example) running NE/SW in that SW spot because even though you are not connected to it currently, it is adjacent to a city and you can connect to it reasonably through an upgrade.  This is the only exception I can see to the "normally be able to place" requirement since you are laying track which you can not use immediately.

E16 is the only mountain that can't contain a coal mine since it is the only mountain not adjacent to a city or red off-board area.

**Comment by daniel-sousa-me** [comment]
It can point to a city that is not upgraded, but you still need to be connected to the tile you are laying. It's an extra restriction.

**Comment by jenf** [comment]
Can you provide an example game?

**Comment by jenf** [comment]
Breaking down for me:
* It needs to be adjacent to a city (already done)
* There needs to be an adjacent city that
a) Has no paths and the path of the mine tile must face the city
b) Have paths, in which case the path of the mine tile must connect to that city

**Comment by daniel-sousa-me** [comment]
The most important thing is that it must be a legal tile lay. The company has to be able to arrive there from a station.

Furthermore it needs to be able to be directly adjacent to a city. In the sense that one of the ends must point to an adjacent city tile.
The city tile doesn't need to have a path there yet, only to be possible to upgrade. The only case when this "possible to upgrade" thing may matter if it's already a brown/B-gray city tile. So it is allowed if it has an end directly pointing at a city, unless that city is not upgradable and doesn't have a path to it.

**Comment by jenf** [comment]
Should I ensure there is a theoretical tile that can upgrade the city to point back or is that not done in real life games?

**Comment by daniel-sousa-me** [comment]
Fun fact: I only played live once.

But in the games I did in rr18xx I don't remember that ever being relevant, because usually the coals are placed early in the game (and then ones that aren't rarely matter)

**Comment by SmithInMN** [comment]
I've never quite interpreted that rule that way.  If it has to be immediately connected, then there is no reason for the qualifier 'or be placed adjacent to a city such that if the adjacent city were sufficiently upgraded, it could directly connect to the coal mine.'  That part would become irrelevant since there are never any other restrictions around what the other end(s) of a tile might do as long as one part is connected (except for the standard restrictions around off-board and grey, &c.)

The reality is that this doesn't come up very often since player are much more likely to actually lay track that they can use, but strategically could be important if you want to lay favorable track in a mountain before another player, who also has a coal mine private, does, especially since that track can't be upgraded.  The idea behind that extra bit of the rule was to prevent players from laying track that can't be used by anyone, effectively removing a hex from the map, for at least some period of time, to the detriment of the players and the game.  It's "teleport" track, to some extent, but it has to be provable that it can be used by the company laying it at some time in the immediate future from that city rather than just to tragic other players.

**Comment by daniel-sousa-me** [comment]
"When the owning company lays yellow track tile". It assumes the company is allowed to lay the track following the normal rules. It's not giving you the power to lay track elsewhere. And then later it has another restriction. But it never says anything about allowing to lay track in any different way than normal.
