### ISSUE TITLE
Show printed tiles in a slightly different color

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#2087]
The other day I wanted to lay a tile that was no longer available, so I tried upgrading a random spot to have the tile. Then I realised that I was upgrading a tile that was printed on the map and so it wouldn't make an extra tile available.

Maybe it would be nice to have some way to distinguish printed tiles from laid tiles

**Comment by michaeljb** [comment]
I'm going to try something--not with a fully different color, but just around the border, like the OO hexes on the AH 1830 map

Bad quality picture but still easier than taking & uploading my own:

![](https://headingleygamesclub.files.wordpress.com/2013/03/100_2999.jpg)

**Comment by daniel-sousa-me** [comment]
Different border is a very good idea. I'd put it everywhere. The hexes that come by default on the map could have a thin border and whenever you lay a tile you get a slightly thicker border. Or maybe something that looks like a shadow.

**Comment by michaeljb** [comment]
I'm not convinced it needs to be everywhere. I think just identifying "preprinted tiles" that could otherwise be mistaken for tiles from the tile manifest is enough:

## 18 Los Angeles

![Screenshot from 2020-11-20 12-10-12](https://user-images.githubusercontent.com/1045173/99840245-6ef2ee00-2b29-11eb-8fbc-07a613d1c69b.png)

## 1882

![Screenshot from 2020-11-20 12-18-24](https://user-images.githubusercontent.com/1045173/99840856-89799700-2b2a-11eb-8159-a0cb9c8a7285.png)

## 18AL

![Screenshot from 2020-11-20 12-21-11](https://user-images.githubusercontent.com/1045173/99841114-e70de380-2b2a-11eb-9dd7-575f22d57e3d.png)

## 18TN

![18TN](https://user-images.githubusercontent.com/1045173/99842338-de1e1180-2b2c-11eb-9d59-a68164011113.png)

## 18MEX

![18MEX](https://user-images.githubusercontent.com/1045173/99842347-e2e2c580-2b2c-11eb-9442-3e58eb59f766.png)

**Comment by daniel-sousa-me** [comment]
Those look very nice!

When I suggested making the change everywhere, I was thinking about something completely different, but I really like your solution.

**Comment by yzemaze** [comment]
@michaeljb looks good to me.
