### ISSUE TITLE
2/5/10 share graphic presentation improvement suggestions

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#2088]
<img width="151" alt="Screen Shot 2020-10-28 at 8 26 53 AM" src="https://user-images.githubusercontent.com/8732435/97457867-62e38a00-18f7-11eb-8274-0c83257f25b6.png">

Would it be possible to indicate on the market which corporations are 2, 5, and 10 share? This could be by making the icons different sizes, or putting colored borders around the icons.

Also, during an OR or M&A round, it would be nice to indicate on the market which corporations have acted, or are ineligible (e.g. if a company moves into the acquisition zone during the round, it won't be eligible for acquisition that same round).

<img width="935" alt="Screen Shot 2020-10-28 at 8 30 11 AM" src="https://user-images.githubusercontent.com/8732435/97464540-4434c180-18fe-11eb-8b9a-f6ff9f531395.png">

Similarly, it would be nice to know which corporations are 2, 5, and 10 share size during the M&A round (shown above).

**Comment by jenf** [comment]
Modifying the market is viable, does this make intuitive sense?

Different colour borders is not a viable solution, as one enhancement requests it to show a different border for different players.

![Screenshot from 2020-11-13 13-41-38](https://user-images.githubusercontent.com/71923/99079299-a86eab00-25b7-11eb-8d49-89d8f6fe170d.png)

I'm trying to work out a way to do the entity bar, but this is more challenging due to formatting.

**Comment by ChrisTheCat** [comment]
Looks great to me.
