### ISSUE TITLE
[18Mex] Copper Canyon allowing illegal routes

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#2149]
Copper Canyon should not allow the below route as it reuses track, game 14352

![298F81A3-C280-4C0C-B8ED-3596F105F396](https://user-images.githubusercontent.com/73144084/97793925-38305480-1bc9-11eb-9523-5d02ab97cc6e.jpeg)

**Comment by roseundy** [comment]
Currently, the code only checks to make sure an exit isn't used twice. No check is ever made between paths to/from a city or town. For instance, if the tile had been rendered so that the town was in the center of the tile, there would be no conflict. This is going to take some thought and some more complexity to the code to calculate when track conflicts exist at town/cities.

**Comment by perwestling** [comment]
Would it be possible to render it as a T, with the town in the middle of left or right of "rough"? I think the end result would be the same if the tile looked like that.

**Comment by roseundy** [comment]
Game 14352 is an 1846 game. Is there a game that I can test my fix with?
