### ISSUE TITLE
[18MEX] NdM sales not displaying half shares in dialogue box 

### ISSUE THREAD

**Issue by eheiden** [tobymao/18xx#2218]
https://www.18xx.games/game/13026?action=698

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
In SR6, when I click the NdM to potentially sell a share the dialogue boxes for sales display two different options for "Sell 1" vs either "Sell 1" and "Sell 0.5" or "Sell 2" vs "Sell 1"

![image](https://user-images.githubusercontent.com/1738619/98398456-05ee7f00-202f-11eb-8df0-539512fec460.png)

**Comment by jenf** [comment]
Looks like a display issue

**Comment by perwestling** [comment]
Yes, you are selling one paper....

The problem is if you would have 2 5% it would show 
Sell 0.5 ($60) Sell 1 ($120) Sell 1 ($120)
as the first would be to sell 1 5%, the second would be to sell 2 5% or to sell 1 10%.
How would you now the difference?

Ok, then say we just show sell 0.5 and the sell 1 would be just 1 10%? And if you want to sell both 5% you would have to sell twice?
But then I would guess there would be an issue about not showing the possibility to sell 2 5%.....

So I guess we would have to change the text on the button (for NdM only) to:

Sell 1 5% ($60)    Sell 1 10% ($120)

But that might look a bit cluttery with the 1 and 1 so close?
So what about

Sell one 5% ($60)  Sell two 5% ($120) Sell one 10%  Sell two 10% Sell three 10% and so on
But that would use up a lot of space....

As you can see it is not trivial.
