### ISSUE TITLE
18MEX game card rendering error

### ISSUE THREAD

**Issue by biddu6566** [tobymao/18xx#2253]
18MEX game does not render card on homepage. Asks to clear local storage but doing so does not help. Tried doing it on different devices. Same issue persists

https://www.18xx.games/game/13076

This is what shows up on my games page

Error rendering game card... clear your local storage: {"id"=>13076, "description"=>"Fast Async minimum 4 turns a day", "user"=>{"id"=>3922, "name"=>"shadowdart13"}, "players"=>[{"id"=>2734, "name"=>"winn1098"}, {"id"=>3244, "name"=>"steph.jehl"}, {"id"=>3799, "name"=>"SwanofTrumpeter"}, {"id"=>68, "name"=>"Spaul"}, {"id"=>3922, "name"=>"shadowdart13"}], "max_players"=>5, "title"=>"18Mex", "settings"=>{"pin"=>"c91f8643", "seed"=>3.100537911501665e+38}, "user_settings"=>nil, "status"=>"active", "turn"=>6, "round"=>"Stock Round", "acting"=>[2734], "result"=>{}, "actions"=>[], "loaded"=>false, "created_at"=>1603077972, "updated_at"=>1604898262}

**Comment by tobymao** [comment]
This is a temporary issue due to pinning games and changing the name of all 18Mex games to 18MEX. You can still play the game but it won't show up on the home page anymore. 

We'll delete these pinned games when they're finished.

**Comment by perwestling** [comment]
I can go to the game just fine by following the link. Do not get the "clear your local storage" for that.

The game was pinned as it broke the rules, and used a bug with the Copper Canyon tile. 
https://www.18xx.games/game/13076?action=543

So the game was not possible to correct, and is therefor pinned. As it is an alpha game there is nothing to do.

So I suggest this issue is closed.

**Comment by perwestling** [comment]
I don't think there is anything to do, so I close this issue.
