### ISSUE TITLE
1846 - Skips straight onto routes after buying Minor

### ISSUE THREAD

**Issue by Blobbley** [tobymao/18xx#2257]
I’m in a game on 1846 where I’ve backed myself into a bit of a corner and trying to go out of it.

In OR2.1 I’ve got $20 in PRR and also own Big4 which has $20. I want to buy PRR for $20 and then lay track with Big4s $20 but when I do so it skips directly to run trains step.

I presume that this is because the sequence goes: Spend $20 > have no money to lay track therefore skip to run trains > receive Big4 and $20

 (GAME ID 15112)

**Comment by michaeljb** [comment]
Sounds somewhat related to #2032. Keeping both tickets open as I'm not sure they have the same underlying cause.

https://www.18xx.games/game/15112?action=91

Also saved to gist at https://gist.github.com/michaeljb/80aa7593b32c484927b03a0e3df27c87

**Comment by michaeljb** [comment]
The problem is the pass action, id 88 - https://www.18xx.games/game/15112?action=88

That pass already skips the track and token step before BIG4 is bought in.

At [action 104](https://www.18xx.games/game/15112?action=104), enough "undo" actions were done to undo the "pass" action at 88. PedroS ended up buying for only $1, but the key thing was undoing to before 88.

Here's a gist where buying in the BIG4 for the full $20 works fine; you can copy and paste the file contents into the the "Import game (hotseat)" on the [create game page](https://www.18xx.games/new_game) - https://gist.githubusercontent.com/michaeljb/91c5b9038741f2e00054e21a2ae91616/raw/5cf8162aa0e84861c181d565baa0e719678cd1c7/2257-fix.json
