### ISSUE TITLE
Web Push Notifications with service worker when you can make a turn

### ISSUE THREAD

**Issue by Zwergenpunk** [tobymao/18xx#2275]
Since I'm in the 1846 tournament I have multiple games open and regularly check my phone if there is a game where its my turn. 

It would be awesome to have push notifications for mobile devices.

There is the web push api which can be used to generate a push message for client. With a service worker you csn subscribe to the push request and a notification can be shown if the user granted the permission.

I could try to implement it myself but I never wrote nor read one line of ruby code in my life. But if there are more people intrested I could give it a try.

[This](https://medium.com/izettle-engineering/beginners-guide-to-web-push-notifications-using-service-workers-cb3474a17679)  is an beginner guide for thr concept.

And [Here](https://github.com/zaru/webpush)  is Potential framework to use.

What do you guys think?

**Comment by beginetienne** [comment]
I get discord/slack notification 18xx.games.  As long as a browser is not sitting on the game somewhere on my many devices.

The setup is a bit complex, but here it goes:

You can setup automation using IFTTT or quickwork.co to receive discord/slack updates.  This automation service is basically receiving a push from gmail/outlook.com when you receive and email, then turns around to post on a webhook URL generated by discord and slack.  You can choose how to be notified, it can be something other than discord/slack.

Obviously, you want only certain emails to post on your discord server.  The email sender and subject can be used as filters.  Many options are available.  

Whenever my outlook account gets an email from 18xx.games, it moves the email to a folder called PBEM using outlook rules.  Then quickwork.co is notified immediately of this new entry to the PBEM folder, which then posts a message to a discord webhook.  I'm basically redirecting important emails to discord/slack messages.  The notification appears before my outlook gui client even receives the email.  

I manage all my PBEM games like this since a majority use emails for notification (rr18xx, twilight struggle, ACTS, VASSAL games, etc etc.)

here's an example on my discord server

![image](https://user-images.githubusercontent.com/67706969/98860160-3bc9a400-2431-11eb-87e0-d7d060202c14.png)

I did not parse the email body for the URL, just getting the game ID is good enough for me.
