### ISSUE TITLE
1817:  Permanent Market, Train Roster

### ISSUE THREAD

**Issue by Avemo3** [tobymao/18xx#2279]
With Operating Order so important in every stage of 1817, it would be really beneficial to keep the Market affixed to the bottom of each stage.  It would save a lot of flipping back and forth to be able to have at least a rough idea of operating order at a glance.   

Additionally, during operating rounds, It would be nice to be able to see train roster beneath the company charters while they are operating.   Also, the Loans market in the same area would be cool.

Thanks for the consideration!

Avery

**Comment by SmithInMN** [comment]
There's a lot to see and consider, in this title especially.  Playing on here has made me realize how playing IRL is a lot easier visually in so many ways because everything is laid out...  although the automation on here offsets that by some degree.

The point is that the layout limitations might be something that we have to accept.  I agree that your suggestions make sense, but at what point do we just have everything on one big cluttered screen?  There's a tipping point, I suppose, but I have no clue where that might be.

**Comment by jenf** [comment]
The operating order is available on nearly every state apart form Acquisitions (which is a separate issue)
In Stock market the corps are in reverse order.

I'm not sure what this adds apart from a busier layout.
