### ISSUE TITLE
Add pictures to the wiki describing how to activate/use private company ability

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#2284]
We do get support questions about some privates. E.g. the KMC&O (Copper Canyon) in 18MEX.

It is explained at the wiki page in many 18xx (e.g. 18MEX, bullet 6 or so, under Implementation notes), but it is still mistakes made. So I would suggest to add pictures. 

E.g. for 18MEX
Add a picture that points towards the ability, showing where to click
Add a picture of a board fragment showing to click at F5, and that is shows the available tiles
Possibly a third picture that shows in placed, in an orientation not default
Possibly add some description under each picture

I would recommend doing this for one title at least to try it out. As 18MEX already has a picture showing how to route on that Copper Canyon tile I think that is a good candidate. Consider if there is any more places on that 18MEX wiki page where pictures would be nice.

**Comment by giovandc** [comment]
A common problem is that players don't know how to activate an ability, since clicking on it shows the description, and the player is lead to believe that the effect of clicking stops there, while it actually activates it. Also is not clear which ability is activated and which isn't, and I think that making the ability a button that you can toggle can help this UI issue. See for more details https://github.com/tobymao/18xx/issues/2190

**Comment by jenf** [comment]
Is this issue still valid?

**Comment by giovandc** [comment]
I don't think so, it's very clear now that the ability is a "button"

Il giorno lun 8 feb 2021 alle ore 14:38 Jennifer Freeman <
notifications@github.com> ha scritto:
