### ISSUE TITLE
18MEX: Indicate in the spreadsheet that a company has merged and not available to be started

### ISSUE THREAD

**Issue by jerryyeti** [tobymao/18xx#2287]
It would be beneficial after a merger if the closed company had some sort of indication in the Spreadsheet that it is not available to be re-started.  Right now it looks like a normal company that has not yet started and has 10 shares available.  The merged company is removed from the Entities tab, so if a different indication is not possible, consider removing it from the spreadsheet altogether after the merger.

**Comment by perwestling** [comment]
Removing it from the spreadsheet might be less good as it removes the OR runs from the spread sheet.
I assume e.g. strike through could be used to show that it is "dead".
In e.g. 1817 or 1849 the closed corporations can be floated again, so for them the current presentation would be enough.
But in e.g. 1856 they are closed for good when nationalized. So that would need this notation.
