### ISSUE TITLE
18Mex - minors do not run when all players pass in ISR

### ISSUE THREAD

**Issue by curlett** [tobymao/18xx#2331]
18Mex - if all players pass in the ISR there should be an operating round. But instead privates pay and minors do not run. 

Hotseat game - https://gist.github.com/curlett/7bd1ff71f31c4a6229c4beda6c525782

**Comment by michaeljb** [comment]
This same thing needed fixing for 1846 2p Variant in https://github.com/tobymao/18xx/pull/1772, maybe something there can be generalized?

**Comment by perwestling** [comment]
I think it would be possible to redesign the round a bit so that the initial auction is just first, and then OR.
If we enter an OR and no corporations/minors are floated just skip the OR.
When a round starts, and auction is not yet completed, enter the auction again.

This would also mean that a bought company with connected minor should float it in 18MEX.
And that all floated minors should run in OR1.
Then back to Auction of SR2 and so on.

**Comment by perwestling** [comment]
Generalization would include a reimplementation of #1146 which was intended to solve #1092.

**Comment by perwestling** [comment]
This turn out to be a difficult implementation. I am considering doing a simplified version:
- Let "floated" minors pay out $15 to owner, $15 to treasury (which they would have gotten if they had run).
- For all other purposes keep the implementation as is.

It is not perfect but it is simple. We can revisit this in the future when we need to implement a more advanced initial auction.
