### ISSUE TITLE
[18MS] - No option to buy over train that didn't operate

### ISSUE THREAD

**Issue by Auzzy** [tobymao/18xx#2515]
Hotseat game data: https://gist.github.com/Auzzy/34057cbfa07c509868858a4d12c45e31

During OR 6, the L&N only ran its 4+, and did not run its 3+. Later in OR 6, IC wanted to buy the 3+ from L&N, which had not run, but the option was not presented.

In the current version of the rule book published by All-Aboard Games, it states in both 11.8 and 11.9: "No company may ever purchase a train that has operated during the current OR and is scheduled to be obsolete at the end of the current operating round."

The "and" sounds like both conditions must be true. So if a train is scheduled to be obsolete, but it did not run this OR, it should be purchasable.

This occurred during a multi-player game, but we undid and moved past it, so I don't know if that's helpful. If it is, here's the game, undone to just before L&N runs trains: https://18xx.games/game/17047?action=243

**Comment by TIE53** [comment]
@Auzzy You cannot voluntarily choose to not run a train just to provide the option to cross-buy it later. Since the company owning the train has operated, you can no longer buy over the train.

**Comment by Auzzy** [comment]
@TIE53 Can you point me to where this was clarified? Because I must either be missing it in the rules, or maybe it was clarified somewhere else. The closest I see addressing this is at the beginning of section 11: "The major company may run any or all of the trains it owns."

**Comment by TIE53** [comment]
@Auzzy If we're getting pedantic, the rules say that you can't buy a train that has "operated" this OR and is due to be rusted, whereas the run trains section refers to "running" the trains.  In practice, I'm almost 100% positive that this is the intent of the rules. You may not buy a train over that is due to be rusted that OR if the company owning the train to be bought has already operated.  

It's not a bug, but possibly a rules clarification.

**Comment by dfannius** [comment]
Section 11.6 does talk about "operating trains", so the verb is (unfortunately) used for trains as well. In my opinion the rule is ambiguous as written, although I'm 80% sure that TIE53's interpretation is intended. I think it would be worth it to reach out to Mark Derrick for clarification.

**Comment by Auzzy** [comment]
I definitely agree that mismatch of wording adds to the confusion. I could see either interpretation being correct, so yeah, reaching out to Mark Derrick is probably the way to go.

**Comment by perwestling** [comment]
It should be noted that the 11.6 also states:
"The combined revenue of each train’s run is the company’s earnings. A major company must run its train(s) each turn for the
greatest earnings possible, if any player who owns stock in the company insists. However, players who spot a better paying route
or combination are not required to point it out."

So unless you are the sole share holder of the "major company" it is likely a bad thing to do this maneuver. But if you are solo shareholder, it might be OK.

 https://boardgamegeek.com/thread/2552307/article/36413389

**Comment by perwestling** [comment]
Have notified designer about the rule question.

**Comment by DogmeatDeluxe** [comment]
I have tried to look at the game in question.  Assuming that you are using the optional rule that allows the purchase of trains scheduled to rust at the end of the current OR, there is no reason that the train in question couldn't operate for the L&N then be purchased by a later operating Major Corporation during the train buying portion of the purchasing Major Corporation's operating turn.  There is no requirement that a train somehow fail to operate in order for it to be purchased over.  This optional rule was largely developed by Scott Petersen and I am assuming that it wasn't his intent to allow rusting trains to be purchased at any other part of the purchasing Major Corporation's operating turn.

I have always used the concept in all of my games that a train "operates" at the revenue calculation portion of the operating turn.  Even if a train has no legal route, it "operates".  Any rules about operating for the greatest amount that can be demonstrated goes all the way back to 1830 where some arguments came up about whether a president could intentionally undercalculate a Major Corporation's income which some rules lawyers have argued can have tactical value in some situations.

[start rant]  Everyone wants shorter 18xx rules but honestly, I've had to add rulings in my rule sets for idiotic situations such as " in emergency money raising, can I sell shares one at a time in order to get less money from the sales?" because I keep getting asked stuff like this.  Perhaps in 1 game in 1000, this could actually have some merit or make a big difference in who wins the game, but what it absolutely does is bloat the rules.  This is not to reward some tactical brilliancy. If you are in emergency money raising, you are probably not running away with the game.  Anyway, I try to make rules as clear as I can while, hopefully, minimizing errors or potential contradictions.  I know things will never be perfect but players should understand that any time they use an optional rule, it might possibly make the regular rules confusing, but hopefully not contradicted. [end rant]

**Comment by perwestling** [comment]
I think it is not about the optional rule - using that it is allowed to make the purchase (but still not running might be hard to accomplish).

In this case I do not believe it is such a "useless" rule, as if it is possible it could help players win the game, as it can make it easier to shift money between their corporations. And also there is a Variant rule (as mentioned) about this so I can understand why it came up.

DogmeatDeluxe's example of selling slowly I think is more a case of wanting to quit the game....
About obscure rules that has had an effect on the hobby I could mention the ruling that you can win even if you go bankrupt. That created a "Holy Grail" for the hobby, which a few players have managed to accomplish.

**Comment by perwestling** [comment]
Just to be clear - if you check the Info tab it will specify if any Optional Rule is used in a game. (Can also be seen in the very top of the log of the game.)
The game in question **does not use any** Optional Rules.

**Comment by Auzzy** [comment]
@DogmeatDeluxe is Mark Derrick's username, right? If so, then looks like we have an answer:

> I have always used the concept in all of my games that a train "operates" at the revenue calculation portion of the operating turn. Even if a train has no legal route, it "operates". 

So once a railroad has operated, all of its trains are considered to have operated, even if they generated zero money, which means the site's implementation is correct.

**Comment by DogmeatDeluxe** [comment]
Per, thanks for clearing that up. I could have sworn though that the 18MS game was described as using the optional rule that allows rusting trains to be purchased. Just to be clear, in the base game with no optional rules used, trains scheduled to rust at the end of the OR may not be purchased by other Major Companies. If the optional rule is being used, then trains that are scheduled to rust may be purchased by other Major Companies whether or not they have operated in the OR. 

Mark

**Comment by Auzzy** [comment]
@DogmeatDeluxe That description contradicts the All-Aboard rulebook, so I just want to ensure I understand what you're saying, since I of course consider your ruling as correct.

Rule 11.8 of the All-Aboard rulebook says:

> No company may ever purchase a train that has operated during the current OR and is scheduled to be obsolete at the end of the current operating round.

My reading is that a Major Company may buy a train which will become obsolete at the end of the OR if it hasn't already operated. So if IC operates last in OR 6, L&N may buy a 3+ from it, since IC hasn't operated yet. Are you saying that no, even in that case, L&N cannot buy a 3+ from IC?

**Comment by perwestling** [comment]
The designer has spoken. So the behaviour of 18MS at 18xx.games is correct.

I will add this rule clarification to the wiki.

**Comment by DogmeatDeluxe** [comment]
Austin, I'm sorry for any continuing confusion over this. 

If it does pertain to the 18MS base game, with no optional rules being used, and assuming that the L&N operates before the IC, then the L&N could purchase a 3+ Train scheduled to rust at the end of the operating round from the IC because it hasn't operated. Note that all train purchases occur after trains have "operated" during the purchasing Major Company's operating turn. Therefore the 3+ Train purchased from the IC will not operate for the L&N before the train rusts at the end of the OR. Again, my concept is that trains "operate" at the moment when revenue is calculated whether they have a legal route or not and whether the president chooses to under-report its revenue or not. 

The IC may not purchase a rusting train from the L&N because it has already operated for the L&N, whether it generated income or not. I think part of the confusion is due to a player thinking that by not declaring any revenue for the 3+ Train during the L&N's operating turn, that it has somehow not operated. This should be consistent with the existing rules. 

If the optional rule is being used, then in this example, the IC could purchase the L&N's 3+ Train that has previously operated even though this contradicts the base game rules. Optional rules tend to contradict the regular rules. 

I hope this answers your questions. 

Cheers, 
Mark Derrick

**Comment by Auzzy** [comment]
Cool, that all makes perfect sense and clears up any lingering confusion I had. And you're exactly correct about where the original confusion came from. But your definition of "operate" clears up the rulebook. I'll be sure to carry it through to any question on other games of yours.

Thank you so much for taking the time to address these questions! And sorry for being a pain. =)
