### ISSUE TITLE
18LA - Only given option to buy 7/8 train (not 6 train) in phase IV

### ISSUE THREAD

**Issue by vantdog** [tobymao/18xx#2589]
https://18xx.games/game/17242?action=488 (I think)

Player Frank is only offered the option to purchase a 7/8 train - not a 6 train. We are in phase IV, OR 5.1, and he is trying to purchase the first train for PER, which he has just floated in SR 5.

-Tim

**Comment by michaeljb** [comment]
The rules enforcement is correct here, though the interface could definitely be better (see #2219).

At https://18xx.games/game/17242?action=485, PER doesn't have enough cash to buy a train, so it must first "emergency issue" shares. Emergency issuing is different from issuing earlier in the turn in that for each share issued, the corporation's share price moves one step to the left, and then the cash received is the value one left of wherever the price ends up.

PER is allowed to issue enough shares to buy the 6T _or_ 7/8T, but cannot issue more than necessary (https://boardgamegeek.com/thread/1849992/article/26952925#26952925)

So to buy the 6T, PER needs to issue 2 shares and gain $200, but by issuing 4 shares and gaining $320, PER can afford the 7/8T and so it is obligated to buy it. (actually, it may be a bug that PER is presented the option to issue 3 shares to gain $270, since issuing 2 is enough to buy the 6T but issuing 3 is not enough to buy the 7/8T).

Strategic note: all of this would be avoided if the PER issued shares earlier in the turn, where they would each put $124 into the PER's treasury, issuing would not drop the stock value, and there would be no obligation to buy any particular train.
