### ISSUE TITLE
Include in "Last Run" info on how many/which trains ran in previous OR.

### ISSUE THREAD

**Issue by bridger15** [tobymao/18xx#2724]
On the company cards, I'd like to expand the info available at the bottom where it details "last run: $XXX".  When evaluating a company, it's valuable to know not only how much they made last OR, but how many trains were used to make it.  In the below example, the BESS company has 3 trains, and ran for $240 in the previous OR.  If you assume that they ran all 3 trains to get that 240, then you would significantly undervalue the company.  In this game, the company ran 2 trains, then _bought the third_, which means it will pay out a good deal more in the next OR, so it might be worth buying.

I was envisioning something like this (maybe have the train specific info in a slightly different font, or slightly smaller, so it doesn't make it hard for the "Last Run" info to stand out).

![Like This](https://i.imgur.com/5iHSbw5.png)

**Comment by PedroRCSequeira** [comment]
this is a good suggestion, i think i've mentioned it somewhere

sometimes it also works the other way, when a company ran and then lost/sold a train, so looking at last run $ only will make it seem better

**Comment by andypymont** [comment]
I don't think this is really going to solve the issue it's hinting at, because there are many, many things that could change from run-to-run which will change a corporation's revenue (potential) vs. the previous run:
- Train situation (old trains rusted, new trains bought, trains cross-bought out of the corporation by another later in the operating order, etc.) as mentioned in this issue
- The corporation may have been tokened out in some location(s) blocking the route(s) it ran - or in some titles have new access to higher-revenue runs because corporations that had previously blocked it with tokens have disappeared (closed, nationalised, acquired, merged with one another, etc.)
- Private companies may have closed which were enabling a certain route or revenue
- Phase changes and tile lays usually increase a corporation's run value, but it may also decrease for some locations (OOs where its legal to hit both sides merging into one city, the rarer cases where phase revenue for a city or offboard decreases, etc.)

Ultimately I think there are too many factors that can change how much a corporation runs for and therefore how valuable a share in it is. The last-run revenue is only ever guidance and I'm not sure it's ever going to be possible to fully automate this information without some extra wrinkle being possible in some game which will catch people out if they use it as too much of a crutch without developing the skill to assess share values "by hand".
