### ISSUE TITLE
18CO- Company is allowed to purchase shares from market or president, but not both

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#2914]
https://18xx.games/game/20640?action=219

In this game, the DSNG has plenty of cash to buy a KPAC share from the president (TIE53) and a DPAC share from the market, but it does not look like I am able to do that. The interface lets me buy 2 DPAC shares, but not one of each, despite having the cash.

**Comment by ryandriskel** [comment]
The 18xx.games implementation is correct. The change from allowing all corporate shares to having to pick one corporation's shares to purchase was lost in a version update to the rules. My apologies. 

I have updated the rules at https://drive.google.com/drive/folders/0B3lRHMrbLMG_eEp4elBZZ0toYnM

As an aside, this change was made because otherwise the game boiled down to running the highest value corporation, which could then simply buy all the shares available.
