### ISSUE TITLE
[1867] Opening Bid passing prevents bidding once an opening bid has been made.

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#2946]
During the privates auction, a player who passes on placing an opening bid on a private is not being allowed to bid once the auction has started. This action is correct after an opening bid has been made, but not for passing on making the opening bid.

**Comment by jenf** [comment]
From the new 1867 rulebook:
"A player who passes may not rejoin
the auction for that Private Company."

However, I do think it's a little ambiguous.

**Comment by jenf** [comment]
@ianwilson156 what's the correct interpretation of the rule?
During the initial private auction if a player passes and then someone bids can they rejoin?

**Comment by ianwilson156** [comment]
This has always been a little difficult to explain. I prefer to use the word "decline" to mean "not put up anything". Then the passing rule is clearer: declining is not the same as passing, so you can enter the auction.
As the wording stands, it is ambiguous, but the answer is yes (because the auction hasn't started until somebody makes a bid).
