### ISSUE TITLE
1817WO - Game Bugs/Breaking

### ISSUE THREAD

**Issue by jerryyeti** [tobymao/18xx#3040]
Two bugs.  Game: https://18xx.games/game/20369

Both resolved by taking a loan first (even when not needed).

**Issue 1 - Could Not Place Pittsburg Tile.** 

_We're sorry this game cannot be continued due to GameError: I6 is not upgradeable to X00
Broken action: { "type": "lay_tile", "entity": "R", "entity_type": "corporation", "id": 113, "hex": "I6", "tile": "X00-0", "rotation": 0 }
Please raise a bug report and include this link (https://18xx.games/game/20369?action=112) and the following JSON data_

If you try to place the Tile immediately, there is the error.  If you take a loan out first, it gets around it.

**Issue 2 - If have $0 and Click Done Trains, when it tries to pay interest, it gives a bug and doesnt automatically take a new loan to cover the interest:**

_We're sorry this game cannot be continued due to GameError: R has 0 and cannot spend 100
Broken action: { "type": "buy_train", "entity": "R", "entity_type": "corporation", "id": 130, "train": "2-2", "price": 100, "variant": "2" }_

https://18xx.games/game/20369?action=121

I was able to repeat both bugs in hotseat mode as well.  Taking loans manually allowed the game to continue (despite that message).

**Comment by ventusignis** [comment]
I made a hotseat clone and I poked around a little bit
This serious of actions reproduces the error:
1: Click on the New Pittsburgh Hex to bring up the plain track upgrades
2: Click on the Pittsburgh Steel Mill ability
- The 3 yellow city upgrades are replaced with the pittsburgh B tile -
3: Click on the B tile
4: Accept

This causes the "not upgradable to X00" error
After this doing any normally valid action causes the Broken game message


Refreshing the page "resets" the broken state
If you instead follow these steps it all works
1: Click on the Pittsburgh Steel Mill
2: Click on the B tile
3: Accept

It works, and you can take a loan before or after


The issue here appears to be that clicking the [Pittsburgh Steel Mill] ability button doesn't properly exit the "normal tile lay" step before entering the special tile lay step

**Comment by ventusignis** [comment]
I was able to reproduce this by repeating the erroring steps in a hotseat game of 1817 so this is common to all of 1817, 1817NA, and 1817WO

**Comment by michaeljb** [comment]
Are these still happening or was this fixed by 9cf3c5398199a596e4bb126361dc40d493ce2c66?
