### ISSUE TITLE
18SJ: Show Nils Ericsson ability for player even after the private is closed

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#3144]
Nils Ericsson can be a bit confusing, could we add abilities for players so it's visible even after the private has closed.

**Comment by perwestling** [comment]
I am thinking of changing this so that the buy of Nils Ericsson gets an extra private (that are not counted for cert limit) that represent the "steal priority deal". This is closed when used, so it may survive phase 5 and later.

Suggested name: Nils Ericsson's Första Tjing ;-) But I can check with Örjan Wennman.

Alternative is to change revenue for Nils Ericsson to 0 when train bought. And close it when steal has been done.

**Comment by perwestling** [comment]
@Nisse75: Any thoughts on this? Do you prefer a separate paper for this, or should it be done with magic on the existing? And what should be the name of such an extra paper?

**Comment by Nisse75** [comment]
”Nils Ericson’s Första Tjing!”. That’s hilarious, lets do that!

**Comment by perwestling** [comment]
GUI when choice is taking place:
![image](https://user-images.githubusercontent.com/2631151/104093326-2be00c00-528a-11eb-9c2f-e2f21ae28a6b.png)

Log text when ability used:
![image](https://user-images.githubusercontent.com/2631151/104093423-b88aca00-528a-11eb-83ea-a6a92870148b.png)

Description. Does not affect certificate count for player. Not closed when phase 5 starts.
![image](https://user-images.githubusercontent.com/2631151/104093382-86796800-528a-11eb-9e45-eb4509071186.png)

**Comment by Nisse75** [comment]
This looks great!
