### ISSUE TITLE
Call out when bank has been broken

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#320]
Moved out as a separate issue from a comment in #262.

**Comment by Djeefther** [comment]
I think this issue is already closed.
I play one matched that in the log this shows up:

"
Philipe receives ¥102 = ¥51 x 2 shares
Djeefther receives ¥204 = ¥51 x 4 shares
-- The bank has broken --
Sakuragi receives ¥102 = ¥51 x 2 shares
"

Or, the issue is not about logging it, but about alert the players.

**Comment by dfannius** [comment]
Yes, it's always been in the log; this issue is about making it clear in the UI that we're in a final-set-of-ORs state, since the log message scrolls away.

**Comment by jenf** [comment]
I'd suggest we just change
Operating Round 7.3 - Lay Track
to
Operating Round 7.3 - Lay Track (Bank Broken game finishes at end of Round 7)
