### ISSUE TITLE
1861: Implementation map

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#3229]
Take 1867 as base

### National railway
- [x] The token in St. Petersburg is placed when the RSR first operates, if one does not already exist on the tile. If one already exists on the tile remove the reservation.
- [x] When Moscow upgrades to silver, immediately place a token there if one does not already exist in Moscow (operates like Montreal). 
- [x] No more than six RSR tokens can be placed outside of St. Pete and Moscow.
- [x] All assets from nationalized companies go into the RSR. Loans are not assets.
Privates owned by the RSR pay their income to the RSR.
- [x] Note: When privates are nationalized at the start of phase 6, the RSR is not paid face value for the privates that had already been nationalized.
- [x] RSR has no stock value and always operates last in an OR. This is still part of the OR.
- [x] Must purchase a train when it first operates, taking as many loans as necessary, no limit.
- [x] The RSR lays no track or tokens, running only on existing track, but follows the standard rules for routes, running for the maximum earnings.
- [x] The RSR always withholds, pays off as many loans as possible, and always purchases the cheapest available train if it is able, Bank or Pool/Discard, with no train limit.
- [x] The A-A Games rules don't address who is responsible for determining the RSR's runs. GTG rules states it's the player with priority in the coming Stock Round.

### End game
End Game:

- [x] If the first 8T is purchased in the first OR of the set, complete the current OR then run two more ORs with no stock round
- [x] If the first 8T is purchased in the second OR of the set, finish the set, do a Stock Round, then run three more ORs

### Nationalization
- [x] Nationalization moves 1 instead of 2
### Stock Round
- [x] Nikolaev must be auctioned first
- [x] Home tokens are assigned for minors
- [x] If no unconnected cities exist major cannot be started
### Map
- [x] Track
- [x] The Kiev hex costs to upgrade from green to brown (and is free yellow to green).
- [x] Create the map
- [x] Locations E3, H6, I5, I9, and J10 are locked until Green (phase 3)
- [x] There are no forced connections like in 1867.
- [x] I'll mention it here but 1861 has two fewer #15 tiles and no #70 tiles in its tile set nor #120, #122, #124
### Grid market
- [x] Implement 1867 grid market

- [x] Fix minor max price behavior
- [x] Fix float pricing
- [x] There are specific value locations where companies may start. This is important for majors formed by converting, where the stock value stays the same but the token placement changes.
- [x] A sold out company's token that is at the top row of the market will move right one column and down one row at the end of the SR.

### Config
- [x] Majors
- [x] Minors
- [x] Check if the right behavior is done on the clash of symboled between 'Moskow, Kiev & Voronezh Railway' & 'Moskow-Kursk Railway'
- [x] Nationals
- [x] Privates
### General OR
- [x] Route bonus for Moscow & Ekaterinburg
### Game phases
- [x] 6 causes gray not brown
### Train supply
- [x] The base game has only two 5+5Es and no 2+2s, but I've never heard of anyone who didn't play with the two 2+2 variant.
There are unlimited 8Ts

Misc
- [x] Do the two Moscow privates stack?
- [x] Correct Moscow spelling after guidance from Josh
- [x] Check Kharkiv tile upgrades and labelling

Post-Alpha bug list
These are things that don't stop it going to alpha
- [ ] Fix stock market formatting
- [ ] Upgrade costs on Kiev tile overlaps the 'K'

**Comment by OedipussyRex** [comment]
Just my bit to (hopefully) help

National Railway:
* The token in St. Petersburg is placed when the RSR first operates, if one does not already exist. Until then the spot is open.
* When Moscow upgrades to silver, immediately place a token there if one does not already exist in Moscow (operates like Montreal). No more than six RSR tokens can be placed outside of St. Pete and Moscow.
* All assets from nationalized companies go into the RSR. Loans are not assets.
* Privates owned by the RSR pay their income to the RSR. Note: When privates are nationalized at the start of phase 6, the RSR is not paid face value for the privates that had already been nationalized.
* RSR has no stock value and always operates last in an OR. This is still part of the OR.
* Must purchase a train when it first operates, taking as many loans as necessary, no limit.
* The RSR lays no track or tokens, running only on existing track, but follows the standard rules for routes, running for the maximum earnings.
* The RSR always withholds, pays off as many loans as possible, and always purchases the cheapest available train if it is able, Bank or Pool/Discard, with no train limit.
* The A-A Games rules don't address who is responsible for determining the RSR's runs. GTG rules states it's the player with priority in the coming Stock Round.

End Game:
* If the first 8T is purchased in the first OR of the set, complete the current OR then run two more ORs with no stock round
* If the first 8T is purchased in the second OR of the set, finish the set, do a Stock Round, then run three more ORs
* Again, the RSR operates last in the OR, which is important if it purchases the first 8T. 

Nationalization:
* Technically, it's moves one column left (or row down, if leftmost) for nationalizing and one column left(/down) instead of two for each outstanding loan

Map:
* Locations E3, H6, I5, I9, and J10 are locked until Green (phase 3)
* There are no forced connections like in 1867.
* I'll mention it here but 1861 has two fewer #15 tiles and no #70 tiles in its tile set

Grid Market:
* 1867 was designed with the flat market, so a grid would be a variant
* There are specific value locations where companies may start. This is important for majors formed by converting, where the stock value stays the same but the token placement changes.
* A sold out company's token that is at the top row of the market will move right one column and down one row at the end of the SR.

General OR:
* A run that includes Ekaterinburg and Moscow does not receive a bonus. With such runs, Ekaterinburg is worth 80 instead of 40. It's this conceptual difference that caused problems with doublers and Timmons.

Game Phases:
* In 1861, the 6Ts are silver, not brown, so the silver upgrades for Moscow, St. Petersburg, and Kharkov(?) (The Kh tile) are available in phase 6.
* This also affects off-board location revenues.
* The base game has only two 5+5Es and no 2+2s, but I've never heard of anyone who didn't play with the two 2+2 variant.
* There are unlimited 8Ts

**Comment by jenf** [comment]
Thanks,. good to know i've not missed anything. It might be a while till it starts development.

**Comment by OedipussyRex** [comment]
General OR:

A ~~run~~ route that includes Ekaterinburg and Moscow does not receive a bonus. With such ~~runs~~ routes, Ekaterinburg is worth 80 instead of 40. It's this conceptual difference that caused problems with doublers and Timmons.

Oops. Words have meanings.

**Comment by ianwilson156** [comment]
Great to hear you're thinking of doing 1861!
Here are the rule differences from 1861 to 1867:
[1867 Rules v1.0.pdf](https://github.com/tobymao/18xx/files/5850988/1867.Rules.v1.0.pdf)
Although they're the wrong way around (61 -> 67), they should give you a full list of things to think about.

Ideally, 1861 should use the grid market - but if you like you could start with the linear market from 1867 to reduce the workload.

I always play a variant with unlimited 5+5E and 2+2 trains. It's rare you need more than two 5+5E's, but quite frequently more than two 2+2's are bought.

The privates are different (obviously). Note that two give a bonus to Moscow: this is cumulative, so a company with both (typically the RSR) gets a +20 bonus for each train running to Moscow.

Another note: the Kiev hex costs to upgrade from green to brown (and is free yellow to green).
Also, no train upgrades allowed.

Good luck! Ian D

**Comment by OedipussyRex** [comment]
"Another note: the Kiev hex costs to upgrade from green to brown (and is free yellow to green)."
The Budapest of Ukraine.

**Comment by jenf** [comment]
When the stock market changes are ready I may add the optional rule to 1867 to allow earlier testing of the 2d stock market

**Comment by jenf** [comment]
@ianwilson156 can the RSR token spot on E1 be used by other corps?

**Comment by ianwilson156** [comment]
Aah, the RSR in St Pete... if only I'd made this rule simpler! 
Up until Phase 4, the spot in St Petersburg is reserved (just like every other printed spot, in fact).
At the first 4T, the RSR may get the SPW token. If it does. the other slot becomes free; if it doesn't, it stays reserved and the RSR places a token there when it first runs. The net effect is to guarantee a token in StP for the RSR - it was the capital of Russia.
(In 1867, I decided to simplify matters and just have a CN token in Toronto from the start.)

**Comment by jenf** [comment]
@ianwilson156 FYI, due to each corporation needing to have a unique id
Moscow-Kursk Railway is labelled as 'MKu' and Moscow & Kazan Railway is labelled as 'MK'
Let me know if you'd prefer an alternative.

**Comment by ianwilson156** [comment]
That's ok, but it is more usual to refer to the Moscow-Kursk as the M-K (MK for Moscow & Kazan is normal).

**Comment by jenf** [comment]
M-K should work.
