### ISSUE TITLE
[1867] Suggestion: Don't show Major Companies in SR In Phase 3

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#3259]
The Major Companies can only be start during the Merger Round in phase 3, not during the Stock Round. There is no need to display them in the SR in this phase. That just clutters the page with eight unnecessary and unusable charters.

**Comment by bridger15** [comment]
I disagree.  Learning 1867 was much more cumbersome than any of the others I've learned on the site (17, Ches, 46, 89) because when the game starts I can't see ANY charters.  Being able to see the charters is quite helpful, because it gives me a lot of information about the rules of the game.  For example: If the charter lists a specific hex for the first token, I know that the company in question has a specific starting city.  I can also check how many tokens each charter starts with.  I can also see how much it takes to float the company, and if it has any special ability.

When I started an 1867 game and I went looking for these answers on the charters, none of them were listed under the Bank in the entities screen and this made it harder to learn.

I can't see how having all companies listed under the bank makes it cluttered at all.

**Comment by OedipussyRex** [comment]
"I can't see how having all companies listed under the bank makes it cluttered at all."
1) That's not what this request is about. That is a separate issue requiring a separate request. This is about the Game tab during the Stock Round in Phase 3.
2) Please notice that a list of charters isn't provided for 1817, either. Probably because the companies are templates, indistinguishable from each other in any meaningful way. They could be name Minor A, Minor B, ... Minor J, Green Minor 1, ... Green Minor 6, Puppy, Kitten, Foal, Lamb, Chick, Gosling, Calf, and Kid -- or even Yellow Minor x10, Green Minor x6, and Major x8 -- and they would convey just as much information.

**Comment by bridger15** [comment]
Understood, sorry for the confusion :)

**Comment by OedipussyRex** [comment]
Fun fact: Back in the before times when we could play in person, when playing 1861/67 (we had the '67 expansion, not the full game) we just called the Majors by their colors: "It's Blacks turn," "Yellow's next," "Your move, Purple." There being two greens close in shade, when one was started the other would be the last to start, if at all.

Doesn't pertain to anything. Just thought I'd share.

**Comment by OedipussyRex** [comment]
I should probably state that I mean not displaying any _unstarted_ Major Companies during the Stock Round when in phase 3, when Majors cannot be started directly. Of course, you should display Majors that have been started in the Merger Round.

**Comment by jenf** [comment]
@OedipussyRex as a compromise, during Phase 3 i could place them after the minors, would this be okay for you?

**Comment by OedipussyRex** [comment]
_There's no need for argument
There's no argument at all_

It was merely a suggestion and I have no power here, so there really isn't a compromise to be had. But having all un-started  minors,  whether yellow or green, together will help. Especially if the design makes my suggestion a pain to implement.


_And if you never hear from him
That just means he didn't call
Or vice versa
That depends on wherever you're at
And if you never hear from me
That just means I would rather not._

_Hit it._

_Oh oh, Domino
Roll me over, Romeo
I said, oh oh Domino
Roll me over Romeo
There you go
I said oh oh Domino
I said oh oh Domino_
-"Domino" by Van Morrison
