### ISSUE TITLE
[18Chess. OtR] Private Ability button not appearing

### ISSUE THREAD

**Issue by skizelo** [tobymao/18xx#3265]
In gameID 20312, B&O was unable to place the token that comes w/ the Chesapeake & Ohio Canal tile lay. After asking in the chat, I was told there should be a button for that private in the Abilities scroll, but there is only a button for the B&O's other Private, the Baltimore and Susquehana Railroad.
Attached images show: the start of the turn, where the tile lay is permitted; after laying the tile and clicking on the token slot, where only an upgrade is offered; and after ending the track phase, and laying a token is not permitted.
![otrbug1](https://user-images.githubusercontent.com/77389765/104448123-ac598200-5594-11eb-94db-18a5ea5b4ca2.png)
![otrbug2](https://user-images.githubusercontent.com/77389765/104448129-ad8aaf00-5594-11eb-84a3-b1158ebb8fe2.png)
![otrbug3](https://user-images.githubusercontent.com/77389765/104448133-aebbdc00-5594-11eb-892a-b69a0086eaf6.png)

**Comment by jenf** [comment]
@michaeljb i'm seeing similar

**Comment by michaeljb** [comment]
Good news / bad news--the recent ability timing changes didn't change how teleport works, but teleport was already kind of broken.

Anyway C&OC's token must be placed during the token step, not during the tile lay step. Since B&S may only be used during the tile lay step, the turn doesn't immediately move to the token step after you lay a tile in Berlin (this part is new behavior).

Once in the token step, Berlin is not highlighted, but you can still click there and token there (this is not new behavior). Here's the JSON for a hotseat game where I did just that - https://gist.githubusercontent.com/michaeljb/553a1974b27b15407212dab721c3e8e9/raw/f624ec511e7f6401f12d2074beabb0ebdeffc5b8/3265.json

Closing as dup of #1520
