### ISSUE TITLE
[1846 2 player] MS operation issue

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#3362]
I experienced a minor bug in our game last night (1846 2-p variant, game #23200): 

When the MS independent operated, it often wouldn’t let me place track right away (all hexes were grayed out). I either had to pass then undo, hit refresh, or once even waiting a longer than expected period of time (waiting ~45 seconds for the placement options to appear).

The game is complete and I can’t figure how to link to it. It was early in the game, and the chat mentions the issue.

**Comment by benjaminxscott** [comment]
Looks like the actionID is [this one](https://18xx.games/game/23200?action=25)

I wasn't able to repro this, it presented both legal hexes to build, and building Port Huron as in your game seemed to work using [game data at the above action](https://gist.github.com/benjaminxscott/66587cea6db5c46213618e6808cd7fd9)

Notably Huron costs 60 to build, so if you built that first it won't let you build another tile, since MS has no money left

**Comment by tobymao** [comment]
closed because it can’t be reproed
