### ISSUE TITLE
Planning mode

### ISSUE THREAD

**Issue by snoonan-wp** [tobymao/18xx#3573]
**What's your idea?**
- I want to plan the next few moves (or just a few companies nearly in a row).  I want to disable syncing and just do the turns, then release them all at once (or at least what is currently valid).

Let us know your proposed changes.
This is almost like visitor mode, just let me do planning with the game tools, then I can decide what I like and commit just those bits.

**Did you join the Slack?**
No

**Comment by tobymao** [comment]
premoves sounds pretty hard to do, however, you can already take notes in the tools tab.

**Comment by dfannius** [comment]
I usually make my turn in hotseat mode, then enter it by hand in the actual game. If it were possible to copy all actions from a hotseat game over to a real game (say, until there was an exception), that would be a cool feature.

**Comment by snoonan-wp** [comment]
> premoves sounds pretty hard to do, however, you can already take notes in the tools tab.

But you have the tools to help lay track and figure routes, this is mostly queuing the commands to go out, instead of doing so instantly. (I say not knowing the codebase). Your visitor modes does this.

**Comment by tobymao** [comment]
there is no queuing, the visitor mode creates a clone of the game and all actions are fired off to the new game

**Comment by jenf** [comment]
Closing, already effectively available in hotseat, would be very complex to do otherwise

**Comment by dfannius** [comment]
> already effectively available in hotseat

I think this is asking for something more than hotseat mode. I would love to be able to make my moves in hotseat mode, then push a button to publish them to the actual game. (Maybe this is too hard, but it's something that would be useful and isn't available yet.)

**Comment by scottredracecar** [comment]
I see how this would be useful.

When I play F2F, I can go into "planning mode" during my turn and
easily revert my moves by keeping stacks of money separate. I can do that
here with undos unless I trigger someone else's action and then they get a
notification and there may be some awkwardness if I want to change my move.

So instead, I might prefer to clone the game, make my moves, confirm it is
good, then make those moves "for real" in the real game (I have done this
sometimes in an async game). But that last step is kind of annoying to redo
the moves so it would be more convenient if I can just push a button to
push my move to the real game.

However, this sounds complicated, maybe someone has a better way to
implement this. But...

Another way to think about it would be a "planning mode" where I enter
planning mode, make my moves (not shown to other players as I make them),
then when I am satisfied, push the whole sequence of moves to the server.
This also seems complicated to me because I don't know much about the
client/server architecture, but maybe the idea can help someone else think
of a way to do it.

**Comment by dfannius** [comment]
> So instead, I might prefer to clone the game, make my moves, confirm it is
good, then make those moves "for real" in the real game (I have done this
sometimes in an async game).

Yeah, I do this pretty much every turn in async games. But I'm often an outlier, and I probably am here too.
