### ISSUE TITLE
Remove share counts and use percentage everywhere

### ISSUE THREAD

**Issue by tobymao** [tobymao/18xx#3621]
Share counts are confusing, I'd rather just have percentages. I think corporation symbols should be used only as opposed to the names.

From a list of JCL's feedback

Other beefs: 
- Lose the:
    - Currency symbols.
    - Share %ages instead of counts (which you do in some places and not others)
    - Last run value.
    - Value and liquidity for players.
    - And their repeats on the spreadsheet.
    - Legend on the market (players should know already).
    - %age left to float (the players should already know).
    - the company names (use symbols everywhere).
All those gone, everywhere, gone.
- Colour the  trains (I don't care what their definition is, I care where they are in the phasing, which is pretty much the only thing I ever care about for a train)
- Get rid of the row of tokens.  Just one with a count remaining and price for current.
- No, I don't care what the coords of the tokens are.  Ever.  And if I did the map would tell me.
- I've already whined on the mobile optimisations that prevent simpler/smaller interfaces (eg hover).
- Alternating between labels below and above values and then mixing with titles to the left is bad.  Pick.
- Not everything needs a label.
- And an odd one: surface current game phase (colour).

**Comment by dfannius** [comment]
I disagree with most of jcl's beefs (unsurprising, given that we've spent a while iterating to get to the point that we're at). So I'd want a chance to defend anything on that "lose the" list before a decision was made to actually lose them.

I do think that train colors would be nice, though. I especially miss them in 1846.

**Comment by tobymao** [comment]
agreed

**Comment by chrispday** [comment]
The only 1 I agree with is surfacing the current game phase.

The rest is typical 18xx gate-keeping, that without new players would be absolutely lost.

**Comment by tysen** [comment]
I think getting rid of the currency symbols might be good. That's mostly noise and f2f I (very close to) never say e.g. 'yen' instead of saying 'dollars', 'bucks', 'smackers', 'bones', 'clams' or omitting the currency signifier entirely. Could be a user setting.

Share count has a different use than percentage ownership (which mostly matches where you see one or the other in the UI). Mostly share count is useful in aggregate to compare revenue/growth potential (say, in a set of ORs) whereas percentage ownership is more valuable when looking at a particular corp.

**Comment by perwestling** [comment]
Share count is kind of a problem in games with unusual share sizes. Maybe it should show 3 10%, 1 20%, 1 5% instead of 5.5?

When it comes to currency I do enjoy it as it gives some flavor. Now I know that is a personal choice. 

When it comes to "player should know this" I definitely do not agree. I think it would be difficult to play some titles, that has different floating percentages in different corporations. But then JCL thinks 1817 is a good first 18xx title while I am more for 18MS so we seldom agree....

**Comment by perwestling** [comment]
I am even going the other way - I want more information added....  Like having a legend on the map to show game specific information. (That would be very nice in 18SJ.) Ok, "players should know this" but I think that it can enhance the player experience.

**Comment by dfannius** [comment]
> I think getting rid of the currency symbols might be good. That's mostly noise and f2f I (very close to) never say e.g. 'yen' instead of saying 'dollars', 'bucks', 'smackers', 'bones', 'clams' or omitting the currency signifier entirely. Could be a user setting.

I think having a currency symbol of some sort is important (maybe because I'm a static-typing coder). There are a lot of numbers on a typical tab, and I think it adds a lot of clarity to call out which ones are currency vs counts of things vs percentages of things. (I don't really care about the symbol changing between titles, but if we are using a currency symbol, it would seem a little silly, and US-centric, to use $ for every game no matter where it is set.)

**Comment by perwestling** [comment]
I think it might be a good idea to split the list of enhancements to separate ones. In some cases enhancements can maybe be grouped but in general it is better to keep them separate in case we are going to discuss them.

**Comment by OedipussyRex** [comment]
Hey, and while we're at it, why bother with how many shares you can purchase at a par price price? The player should know.
Or how much money the player has? The player should know.
Or what their payout was? The player should know.

/sarcasm

A few good points, though.

**Comment by tobymao** [comment]
The point of this ticket is mainly just to spark of discussion from a drastically different point of view.

**Comment by benjaminxscott** [comment]
>  I think corporation symbols should be used only as opposed to the names.

Is this for the corp card? 
(i.e. "Pennsylvania RR" -> PRR)

(was this particular item toby's ask or JC's ask, it's not clear to me whether this issue is all JC's asks or if some of them are toby's preference)

**Comment by OedipussyRex** [comment]
> The point of this ticket is mainly just to spark of discussion from a drastically different point of view.

Point taken. My sarcasm was to point out that much of what JCL wants to eliminate is information that has been automated so the player doesn't have to look in multiple places and/or calculate to know it. 

Why bother with market/par prices on the company charter in the stock round when that information can be found in the Market tab? Because it makes the game easier and faster. At a glance I can know an aspect of the game-state without having to calculate it. And at a glance I can know how many more shares are required to float a company. 

JCL apparently doesn't use a run tracker, as evidenced by his desire to get rid of the last run value. Granted past performance doesn't guarantee future results, but almost every 18xx game produced in the last 30 years provides one. Because it's useful. 

Liquidity is good to know when your trains are about to rust; I don't have to figure out which shares I will be able to sell, how much I'll be able to get from them, etc. The info is there. 

And depending on how well I know a map, token coordinates are as good as city names to me. In fact, in '67 I know the coordinates better than the city names.

There's more, but here's something I agree with: visual representation of the current color/phase.

**Comment by tobymao** [comment]
closing for now, it's in history now if we vere want to look back
