### ISSUE TITLE
Suggestion:  Please create a setting to force email notifications even when a browser window/tab is open

### ISSUE THREAD

**Issue by bentmeeple** [tobymao/18xx#3755]
I frequently walk away from my computer, sometimes for hours at a time.  I leave the browser on with all of my tabs ready for when I return.  This means I frequently don't get notified when it is my turn.  I realize some users don't want to get extra emails when they are actively interacting with the site, so the default behavior is the right choice.  But I would like to request the ability to choose as a setting to have the emails sent even when I have a browser window open on the game.

**Comment by bridger15** [comment]
Yes please!  Every time I introduce someone to the site for async play, I have to do this convoluted explanation that the async play ONLY WORKS if you always close your tabs after your turn.  Even then we still have people who don't realize it's their turn because they left the tab open at work or on their laptp or just in a minimized window and didn't realize it :\

**Comment by tobymao** [comment]
closed in favor webhooks
