### ISSUE TITLE
18Ireland implementation map

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#3780]
https://www.dropbox.com/s/0rrgo8i5nrs8mts/18Ireland%20Rules%20R2.pdf?dl=0

Setup
- [x] Initial config
- [x] Set aside Dublin & Kingstown Railway
- [x] Randomize order of other corps
- [x] Remove one other, including tokens reservations
- [x] 5 out of the private companies are kept, rest removed
- [x] End game

Initial Stock Round:
- [x] Mostly 1830
- [x] But if all players pass the ISR is over rather than a discount.
- [x] Unless no privates are bought, in which case it restarts

Stock Round
- [x] 5 shares: Very similar to 1861/67 but with the limitation that the corps come out in random fixed order
- [x] 10 shares: Identical to 1861
- [x] 60% minor, 70% major

OR
- [x] Issue or redeem one share
- [x] Lay track rule from 1861
- [x] Entirely-Narrow gauge tiles are without terrain costs (only need to check yellow)
- [x] Track types must match (narrow to narrow, broad to broad)
- [x] Connection rules for broad-gauge and narrow-gauge
- [x] Track: Narrow gauge only tiles can lay as long as the route to a token only goes broad -> narrow and doesn't then include broad again.
- [x] Track: Broad gauge (or Narrow/broad mix) only includes broad gauge connectivity
- [x] Track: Tokened out cities, do not block narrow gauge being laid.
- [x] Token: is broad gauge only
- [x] Track: Fix permissive-checks on upgrade
- [x] Route: broad gauge connectivity only
- [x] Narrow-gauge payout bonus (tiles connected solely via narrow gauge to a visited hex pay out bonuses)
- [x] Full/half pay with double jumps
- [x] Hex train (n+1 hexes)
- [x] Train trade-in phase locked (similar to 1867, but face value exchange)
- [x] EMR: Can buy trains from discard or depot
- [x] Bankrupcy: Closing corps @ !£0 pays players current valid of stock
- [x] Company closes at bottom of stock market
- [x] Train downgrades on obsolence.
- [x] Check track upgrades on labelled tiles (DUB doesn't work)

Merger
- [x] Player order from PD
- [x] 5 shares to 10 shares
- [x] Merger must be legal
- [x] Connectivity is broad-gauge only
- [x] Vote goes from the initiator round
- [x] Vote as a block and cannot abstain
- [x] New stock price
- [x] Bankpool votes depending on situation (can be done immediately) Charter shares do not vote
- [x] Check abilities get acquired

Privates
- [x] P2/P5 - probably special code
- [x] P3 - similar to 1817
- [x] P4/P7 - similar to 1846?, might impact merger code
- [x] P6 - similar to 1889
- [x] P8 - might be complex
- [x] P9 - bypass the second lay rule, custom code
- [x] P10 - lay offboard, could be complex depending on what to do about the tile at G-1
- [x] P11 - variation of initial corp with par. needs to buy a 2 train immediately

Smaller issues - can be fixed as alpha issues
- Fix render of IR7 & IR8 tiles
- [x] Correct colors used for corps
- How to Auto-pass in merger?
- Simplify display of trains in the bank pool (since there'll be a lot)

Bugs to fix before alpha
- [x] DKR starts with incorrect capital
- [x] DKR doesn't log the train purchase
- [x] Entities is in the wrong order
- [x] First minor isn't 'exported' per 5.8
- [x] I9 not being upgradable
- [x] Irish Mail cannot be connected (should've allowed IR39)
- [x] Merger failing

Rough Plan
- [x] Initial config using 1849 as base
- [x] Add corps & stock market
- [x] Sort starting corporations
- [x] Implement first pass on Merger
- [x] Add map and tiles and separate from 1849
- [x] Setup
- [x] Full Stock round
- [x] Full OR except gauge-ness
- [x] Gauge-ness rules
- [x] Add privates
- [x] Initial auction
- [x] Testing especially around gauge-ness rules

**Comment by benjaminxscott** [comment]
Probably the most exciting mechanic and most custom logic is mergers:

- after phase 4 breaks, add a special merger round after each set of ORs

1. player with priority may propose a merger of two or three 5-share companies, or pass
(players may pass and then later propose a merger in that round)
(this player must own at least one share of any one of these companies)
(this player does not have to be president of any of them to propose)
(each set of companies can only be proposed once per merger round)
(there must be at least one unstarted 10-share company to be the resulting merged company)
(the resulting 10-share company must not have any illegal tokens, e.g. more than one on a tile)
(it must be possible to replace outstanding certificates of the 5-share companies with 10-share certificates, e.g. no more than 10 certificates may be in player hands or the bank pool)
(it must be possible for resulting 10-share certificates to be legally held by players and the bank pool (70% max for a player and 50% max in pool)
1. clockwise, each player with at least one share must vote "for/against" the merger. 
(Shares are voted as a bloc, and not split e.g. "three shares for merger")
(Shares in the bank vote "for" if the resulting share price is higher than the current price, "against" if resulting price is lower, and "abstain" otherwise)
(IPO shares do not vote)
1.  If a plurality of votes are 'for' the merger, a 10-share company is formed with the tokens and assets of the 5-share companies
(each 20% share of the 5-share companies held by players or bank pool is replaced with a 10% share of the 10-share company)
(Its resulting market price is the intersection "left" and "up" of the highest row and leftmost column of the 5-share company market prices)
(the president's cert moves to the player who holds the most shares of the resulting company, with ties broken starting with the player who performed the merger, then moving clockwise)
(IPO shares of the 5-share companies are discarded w/o compensation)
(any un-exchanged shares of the resulting 10-share company are placed in its IPO)
(excess trains are discarded to the pool w/o compensation)
1. next player clockwise repeats from (1), ending the merger round when all players pass in turn

**Comment by thebamaman** [comment]
> * 5 out of the private companies are kept, rest removed

P1 (DAR) and P11 (DKR) are always in, only 3 are really randomized

> * Full/half pay with double jumps

No half-pays, only full or withhold
Must payout at least stock price to move right, only 5-shares can double jump

> * EMR

if treasury has enough to buy an obsolescent train in market, no EMR allowed
