### ISSUE TITLE
1849 Messina Earthquake Handling

### ISSUE THREAD

**Issue by biddu6566** [tobymao/18xx#3790]
https://18xx.games/game/25249

Issue: AFG needs to buy a train and only has one token in Messina. During emergency fund raising it has to buy the 12H, which causes the earthquake and AFG should close. The game should allow buying the 12H and then close. Instead it does not allow the train buy and keeps kicking the action back to train buy step.

**Comment by crericha** [comment]
@tysen, this bug occurs because `@game.phase.buying_train!(entity, train)` happens before `@game.buy_train(entity, train, price` in `Step::Train::buy_train_action`. The former triggers the event and closes the corporation before the train is purchased.

I'm not sure if there is a reason behind that order. Someone will need to look into that.

**Comment by czlam** [comment]
Similar situation encountered in this game: https://18xx.games/game/26434

**Comment by czlam** [comment]
Happened to me in two games in a row :(
https://18xx.games/game/27169

**Comment by dfannius** [comment]
Naïvely flipping the order of the two statements @crericha identified causes lots of test failures, as expected. So the solution isn't that simple.

**Comment by dfannius** [comment]
The original game in this issue has been pinned, but I created a new game that demonstrates the issue: https://gist.github.com/dfannius/8642c6ce228d1536366abb24d171cdd4

**Comment by crericha** [comment]
Confirmed the bug goes away if the train is bought before the event triggers.

I am able to get all the tests to pass too. Going to run on the full db once I have access to a newer version of it.
