### ISSUE TITLE
1849: Bankruptcy doesn't always give choice to leave or $500 when it should

### ISSUE THREAD

**Issue by Jay-Davis** [tobymao/18xx#3899]
In rule 10.7.B it reads "... if the president has no stock left
they can either leave the game (finishing with L. 0) or take
a L. 500 loan from the bank."

It appears the implementation is looking at the cert count and not just "stock", so if the player has no stock, but has one or more privates, it neglects to give the player the leave/$500 choice. It does work properly if the player has no privates and no stock. I've attached a simple hotseat scenario where this just occurred.

I assume this bug too will also affect 1849: Kingdom of the two Sicilies.

I received my physical copy of 1849 today, so am really reading the rules and it occurred to me that these things unique to 1848 (at least as far) as I know are likely to be problem areas, so I checked a few,

Here is the hotseat game:
https://gist.github.com/benjaminxscott/98754e99a28b00562de1f537d1b2495e

**Comment by Maxwell-Frank** [comment]
I wonder if this rule is intentional, or just unclear.  This[ non-authoritative BGG thread ](https://boardgamegeek.com/thread/1840342/player-bankrupcy) concluded that you cannot take a loan if you have any positive assets, which I'm inclined to agree with. I think the situation you concocted is actually quite strong for the player who could take a loan in your scenario.

**Comment by tysen** [comment]
Private companies count as certs so having any prevents you from taking a loan.

**Comment by dfannius** [comment]
> Private companies count as certs so having any prevents you from taking a loan.

Right, but the AAG rules say "stock", not "certs". Have we decided that the rule as written is misworded and should say "certs"? (I'm fine with that.)

**Comment by Jay-Davis** [comment]
That thread per-dates the AAG rules and the AAG rules specifically say they cleaned up the emergency fund raising section. The new rule above specifically says "stock".

I found a copy of the old rules and it says "In case of bankruptcy, the unlucky President's properties are likely to be reduced to zero. In this case he / she can either leave the game (finishing with L. 0) or take a L. 500 loan from the Bank." I would agree under the old rules that anything would count, but not under the current rules.

Having said that, it would be good to get a clarification of the intent from the person who wrote it since there may be a specific reason for it to be one way or the other.

**Comment by tysen** [comment]
This argument rests on an implicit claim that "stock" does not include private companies, which I don't think is founded. "Cleaning up" the rules doesn't mean changing them - where the old rules were clear (as in the excerpt you provided), we should expect the new rules to match.

@scottredracecar

**Comment by dfannius** [comment]
I would never have guessed that "stock" might include privates! I look forward to the clarification.

**Comment by scottredracecar** [comment]
Doing a little reasearch, give me a week.

**Comment by scottredracecar** [comment]
I pinged Vellani today and got a response. His opinion is that the private companies should not count in the determination of whether a player may take a loan. 

His justification is "I don't like to let anyone be expelled from the game because of the possession of a mere PC" [private company]

So I guess that means this open issue is a "bug" if it is desired to follow the designer's intention. Chris Lawson would be another reference point, but I will leave it here so as to not sow further complication.

Perhaps by making this change, it creates a new dominant strategy:
- Buy a big private company
- Self-bankrupt to get the loan/restart (and keep the private)
- Buy in big private company
- ...
- Easy win

If that is found to be the case, then I would recommend to reconsider, but I think we would have to try the revised implementation to know that. I suspect this will not be such a problem, but it would be worth looking out for if the implementation is changed.

**Comment by Jay-Davis** [comment]
I thought about that strategy, but there really isn't a big private in this game, people would have to let someone buy multiple privates to try to make this work, Even if they did, it would have to be a 4 or 5 player game to even possibly be an advantage, and even then I'm not sure it really is a good strategy.

**Comment by jstern78** [comment]
If you need an actual game reference, you can see Game #38674.

The described situation came up exactly. I had two large privates in a 4p game. Couldn't afford a train in OR1 and was denied a loan despite having no corporate shares. I don't know what the rule is supposed to be. I assumed that stock meant shares and think I would have been in a strong position with the loan.

**Comment by scottredracecar** [comment]
Yes, it appears you have constructed a very good attempt at making the potentially "dominant strategy" I mention above work.

Link with current action for posterity:
https://18xx.games/game/38674?action=94

I don't think anyone is working on this right now--so tough luck I guess. 🙂
