### ISSUE TITLE
18CZ display corporation sizes and/or availability on map

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#3905]
It would be nice if, at the start of SR1, you could see at a glance on the map which five small corporations are available. This could be accomplished by indicating corporation size, or simply highlighting the currently available corporations.

**Comment by benjaminxscott** [comment]
Could you expand on this usecase ?

Would this be something like "I would like to tell which companies are small vs medium" ?
(since it shows all the token reservations, but only small companies are start-able in sr1)

**Comment by ChrisTheCat** [comment]
In SR1, I see the charters that are available - the five small corporations. I then of course look at the map to see where they are. There are 15 reserved token spaces on 15 cities. They all look the same.

In the published game, I can glance at the map and see at a glance "this city has a diamond shape, it's small; this one has a shield shape, it's medium; the large cities start in the special hexes on the edge of the map." We also generally put the available tokens on the map, so you can see at a glance "the five starting locations in SR1."

With all the tokens undifferentiated in 18xx.games, it's harder to tell what's available now vs. what will be available later.

**Comment by benjaminxscott** [comment]
Ah I can see that being helpful

Within the current system, the token reservations are just text in the city slot and tokens are SVGs that get rendered

If the "reservation tokens" were svgs, they could have the properties of a "grayed out" version of the token logo shape, which presumably would cover this case
(this would be a bigger change to the system, fwiw)

Or, perhaps an indicator on the home token reservation indicating that they're not yet available to start?
(Thinking generically, since this is similar in 60 and Ireland as examples I'm aware of where there are a set of start-able companies)

**Comment by Zwergenpunk** [comment]
> Or, perhaps an indicator on the home token reservation indicating that they're not yet available to start?
(Thinking generically, since this is similar in 60 and Ireland as examples I'm aware of where there are a limited subset of start-able companies)

Yeah I think a generic way of displaying not available corporations would be nice.
