### ISSUE TITLE
Can only add city/town to one end of route even if both are possible

### ISSUE THREAD

**Issue by yoyoson** [tobymao/18xx#3915]
**What's your Game ID?**

https://18xx.games/game/23135?action=1373

https://gist.github.com/yoyoson/b7358942dddaa22ccae372bf4d45c6d1

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
### - First Test:
- Undo the red train's route (first 9+5) by clicking to back out of I3, J4, K5 (Ryde Esp < Ryde < St.Helens).  Your map should now look like the screenshot. 
![can_only_route_from_sandown](https://user-images.githubusercontent.com/525244/108023753-4166f500-6ff1-11eb-813d-2e43450b0b92.jpg)

- 
- Now click K5 (St Helens) again, several times. 
- Notice It will only extend the route through J8->K7  (from Sandown), even though on last run it was coming from J6 (Brading).

### - Second Test:
- Now with St Helens out of the route, click on Ryde J4. It should  now be  I5 -> J6 -> J4 (Ashey -> Brading -> Ryde). 
- Now try clicking St Helens again. Still it only allows the route to extend from Sandown, even though other valid routes exist. 

- My expectation is that it would allow routes from Brading and Ryde.  

**Which Browser / Platform?**
- Browser Version = Google Chrome | 88.0.4324.150 (Official Build) (64-bit) (cohort: Stable)

- Platform = Desktop

**Comment by roseundy** [comment]
This is a minor bug at best, you are able to add St Helens just fine. Why does it matter what end of the route it is on?

If you really want St Helens on the other end of the route, remove Sandown first.

**Comment by dfannius** [comment]
A less defensible case of this happened to me in an 1830 game lately. The town I was clicking on was adjacent to both ends of my route, but only one end was legal to extend from (due to a blocking token). The site assumed I was trying to extend from the illegal end rather than the legal end (because it makes that choice arbitrarily before checking for legality). I had to shorten the route by hand and then reëxtend it, as roseundy suggests, which is certainly a workaround but was awkward. In that case, at least, the game should understand what I'm trying to do, since there's no ambiguity.

**Comment by roseundy** [comment]
The latter case (deciding which end of the route to extend by legality) would be very hard to implement. It might be possible to fix the general case by adding another "cycle routes" case to the code.

**Comment by yoyoson** [comment]
> This is a minor bug at best, you are able to add St Helens just fine. Why does it matter what end of the route it is on?
> 
> If you really want St Helens on the other end of the route, remove Sandown first.
> 
> This is not specific to 1860 in any way.
I agree that the behavior is an interface thing and not specific to 1860. Perhaps the template for filing a bug should only request that the 18xx title be included if we are sure it's specific to that 18xx. 

In this case, the NGStL cannot route from Sandown to the 3 Ryde hexes because it would be trying to route through a 2nd tokened-out hex, whereas only one is allowed. This is 1860 specific. The NW portion of Newport was one, and Sandown would be another.

**Comment by yoyoson** [comment]
The 1860 rule, for reference, 

>One (and only one) of the trains run by a company on its operating turn may pass through ONE tokened-out station. Tokened-out stations are large stations which have all their station circles filled by tokens belonging to other companies. Apart from this single tokened-out station, no other tokened-out stations may be travelled through by any train on a company’s turn, although they may be included as the terminus of a train’s run.

Near the top of page 12, https://tesera.ru/images/items/154476/1860.PDF

**Comment by roseundy** [comment]
Yes, I'm quite familiar with the 1860 rules.  The problem is that this is generic issue with how the route selector works for any game. Route legality has never been a part of selecting nodes on the route.

I agree that "cycle routes" could be modified, but as is this is completely playable. Having a node be a candidate for either end of a route is a rare case.

**Comment by dfannius** [comment]
I think this is the same as #2599.

**Comment by dfannius** [comment]
The general issue I mentioned above, where there are connections to the clicked-on city from both ends of the current route and the site picks the illegal one, happens all the time in 1830, since there are a lot of loopy routes in the Boston/New York and Philadelphia area. I'm constantly having to back up one end of my route to ensure that the site can't try to connect from it, then restore it after the new city has been connected to the correct end.

One improvement that might be relatively straightforward to implement is to keep track of which end of the route has been modified most recently, and check that end for connection to the clicked-on city before the other one, instead of always checking the two ends in a fixed order. This isn't a complete panacea but would successfully DWIM most of the time in these situations.
