### ISSUE TITLE
CZ SR/OR chart

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#4065]
Hi!
It would be super helpful to have the OR/SR chart included in the online game.  I think that on the Market page or the bottom of the “game” page would be ideal. I attached an image that can be edited :) 
![image](https://user-images.githubusercontent.com/73318207/108606509-a74bd780-7377-11eb-8a95-0508f244b238.jpg)

**Comment by vints1** [comment]
This enhancement has already been suggested in issue #3909 and is a definitely needed.  There is a text description in the info tab at the moment which tells you if the upcoming OR set is 1, 2, or 3 and how much the privates are currently worth but I never even saw it until someone pointed it out.  It also tells you there are 13 ORs, but with the OR1.1 convention used elsewhere for the game (like in the top row), that's not particularly helpful without doing some of your own conversions.

**Comment by yzemaze** [comment]
duplicate

**Comment by benjaminxscott** [comment]
@vints1 

(for context, I implemented this approach, glad to change it's not set in stone)

Glad to learn more about your comment, paraphrased 
> the current interface shows "13 ORs" but perhaps use OR1.1 convention 

Perhaps refactor to "game ends after OR set 8.3" ?
(the current approach just grabs a variable `total_ors` or something, which is why it's a flat number)

**Comment by vints1** [comment]
@benjaminxscott Since the rest of the site uses OR X.X I think it would make more sense to stick with that convention, although it is useful for a game with a fixed number of ORs to think in terms of the total (which I hadn't until you just put that that idea in my head!).  An alternative would be to display something like you're in OR 4 of 13, I guess, but then you deviate even more from how things are displayed in other games.

**Comment by benjaminxscott** [comment]
See https://github.com/tobymao/18xx/pull/4222
