### ISSUE TITLE
Hot keys affect note taking

### ISSUE THREAD

**Issue by databoy01** [tobymao/18xx#4121]
When leaving notes and using any letters that are the same as tab hot keys say like an S it will open the “Spreadsheet” tab while taking a note. I was trying to type in a note about shares and that happened and also any time I typed E for like Sell, the e in that word would open “Entities”. Thus making Notes useless now. This is in game 1882 ID 27247 and version I see we are on is 272d4360

Thank you

**Comment by databoy01** [comment]
Further comments regarding this issue. I play this on my iPad and haven’t had this issue before. According to user “eludyan” they state on their computer if you do not click on the window they see the issue.  So it might not be everyone having this issue...

**Comment by Auzzy** [comment]
I have seen this same behavior for the few past hours when using my Chromebook. Even when I make sure to click the text area first, typing a hot key activates that hotkey.

**Comment by Eludyan** [comment]
So I noticed that when I hit *enter* the screen hops and my curser leaves the chat box. It is like the screen refreshes when I press enter instead of just sending the chat through.  I hope this makes sense!
I use a newer iPad with external keyboard. I feel like this is a recent change for me.  It happened on occasion before, now it is every time I type something in chat.

**Comment by yzemaze** [comment]
Sorry, I should’ve tested more thoroughly. The regressions you mentioned should be fixed after next deployment.
