### ISSUE TITLE
Improved notation on runs

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#4154]
This request has some relation to issue #2193, but it's a little bigger.
In addition to better train descriptions, integrating this information into the runs would be useful. 

Trains in different games run differently. When running a route it currently says how many stops are included, but it doesn't say how much of the limiting factor has been utilized. 

In some games, dits count towards the stop limit, others not. In games where they don't count, it is still listed as a stop. Some trains run hex-sides, and number of stops doesn't matter, etc. 

My suggestion is to show how much of the limiting factor has been used rather than the generic "stops." It may be useful to have number of stops as a secondary column if that is not the primary limiting factor.

**Comment by dfannius** [comment]
The general code for this has already been implemented, and is specifically used in 1849, where the hex trains now show how many hex edges they've traversed, not how many stops they've visited. (You may have already noticed that the table now says the generic "Used" rather than "Stops".) It would be useful to have a list of games with interesting trains and how their resource usage should be displayed.

**Comment by HerbyMcGee** [comment]
Ah, last game of '49 was pinned as being an old implementation. I didn't know it was fixed.

I don't have a list. The most common quirk is counting dits, or not.
CZ has very strange trains- I haven't read the rules on the trains.

**Comment by scottredracecar** [comment]
The notation works well on most games. I suggest to make specific suggestions for improvements in certain games that are lacking and if there is interest in someone writing special code for it, it may happen. :-)
