### ISSUE TITLE
Leaving browser overnight and loading a game causes the game not to load due to bundle changes

### ISSUE THREAD

**Issue by jenf** [tobymao/18xx#4157]
Last night let a browser running, unslept the laptop and browsed to an 1817 game, there was an exception.

Likely there's a bug with the bundle whereby the old base javascript code is loaded and then the 1817 code is subsequently loaded causing a mismatch.

**Comment by jenf** [comment]
@michaeljb fyi, we need to be able to spot this somehow...

**Comment by michaeljb** [comment]
Maybe when loading a game's bundle file, there could also be a request for the latest version.json and that can be compared with whatever the main bundle thinks is the version? Not sure how best to go about this, I'll try and think about it some this weekend

**Comment by michaeljb** [comment]
So when entering a game by clicking on the card (rather than hitting the game's URL directly), only the game's bundle is requested, the main bundle from the initial page load is still used. Maybe a check could be added for the latest version? That might require building the commit version into the main bundle somehow. If that was built in, then the workflow could be something like this?

* user clicks "Enter game"
* [new step] make new request for assets/version.json, compare with the version in the currently loaded Engine
* [new step] if different, then request new main and deps
* continue with current flow of requesting the game-specific bundle(s)

**Comment by scottredracecar** [comment]
@michaeljb this doesn't seem to be a common problem, okay to close?

**Comment by michaeljb** [comment]
Yeah, seems like it hasn't caused any complaints for a while.
