### ISSUE TITLE
[18CZ] Incorrect route, can run 1 train hitting Praha twice

### ISSUE THREAD

**Issue by adamranderson** [tobymao/18xx#4210]
Can observe the bug at https://18xx.games/game/30268?action=373. Run the 3+3 train from Praha to Praha for 130.

**Comment by benjaminxscott** [comment]
[testcase](https://gist.github.com/benjaminxscott/e90674ef9a3f35d6b329aae33abb1e14/e953262bb175e190ce9155d77e4942e41995b024)

**Comment by michaeljb** [comment]
@Zwergenpunk we just need to make each `city` on the Praha hex part of the `Praha` group. Here's an example in 1846 of using the Chicago group for the Chicago/D6 hex: https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1846/game.rb#L664

This case is a little bit different since the green Praha tile adds two cities, you might need to specify the group for all cities on that tile as well--in the 1846 Chicago case, the groups from the four preprinted yellow cities automatically transfer to the green tile when it is laid.
