### ISSUE TITLE
[1822,1856,1870] Destinations

### ISSUE THREAD

**Issue by Jlamb52** [tobymao/18xx#4255]
**What's your idea?**

A map layer for 22,56,70 and other games would be handy for the showing of destinations. Currently in 22 a blurry SVG of the corparations token is there. While this may be fine as a reminder it is too hard to see clearly on a computer screen for initial planning. A better implementation would be a map layer similiar to showing last routes etc that clearly marks each companys home tile and then draws a straight line across the map to the destination hex. If multiple companies share homes/destinations/destiation and home these could be marked in text

see how rr18xx does it.

**Comment by perwestling** [comment]
Also 18AL could use such an enhancement.

**Comment by daniel-sousa-me** [comment]
I'd like very much to have this.

Iirc each of these games implement destinations in a different ad-hoc way and there's no generic way to have destinations. I think we should consolidate the implementations first, and then find a visual solutions that work for all games.

@perwestling since you know the code better than me, which of these games do you think implements destinations in a cleaner way? Do you have any idea of how a good generalisation could work?

**Comment by perwestling** [comment]
@daniel-sousa-me Sorry, I have not looked into neither of these three titles. I do not know if it can be generalized more than just the display?

**Comment by daniel-sousa-me** [comment]
I just want to consolidate the way that is stored the destination for each corp (and the information that it was reached. I think each games does it in a different way). I'm not looking to generalise the berhaviour, because they're wildly different. Even what it means to reach a destination is different.

But thanks anyway :)
