### ISSUE TITLE
Tiles page is broken

### ISSUE THREAD

**Issue by carlorusso** [tobymao/18xx#4305]
- Opening https://18xx.games/tiles/all return just this json: '{"error":"nil is not a class/module"}'

**Comment by yzemaze** [comment]
@michaeljb
seems to be due to https://github.com/tobymao/18xx/blob/d2361b5ebdc556d803711463645926f38587dbf7/api.rb#L108
title(s) in path work fine, tiles and `all` don’t.

@carlorusso 
Maybe showing tiles of specific titles helps in the meantime: `https://18xx.games/tiles/1830` or even `https://18xx.games/tiles/1830+1846` works fine.

**Comment by michaeljb** [comment]
I can look at the /all page this weekend
