### ISSUE TITLE
Game Log: report stock price and token movement

### ISSUE THREAD

**Issue by tysen** [tobymao/18xx#4308]
https://18xx.games/game/28128?action=163

GT is fully owned and so moves up one space in the market. HBR as well. The log only reports HBR though, I assume because the share price values for the space GT left and the space GT entered are equal.

**Comment by yzemaze** [comment]
> I assume because the share price values for the space GT left and the space GT entered are equal.

Exactly:
https://github.com/tobymao/18xx/blob/68f86a0f08dec9f28c7a4a620c73d4dcada49dd7/lib/engine/game/base.rb#L859-L865

As it’s designed to report stock price _changes_ and not _movements_, it’s not a bug.
Do you think reporting movement and price changes would be worthwhile?

**Comment by dfannius** [comment]
I do.

- It's useful information.
- We call out all other movement on the market.
- The current lack of message is confusing enough that once a month or so someone "erroneously" reports a bug (e.g., "this stock didn't move even though it was sold out").

**Comment by dfannius** [comment]
One proposal is to change the message from "AAA's share price changes from $X to $Y" to "AAA's share price moves [up/down/left/right] from $X to $Y". This also would make it clearer to newer players how market movement works, since right now it's easy for them not to pay attention to up vs right, or down vs left.

It would also be nice to call out ledging.

**Comment by thepackrat** [comment]
I can take this on a general extension to the multijump reporting.
