### ISSUE TITLE
[1822] London Tiles Not Reserved for Owner

### ISSUE THREAD

**Issue by SamForestBH** [tobymao/18xx#4311]
According to rule 5.10.7, "The six hexes around London are reserved for the adjoining companies and cannot have a yellow tile placed on them without the agreement of the director or concession holder of the respective major or minor company." This rule is not respected in game.

**Comment by magnusfalt** [comment]
I need an example where it doesnt respect the rules.

**Comment by SamForestBH** [comment]
https://18xx.games/game/31150
We undid after we realized, but 14 was able to lay a gentle curve into SW London without the consent of GWR president.

**Comment by magnusfalt** [comment]
Ok now i understand, i have made so you cant build a tile except into london. Its highly unlikely i will enforce an agrement ingame where you get a question.

**Comment by SamForestBH** [comment]
Ok! Just to make sure I understand, you think you will be leaving it as is and it will be up to players to enforce that rule?

**Comment by Maxwell-Frank** [comment]
@SamForestBH You are able to lay track **into** London without the owner's permission if it connects London into the pre-existing track network. However, 14 should be able to lay other tiles in that hex that do not connect into London with the GWR owner's permission.  

@magnusfalt Requiring all track lays in hexes surrounding London to connect to the London stations themselves is **not** correct behavior and needs to be changed.

**Comment by Maxwell-Frank** [comment]
@magnusfalt You are allowed to build track that does *not* connect to London with the owner's permission.  Requiring that all track be built into London is not correct behavior.

**Comment by magnusfalt** [comment]
Ok reread the rules and you right. Will changed the issue to a bug.

**Comment by magnusfalt** [comment]
But in SamForestBH case, where 14 lay track into london from a current network is correct behaviour. Dont need an agrement to lay track into london.

**Comment by SamForestBH** [comment]
"The six hexes around London are reserved for the adjoining companies and cannot have a yellow tile placed on them without the agreement of the director or concession holder of the respective major or minor company. If the company has no director or concession holder, then a tile may only be laid if it connects the associated London station into an existing route network."

Unless I am reading an outdated version of the rules? The issue was not due to the fact that the 14 was collocated because the track was laid into a different London exit.

**Comment by Maxwell-Frank** [comment]
You need permission to lay track **into** London if and only if there is a concession holder or president of the associated London company.  If the company does not exist in any form yet, then connecting it into the existing track network is sufficient. Otherwise, permission is always required, even if you're connecting into London.

**Comment by SamForestBH** [comment]
Agreed! In this case, the 14 was laying track into the GWR's home when the GWR existed. This was on the first turn of the GWR's existance, before the GWR ran. (The issue was undone once we realized the mistake).

**Comment by ChrisTheCat** [comment]
> If the company does not exist in any form yet, then connecting it into the existing track network is sufficient. Otherwise, permission is always required, even if you're connecting into London.

This is also true for minor companies that have been eliminated from the game, though it's unlikely that a London minor will go un-purchased.

**Comment by rclyne** [comment]
My understanding from being a play tester of 1822 is that the six hexes around London have a little bit of track printed on the hex.  See [picture](https://cdn.shopify.com/s/files/1/0252/9371/7588/products/1822_Map_grande.png?v=1599166572) to see the board in the AAG version. This track needs to be kept when laying yellow tiles.    I've reread the latest rulebook and I'm not 100% sure if this has been changed.  I've reached out to Simon.

**Comment by KevinR1000** [comment]
The behavior of 18xx.games is clearly inconsistent with the rules as written.  I've run a hotseat game to highlight a clear failing; see attached json of the game (compressed because json not recognized file type here).

Rule 6.1.5 of the AAG printing just delivered (Apr 2021) is:
> 6.1.5  The six unbuilt hexes around London are reserved for the adjoining companies and cannot have a yellow tile placed on them without the agreement of the director or concession holder of the respective company.  If the company that controls such a hex has no director or concession holder, then a tile may only be laid if it connects the associated London station to existing track.  There is no restriction on upgrading these tiles once placed.

In the situation below, the only options that LNWR is given for the Hartford track are tracks connection to the London LNWR station.  Tracks that connect to the Manchester LNWR station but not the London one are _**not permitted**_ by 18xx.games. 

- This isn't a case where 18xx.games is bypassing hard-to-implement (and slow) consent given by another player.
- This isn't even a case where 18xx.games is choosing not to assume consent due to multiple companies owned by the same player.
- This is a case where consent is explicitly being given, because LNWR is trying to build yellow track in front of the LNWR station, and 18xx.games still blocks legal track lays.

Unless rclyne can confirm that the RAW are contrary to designer intent, this seems to be a clear issue of 18xx.games.

<img width="357" alt="Screen Shot 2021-04-24 at 10 00 34 " src="https://user-images.githubusercontent.com/82781561/115963291-4ad67700-a4e4-11eb-9b14-869d230327af.png">

[hs_jjohcobv_1619276145.json.zip](https://github.com/tobymao/18xx/files/6370012/hs_jjohcobv_1619276145.json.zip)

**Comment by KevinR1000** [comment]
That said, I understand the reluctance to create a dialog or confirmation system, where one player's turn is interrupted to wait for explicit confirmation by another player.

I think it would be fair for the 18xx.games assumption to be that a different player would not consent to being blocked.  But I think that 18xx.games should definitely permit a company to block itself and probably permit a player to block themself.

That is, I think it would be fair for 18xx.games to implement 6.1.5 along these lines:
> 6.1.5 The six unbuilt hexes around London are reserved for the adjoining companies and cannot have a yellow tile placed on them without the agreement of the director or concession holder of the respective company. If the company that controls such a hex has no director or concession holder **_or is controlled by another player_**, then a tile may only be laid if it connects the associated London station to existing track. There is no restriction on upgrading these tiles once placed.

Currently, 18xx.games implements this version of 6.1.5:
> 6.1.5 The six unbuilt hexes around London are reserved for the adjoining companies.  A tile may only be laid if it connects the associated London station. There is no restriction on upgrading these tiles once placed.

**Comment by KevinR1000** [comment]
Rule 6.1.5 is currently enforced in the 1822 **_map_**.
https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_1822/map.rb
```
        ['M36'] =>
              'town=revenue:0;stub=edge:0',
```

Fixing this (to implement the rules as written) seems likely to be non-trivial and of little benefit.

I'll try to figure out how to add a bullet to the Implementation section of the wiki to document this.

**Comment by KevinR1000** [comment]
Wiki updated with new Implementation Note:
> Any yellow tile built in the six hexes around London (M36, N37, N39, M40, L39, L37) must connect to the associated London station. Despite rule 6.1.5, a company may not consent to have its station blocked.

https://github.com/tobymao/18xx/wiki/1822

I recommend closing this issue as unresolvable (wontfix?).

**Comment by Maxwell-Frank** [comment]
@KevinR1000 Why is implementing an overly-restrictive ruleset correct here? Wouldn't the rules permissive approach be to allow **all** tile lays outside London, and leave it up to the players to not break the rules?

Intentionally implementing rules that prevent legal gameplay seems incredibly unwise.

**Comment by KevinR1000** [comment]
That is a philosophical question, and far above my pay grade.

Permitting everything and relying on players for enforcement has precedent (inter-player sales of trains or privates).  For privates (at least), a warning pops up requiring the buying player to confirm that the seller agreed.  Maybe something like that could be added (although I don't know how complex that is; I'll look).

My inclination, however, is that this sort of track laying is not obviously transgressive in the way stealing someone's cert/train would be.  That might put a thumb on the scale, suggesting that programmatic enforcement is reasonable (even though it blocks rare but legal moves).

For the time being, we definitely need to document what the code does (strictly enforce part of the rule and ignore part of the rule).  If this can be fixed in a better way in the future, great.

**Comment by KevinR1000** [comment]
(Also note: the rule as written is slightly ambiguous.  If both the 14 and another company are co-located, is it sufficient for only one to consent to a connecting yellow tile?  If the other company is unowned, can the 14 consent to a non-connecting yellow tile?  If the 14 is unowned, in some sense it is at every London station; can a non-connecting yellow tile be played while the 14 is unowned?)

**Comment by ChrisTheCat** [comment]
I'm not convinced that a non-connecting tile is even legal.

**Comment by rclyne** [comment]
I emailed Simon Cutforth and he said:

For 1822, the answer is half and half.  

Any company can lay track that keeps the little spurs.  Only the director of the company, or the concession holder, can permit a piece of track to be laid that ignores the spurs.
In practice, the director is pretty unlikely to want / allow this so the spurs will apply probably 99.99% of the time.
(For the avoidance of doubt: if a company doesn't have a concession holder / director, then the spurs count.)

**Comment by Maxwell-Frank** [comment]
I believe this is even more broken than before, @scottredracecar. It's definitely not rules permissive.  You are currently required to build track into London and not bypass the spurs, even with consent.  

Please correct me if I'm wrong, but this is still a bug that needs fixing.

**Comment by scottredracecar** [comment]
Okay, but this issue is long and hard to track the specific request. I suggest making a new issue that clearly explains what needs to be fixed now and reference this one for background.

**Comment by magnusfalt** [comment]
This is an issue where the amount of work is need to get this to work WAY outweighs the need to do this very specific case correct. Anyway, i wont touch it, but if we have an eager 1822 fan who want to do it, go ahead :)

**Comment by scottredracecar** [comment]
Closing for now. This is documented on the wiki and I added a link to this issue.
