### ISSUE TITLE
1860 variants

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#4391]
I've been playing some 1860 and I'm interested in trying some of the variants proposed in the rules.

I'd like to implement them, but don't want to step on anyone's toes. @roseundy do you have any plans to implement them? Any other comments? Can I go ahead?

- [ ] Simplified Insolvency Revenue
- [ ] Ignoring historical order of companies
- [ ] Selling shares in non-operating companies
- [ ] Re-use of hexes
- [ ] Destinations

**Comment by roseundy** [comment]
No, I don't plan on implementing those options. I would be against the simplified insolvency revenue because 1. we already have an option around insolvency revenue and I don't want to confuse things and 2. the only reason for this option is to make it faster to play in person. I am also against destinations because I feel that would make what is already complicated code even more so.

Is there much demand for these options?

**Comment by roseundy** [comment]
Thinking about this more, I'd prefer to leave it the way it is. The options either have a small effect on play, or are fairly intrusive to the code. The only reason I added any options at all is that I knew people would want to play with the first edition rules.

**Comment by daniel-sousa-me** [comment]
Afaik the demand is: one person xD

It was mostly because I wanted to try the destinations. I'd also like the simplified revenue, because I get annoyed by having to click in all the halts xP

But I understand where you're coming from and I don't consider any of this important at all.
