### ISSUE TITLE
[1860]  Insolvency remains despite the fact company had purchased a train.

### ISSUE THREAD

**Issue by TheNoah2** [tobymao/18xx#4514]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

https://18xx.games/game/31708

- (optional) Provide a link to the specific action that t
https://18xx.games/game/31708?action=491
https://18xx.games/game/31708?action=522

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- Company BHI&R remains insolvent after purchasing 9+5 train.
- later on, despite the fact of having a 9+5 train, it leases a 9+5 train again. Due to a coincidence of having money (being floated again) it purchases a second 9+5 train and becomes solvent.

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome,  89.0.4389.82
![1860](https://user-images.githubusercontent.com/80719059/111219527-ea841980-85b6-11eb-874d-fe9e4f6c8bbb.PNG)

**Comment by roseundy** [comment]
The bug happens when BHI&R is leasing a train and when it withholds, two things happen:
1. It now has enough money to buy a train, AND
2. It's share price drops into the bankruptcy zone.

The bug is that it should **not** have bought a train. It remaining insolvent is fine, since the designer says that bankrupt companies retain the insolvency flag. I need to add a qualifier to the buy_trains step to prevent it from buying a train since the bankrupt company should step operating immediately - and not wait until the end of its operating step.
