### ISSUE TITLE
[1870] Require selling shares above 60% if acquired through brown/green market

### ISSUE THREAD

**Issue by daniel-sousa-me** [tobymao/18xx#4567]
You can assign this to me. I'm just putting it here so that we have a list of "known bugs", because most likely I won't be able to take care of this today.

**Comment by OzLocutus** [comment]
Is there a rule that actually says this? I know rr18xx don't have this implemented. Shares can always be kept over 60% no matter how they were obtained. The compliance sales section of the rule book specifically refers to compliance sales due to the certificate limit. In saying that, rr18xx if I recall correctly stated there is no clear guidance in the rule book. Would be curious to clarify this with the designer.

**Comment by Maxwell-Frank** [comment]
What if you acquired some of your 60%+ shares through price protection and some through green/brown? Do you still have to sell down? Or if you acquired the excess shares through price protection and then it moved into and out of green/brown? 

This is a rules question more than implementation, but might need clarity before implementing.

**Comment by daniel-sousa-me** [comment]
Yes, that is why I'm taking some time to do this right.

Until then rules are permissive.

**Comment by Maxwell-Frank** [comment]
Don't work on this yet. Bill Dixon mentioned on the groups.io that you might always be able to hold >60% in perpetuity if legally acquired. I'll post here if he makes an official ruling.

**Comment by daniel-sousa-me** [comment]
I saw your email ;)

Thanks!

**Comment by daniel-sousa-me** [comment]
Bill Dixon answered:

> Mayfair tried to complicate the rules.
> 
> I have always played that you can keep any shares over 60%, regardless of how you got them.

https://groups.io/g/18xx/message/49377

So I'm closing this and leaving the implementation unchanged.
