### ISSUE TITLE
wrong links on https://github.com/tobymao/18xx/wiki/Harzbahn-1873

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4583]
The links on https://github.com/tobymao/18xx/wiki/Harzbahn-1873 to Map, Tiles and Market go to 1870, not to 1873.

**Comment by yzemaze** [comment]
Wiki links are correct. Redirection to 1870 is just because there’s nothing to show for 1873, yet. This should work, once 1873 is in alpha.

**Comment by roseundy** [comment]
Why is this happening? It's really hard to develop a game when you can't look at its map.

**Comment by scottredracecar** [comment]
Hmm, turns out even prealpha games can link to these resources--so the failure was with the fuzzy search "1873" finding 1870 instead of Harzbahn 1873. Seems like exactly matching the number should rule, but apparently not!

I just changed the wiki links to "Harzbahn" instead and it seems to work now.

**Comment by michaeljb** [comment]
The real underlying issue has a couple parts: 1) 1873's title is "Harzbahn 1873" rather than "1873", and 2) the list of things to match doesn't handle the game class part quite right--it takes `G1873` and and transforms it to `G1873` and `73`, but not just `1873`.

Adding `GAME_ALIASES = ['1873'].freeze` to `G1873::Meta` would work around part 1, but part 2 is wrong and I've got a fix just about ready for it.
