### ISSUE TITLE
[18CZ] After buying a company, button should be "Done (Companies)"

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#4619]
After a company has been purchased, the button says "Skip (Companies)" when it should be "Done (Companies)".

https://18xx.games/game/32143?action=325

**Comment by Zwergenpunk** [comment]
If we are at that granularity of bugs i'm happy :)

**Comment by Zwergenpunk** [comment]
I think that is a bug for all games with a blocking buy_companies at the end.

The step where acted is set to true is the non blocking buy_company step.  But the button shows the blocked buy_company step which is not acted on.

I have no clue how to  fix that in a good way =/

**Comment by crericha** [comment]
I think you can fix the same way the track step works.

>      def pass_description
>        @acted ? 'Done (Track)' : 'Skip (Track)'
>      end

**Comment by Zwergenpunk** [comment]
https://www.github.com/tobymao/18xx/tree/master/lib%2Fengine%2Fstep%2Fbuy_company.rb

In line 39. the code is already there. The problem is that 2 instances of the step. And buying s company triggers the acted of the first buy company step. But responsible step for the button text is the second step
