### ISSUE TITLE
[1822MRS, probably 1822] Player Cash Should be Applied to Outstanding Debt Before Interest is Added

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#4636]
https://18xx.games/game/33015?action=311

At the end of this SR, Ventusignis is charged 50% interest on their outstanding loan **before** their cash on hand is used to reduce the debt.  The loan should be reduced first, and then interested should be charged on the balance.

**Comment by scottredracecar** [comment]
A player with a loan needs to be offered the option to pay it off (in part or entirely) during the SR on their turn. Is this possible now? (Was not evident to me).

**Comment by Maxwell-Frank** [comment]
I think there's a button if you can pay it off in full, otherwise it auto-applies your existing cash to the loan at the end of the SR (well, at the beginning of the next OR now, which is part of the problem).   Can you opt to not pay towards your loan for some reason?

**Comment by scottredracecar** [comment]
RAW, the only time you are allowed to pay loans is during your SR turn. I have always played that you can do a partial or full payoff during the player's SR turn (including in playing with Simon).

More practically, we've tracked loans and payoffs in different ways in face-to-face play, but I think the 18xx.games implementation should follow the rules as written. There should never be an auto-pay-loans at the end of an SR IMO. If you didn't pay off the loan when you had a chance, you can't do it then (paying off a loan is one of the things during an SR turn and if you don't do any of those things, you must "pass").

**Comment by magnusfalt** [comment]
4.2.4 The sum of any loans in play does not affect the bank limit of £12,000 i.e. treat the loan as coming from a separate source, not the bank.

EXAMPLE. During phase 4, a company has £140 cash, but no train. The director has only £20 cash. The director chooses not to buy a train from another company. The company therefore enters the emergency money raising procedure. The director first adds their £20, for a total of £160. Then the director sells one share (all that they can sell), for £80, taking the total sum to £240. However, the next available train is a 4-train, costing £300. The director therefore takes a loan of £60 to make up the shortfall. 50% interest is applied to this, resulting in a total debt of £90. **During the remainder of the operating round the player earns a further £50, which is paid off the loan as it is earned, and they thus enter the stock round with a £40 debt.** Since they have nothing that they can sell during the SR, their
debt remains and a 50% interest charge of £20 is added to it. We hope that they earn enough to pay off the outstanding balance of £60 in the next set of ORs.

New rulebook:
5.15.6 If the director, after selling all of the shares they are allowed to, still cannot contribute enough money to purchase the train, they must take a loan from the bank for the shortfall. In addition, the bank charges 50% interest (rounded up) on loans, so the amount of the debt will be 150% of the shortfall between the director’s disposable assets (cash and sellable shares) plus the company treasury and the purchase price of the train.

EXAMPLE. During Phase 4, a company has £140 cash, but no train. The director has only £20 cash. The director chooses not to buy a train from another company. The company therefore enters the emergency money raising procedure. The director first adds their £20, for a total of £160. Then the director sells one share (all that they can sell), for £80, taking the total sum to £240. However, the next available train is a 4-train, costing £300. The director therefore takes a loan of £60 to make up the shortfall. 50% interest is applied to this, resulting in a total debt of £90. **During the remainder of the operating round, the player earns a further £50. During their next stock round turn they pay £50 toward their loan (leaving £40 debt remaining)**. Since they have nothing that they can sell during the stock round, their debt remains and a 50% interest charge of £20 is added to it resulting in total debt of £60.

I will change it so it will reflect the new rulebook. As it is now you pay of as you earn, and if you sell in stock round and can pay off in full there is a button. Will change so if you earn money it wont reduce the debt automatically, and will show the button in SR whenever you have dept and if you press it it will reduce the debt in full if you have money or as much money you have.

**Comment by scottredracecar** [comment]
Yes, that bolded sentence in the old rules was a problem since that process never otherwise appears in the rules (I think). Through the iterations of rulebook edits, we hopefully cleaned up some things like that. Sorry the final rulebook took so long to post.

**Comment by mouseworthy** [comment]
> ### Change
> 
> I will change it so it will reflect the new rulebook. As it is now you pay of as you earn, and if you sell in stock round and can pay off in full there is a button. Will change so if you earn money it wont reduce the debt automatically, and will show the button in SR whenever you have dept and **if you press it it will reduce the debt in full if you have money or as much money you have**.

Wouldn't the bolded section still result in an incorrect implementation? There may be instances where you prefer to repay less than your total available cash, and this would not allow for that option.

**Comment by magnusfalt** [comment]
No @mouseworthy, as it was before you didnt even have that option. If you got money, any money that money would go toward the debt. Meaning you should never have any cash as long as you had debt.

But the intent was to have it as an action in the SR, and the only option you have is either to pay or not pay. Not how much.

**Comment by magnusfalt** [comment]
```
4.3.2 After their “sell shares” step, a player may make a payment on outstanding loans. This may be for the full amount or a partial amount. The money is paid to the bank.
```
How read this the partial amount is the loan not how huch you want to pay. So either you pay what you have as partial towards the loan or you pay the whole amount if you have this.
