### ISSUE TITLE
1870 Destination Bug - Would not allow an invalid route or a Zero run for a destination.

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#4720]
Game 34014  KADY

- from Chris W on slack

**Comment by daniel-sousa-me** [comment]
I thought I had answered this one...

When I got to the game a few hours later it had already been deleted, so I can't see what's going on. What's written in the title sounds like the expected behaviour. Maybe it was yet another instance of a false positive of the check connections auto action, which hopefully is fixed by #4752

**Comment by michaeljb** [comment]
Yeah I think you commented on slack after I had pasted this into the issue here.

**Comment by daniel-sousa-me** [comment]
Ah, good to know I'm not going crazy :P
