### ISSUE TITLE
Implement 2-player 18Chesapeake rules

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#477]
Per section 14 of the rulebook.

- President's certificates (except for Vanderbilt which is still 20%) are 30%
- When a company floats, all remaining IPO shares are placed in the market
- When a non-president buys a share from the market, one share is exported (before the buy proceeds)
- Stocks float up if market is empty (don't need 100% in player hands)

**Comment by scottredracecar** [comment]
Competitive 2p games with the current implementation are tedious because players are incentivized to trash opponents stock at every opportunity in a zero-sum game. It is fine, but takes away the decision making present in multiplayer games--here you just do it and don't question.

Also, in the current implementation (starting cash 1200 and cert limit 20), the cert limit is way too low. 32 would be a better number if the official 2p rules are not implemented.

The game functions as is, but the official 2p rules would be better. The current rules could be kept as a 2p variant (with 32 cert limit).

**Comment by sparr** [comment]
I am attempting to work on this.
