### ISSUE TITLE
[1822] Discard step should occur before acquire corporation

### ISSUE THREAD

**Issue by ViennaTramways** [tobymao/18xx#4773]
https://18xx.games/game/33271

OR starts. Next available train is a 5T. Minor 8 acts first. After clicking "Skip (Acquire companies)" all three minors are skipped and game proceeds with the first major.

The same thing happened at:
https://18xx.games/game/31244
5T are available...

**Comment by magnusfalt** [comment]
The game doesnt skip the minors. Its accually a Discard Train step, and MR is the only Corporation that need to discard a train. After MR have discarded a Train, the game will continue on the minor 8 track step.

I put the discard train step after aqcuire company just because of the 2P, LP and 5P which you can acquire and maybe must discard a train.

I will put this as an enchantment issue to put a discard train step first in the step just to catch train that needed to be discarded after a train have been exported.

**Comment by ViennaTramways** [comment]
OK, now I feel a little bit silly.
Of course it's a discard step. If I would have read it carefully...
Thank you for the hint!
lonny

Am Mo., 29. März 2021 um 13:38 Uhr schrieb Magnus Fält <
***@***.***>:

**Comment by jenf** [comment]
Exact action
https://18xx.games/game/33271?action=600

**Comment by magnusfalt** [comment]
To clarify, there should be a discard step first in the OR to catch the exported train. There should be a discard step after acquire privates since you can aquire the 5P and need to discard a train, and lastly there should be one after aquire minor.

**Comment by KevinR1000** [comment]
I think that the issue arises in lib/engine/game/g_1822/round/stock.rb around lines 156 and 173.
```
def remove_minor_and_first_train(company)
    train = remove_train
...

def remove_train
    # Remove the next train
    train = @game.depot.upcoming.first
    @game.remove_train(train)
    @game.phase.buying_train!(nil, train)
    train
end
```

Two notes:
- The call to `@game.phase.buying_train()` is much more complex in g_1822/step/buying_train.rb lines 31-36.  Maybe this is an issue?  [The comment there suggests that variant trains in 1822 are an issue.]
- Would reversing the order of lines 176 and 177 change this?  Maybe `buying_train!(nil,train)` fails after `remove_train(train)`.

**Comment by magnusfalt** [comment]
Thank you @KevinR1000 for your willing to search for solutions. But the above code is correct, the problem is if you look at lib/engine/game/g_1822/game.rb on lines 935 to 955

```ruby
        def operating_round(round_num)
          G1822::Round::Operating.new(self, [
            G1822::Step::PendingToken,
            G1822::Step::FirstTurnHousekeeping,
            Engine::Step::AcquireCompany,
            G1822::Step::DiscardTrain,
            G1822::Step::SpecialChoose,
            G1822::Step::SpecialTrack,
            G1822::Step::SpecialToken,
            G1822::Step::Track,
            G1822::Step::DestinationToken,
            G1822::Step::Token,
            G1822::Step::Route,
            G1822::Step::Dividend,
            G1822::Step::BuyTrain,
            G1822::Step::MinorAcquisition,
            G1822::Step::PendingToken,
            G1822::Step::DiscardTrain,
            G1822::Step::IssueShares,
          ], round_num: round_num)
        end
```

The `G1822::Step::DiscardTrain` is after `Engine::Step::AcquireCompany`. Ive made it so if you aqcuire the 5P train you might be needing to discard a train. I forgot about the Export train.

Its a really easy fix, just include a `G1822::Step::DiscardTrain` first in the operating round and if a train have been exported in the end of stock round it till be cought. But if we do this, many games will break and we will need to PIN all the broken games, and this is a manual step for the person which is deploying to the live servern. This is the reason i havent changed it yet.

**Comment by KevinR1000** [comment]
The `G1822::Step::DiscardTrain` at the end looks out of place as well, but that is probably reasonable for game flow.  `G1822::Step::DiscardTrain` requires response from other players, but that response is obvious enough that waiting until the active player is entirely done is fair for 18xx.games.

So it looks like one `G1822::Step::DiscardTrain` should move to the very first step in an OR and the other `G1822::Step::DiscardTrain` should  move to the very last step in an OR.

(Thanks for point me to the main loop.  New enough to this code (and style of coding) that I hadn't known were to look.)

**Comment by magnusfalt** [comment]
No the `G1822::Step::DiscardTrain` steps are correct where they are. The first is if you aquire the 5P, with this you might need to discard a train if you are over limit. If we move this before then you might be able to run to many trains.

The last `G1822::Step::DiscardTrain` is if you acquire a minor and you goes over you limit, you will have to discard trains down.

As i said, the correct is to add additional `G1822::Step::DiscardTrain` first in the loop.
