### ISSUE TITLE
[Harzbahn 1873] For opened but not floated company: concession owner should keep concession

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#4850]
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

https://18xx.games/game/33488

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

- In Auction Round 5 player DSteiner got the KEZ concession
- In SR 5.1 he bought a KEZ share, thus forming the KEZ
- The KEZ did not float in that SR, though.
- But at some stage of the game I was unable to reconstruct, he lost ownership of the KEZ concession.
- This is not correct: he should have kept the concession until the KEZ buys its compulsory train (after it has floated in a later stocj round).

Klaus Kiermeier

**Comment by roseundy** [comment]
I think this is just a display issue. The "KEZ Concession" is displayed only on their player card until the KEZ is formed. At that point I remove it, since it has been "used" to form the KEZ. Since they will remain the director until the concession requirements are completed by the KEZ, I have no need to track it further.

I use the "Concession" flag attached to the player to determine whether the player has forfeited the Concession at the end of the stock round.

If you like, I can add a status message to a Railway card with an incomplete concession. In either case, my code is keeping track.
