### ISSUE TITLE
[Harzbahn 1873] Diesel route affecting revenue from normal trains

### ISSUE THREAD

**Issue by roseundy** [tobymao/18xx#4867]
Game https://18xx.games/game/33770?action=1725

When the Diesel routes are added, the revenue produced by the "normal" trains drop by the amount the diesels are running for.

**Comment by KlausKiermeier** [comment]
Yes, indeed, and moreover: a third diesel route (apart from the 2-part concession route of the NWE), in this case from D7 to D9 was not accepted.

**Comment by roseundy** [comment]
Both the highest_train_at_stop? and stop_on_other_route? need to ignore Diesels.

**Comment by roseundy** [comment]
I managed to get D7-D9 in my diesel run, but there is another issue, #4865, that could have affected your play.

**Comment by roseundy** [comment]
![8 colors](https://user-images.githubusercontent.com/8494213/112901647-41ebb480-90a2-11eb-9867-4fa45a979f55.png)

**Comment by KlausKiermeier** [comment]
Yes, Steve, I realized this already: If the NWE ran only 5 routes with 
standard trains, then a third Diesel route was accepted.



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Steve
Betreff: Re: [tobymao/18xx] [Harzbahn 1873] Diesel route affecting revenue 
from normal trains (#4867)
Datum: 29. März 2021, 23:20
An: tobymao/18xx
Cc: KlausKiermeier, Comment



I managed to get D7-D9 in my diesel run, but there is another issue, #4865
<https://github.com/tobymao/18xx/issues/4865> , that could have affected 
your play.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/tobymao/18xx/issues/4867#issuecomment-809721934> , or 
unsubscribe
