### ISSUE TITLE
[1873] Mine machine and switcher values not visible when using black background

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#4913]
Suggest using contrast method, so values are in a white box when using a black background.

**Comment by ChrisTheCat** [comment]
The borders do show up when the company is greyed out during the stock round because the active player can't do anything with that company.

<img width="670" alt="Screenshot 2023-02-17 at 10 39 55" src="https://user-images.githubusercontent.com/8732435/219756898-05b10737-a3fc-4748-a80e-b919fab23b13.png">
