### ISSUE TITLE
[1867] Cornwall tile placement

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#4939]
Is there an easy to miss rule, that I can't find or is there a bug? 

game: 1867
ID: 34248

With CV I can't lay another tile than a sharp edge w/ small city on K13 / Cornwall. 

https://18xx.games/game/34248

**Comment by Maxwell-Frank** [comment]
There is a pre-existing track stub leadout out of the SW edge of Montreal that must be preserved. Coming from CV's token, the only tile that CV can lay that it is connected to and preserves the pre-existing stub is the sharp curve.  

This is usually irrelevant because minors usually start in both yellow Montreal stations before this becomes an issue.

**Comment by Ticketautomat1** [comment]
Thank you @Maxwell-Frank 
Haven't seen this little tiny piece of track  :D

That makes sense! Thank you
