### ISSUE TITLE
1860 Private Issue

### ISSUE THREAD

**Issue by Jlamb52** [tobymao/18xx#4999]
You should be able to par a corporation in 1860 and then immediately exchange your private for the reserved share, as it is currently implemented you are auto passed to the next player if you par and you cannot exchange before parring.

**Comment by roseundy** [comment]
Hmmm. The fix is going to break a lot of games. I'll see what I can do.

**Comment by roseundy** [comment]
I'm going to ask why this needs to be fixed. You will get another stock turn and you may exchange then. It won't count as an action so it won't affect priority deal.

**Comment by Jlamb52** [comment]
its a rare case where you can do it right before the private that closes others is available. could just mastermode to another turn theoretically then

**Comment by roseundy** [comment]
Normally, I wouldn't argue about making a fix, but the problem is that if I fix this pretty much every single existing game will be broken and require pinning. This is because I'll have to force players to submit a "Pass" action after they par a company if they have any of the four exchangeable privates.

I could add an option to the Par action to exchange the corresponding private, but that will require a bit of work.

**Comment by roseundy** [comment]
Shoot. I was hoping there was a test case for this. It will take me some time to create one before I can fix this.

**Comment by roseundy** [comment]
OK, I managed to find a case. My fix will "break" a limited number of games (actually, if in progress, they will be pinned).

The game will now allow an exchange after a par if the player owns the corresponding private to the one being parred but only if Fishbourne is available (phase 6 or later). I'm trying to cause the least amount of perturbation possible.
