### ISSUE TITLE
info tab unavailable (18MEX, all trains sold)

### ISSUE THREAD

**Issue by arcee1986** [tobymao/18xx#5084]
The "Info" tab is unavailable in https://18xx.games/game/32903 (18MEX). All trains have been sold, but it's still a useful location to find that out cleanly and to get the rules link.

**Comment by KevinR1000** [comment]
[my notes also in slack]

This might be due to a failure to check for an empty depot, and I think that I may have identified where (although I've never programmed in whatever language this is, so I'm not sure).

File 18xx/assets/app/view/game/game_info.rb uses a variable/object "first_train" in two places:
<line 204>  first_train = @depot.upcoming.first
<line 233>  name = (train.name == first_train.name ? '→ ' : '') + names_to_prices.keys.join(', ')

I suspect that line 233 needs to have a check like "if first_train != nil"
