### ISSUE TITLE
1860 holding the towns issue

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#5180]
https://18xx.games/game/39137?action=512

The NGStL runs a 4+2 train from: F2-F2-F2-F4-G5-G3-H4-H4-H8-H10-G9-G7 and it does not give the option to hold both the 20 and 10 value towns as a subsidy. Only one or the other.  I hope this isn’t a duplicate cuz I couldn’t find it anywhere else!  Thanks all!
Jen

**Comment by Blobbley** [comment]
Was lurking on Github and saw this.

The NGStL has a 4+2 and runs it to: G7-G9-H10-H8-H4-H4-G3-G5-F4-F2-F2-F2

Big cities on that route are: G7 (20) - G9 (20) - G5 (60) - F2 (60) = 160

There are three towns on route (2x 10 and 1x 20) and 5 halts.

The interface when running the route gives three options:

160 + 20 - all four big cities plus two halts [4+0]
180 + 10 - all four big cities, the 20 town plus one halt [4+1]
190 + 0 - all four big cities, the 20 town, a 10 town and none halts [4+2]

These are all the options that should be given, there aren't any alternatives (save running to both 10 value towns instead of the 20 value one but I think the implementation choice is the best option here). I think OP is getting confused between the role of towns and halts - towns add to the money you can pay out as dividends. Halts can be included to pay directly to the treasury and are displayed in the clickable box on the revenue screen. Each halt = £10.

Hope this is a helpful clarification for closing the issue!

**Comment by Eludyan** [comment]
Thanks!  I totally misunderstood the rule. I appreciate the clarification! 
Jen
