### ISSUE TITLE
[18Ireland] dcr label is not in the right hex

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#5274]
DCR label is shown on H4, but the action allows a tile lay on F4. 

It would also help if the hex coordinates were included in the private description for DCR. And actually most other privates in 18Ireland.

**Comment by jeroenh** [comment]
Also, the label  does not seem to be shown on the starting map.

**Comment by benjaminxscott** [comment]
It looks like [P6 - DCR is supposed to be in H4](https://i.imgur.com/OwuP40j.png) , so the current config is incorrect - i'll make a PR

Re: your second comment, It looks like the DCR private shows up on the in-game map, but it's contingent on the private not being removed during the setup process
![image](https://user-images.githubusercontent.com/1711810/117516479-1506a900-af4e-11eb-9d86-b6b933fdd0d9.png)

The [base map](https://18xx.games/map/ireland) doesn't show private reservations, since it doesn't know whether they exist or not in a particular game

Is that what you're referring to?

**Comment by jeroenh** [comment]
Okay, given that it makes sense that the private is not shown on the base map. Thanks!
