### ISSUE TITLE
[18Ireland] pre filled track jumps to wrong city on DD tile (I9)

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#5279]
https://18xx.games/game/40351?action=804

If a company's track uses the small dit on DD tile (I9), the pre filled track jumps to the big city, whether the company runs this track or not.

**Comment by jenf** [comment]
Alas, archived. But is still a bug

**Comment by jenf** [comment]
Saw it
https://18xx.games/game/41305?action=946

**Comment by jenf** [comment]
Problem is the route doesn't store which stop it actually goes to
            [
              "I9",
              "H8",
              "G7"
            ],
            [
              "I11",
              "I9"
            ],

**Comment by dfannius** [comment]
The information necessary to reconstitute the correct paths on hex I9 is not available in the `run_routes` action, since there are two ways to go from the NW exit to the S exit. `Route::find_pairwise_chain` just returns the first set of paths it finds.

Fixing this would require storing more information in the `run_routes` action (either generally or in identified special cases) and using that when recreating the paths in `find_pairwise_chain` or elsewhere.

There is already some special-case code for handling paths between two nodes on the same tile; see `Route::chain_id` and `Tile::ambiguous_connection?`. It's possible that that could be extended to handle this case but the existing code seems to be very specifically about node-node paths on a single tile and I didn't see a way to easily generalize it.

My preferred design would be to have the serialization of routes include the actual connections, but that's not how the code works.

**Comment by roseundy** [comment]
@dfannius

See #7205. I would have though this fix would have addressed that.

In 7205, we have this route being reconstructed:
![18mo_route](https://user-images.githubusercontent.com/8494213/154390435-deb70384-2e76-4bb4-a821-eb9da8263abf.PNG)

The previous run serialized the nodes like this:
"nodes": [
            "J4-611-0",
            "K3-K3-0",
            "K7-K7-0",
            "J8-X3-0",
            "I7-611-0",
            "J8-X3-2",
            "G9-290-0",
            "D8-6-0",
            "C7-C7-0",
            "A7-A7-0"
          ]

The tile X3 was changed for X4, but the node numbering is the same. Node 2 connects edge 2 with edge 4. But when the route is reconstructed, it is getting confused. So I think something is wrong with the deserialization that was added.

**Comment by dfannius** [comment]
(I took the conversation about #7205 back to that issue.)
