### ISSUE TITLE
[1822] Game pinned after update

### ISSUE THREAD

**Issue by Felipealou67** [tobymao/18xx#5299]
https://18xx.games/game/34729?action=190

Cannot be deleted or finished by users.

```
We're sorry this game cannot be continued due to GameError: Cannot lay a yellow now
Broken action: { "type": "lay_tile", "entity": "P21", "entity_type": "company", "id": 191, "created_at": 1617499812, "hex": "N21", "tile": "6-5", "rotation": 0 }
Please raise a bug report and include this link (https://18xx.games/game/34729?action=190)
[21:29]9 (P21) lays tile #6 with rotation 1 on N23 (Grimsby)
[21:29]----
[21:29]Your game was unable to be upgraded to the latest version of 18xx.games.
[21:29]It is pinned to version 9f0a95280, if any bugs are raised please include this version number.
[21:29]Please note, pinned games may be deleted after 7 days.
[21:29]----

```

**Comment by benjaminxscott** [comment]
If you'd like to continue the game, attempt to undo to action 190 and take an action
(note that this is not guaranteed to work)

To add some context, the game can't be continued from its current state since it's not compatible with the latest version of server-side code

"pinning" is when we maintain a copy of the old server-side code to allow deprecated games to potentially continue
(but it's not guaranteed that the deprecated game state will be compatible, and deprecated games may be deleted)

**Comment by tobymao** [comment]
pinning is when we maintain a copy of the client side code and skip server side validation so that you can continue your game. if the game is broken, it probably got pinned to the wrong version

**Comment by tobymao** [comment]
someone with DB access should just archive the game and close this issue

**Comment by Felipealou67** [comment]
That would certainly be our preference.

We cannot do this.

mike

**Comment by jenf** [comment]
Archived

**Comment by Felipealou67** [comment]
Thanks Jennifer!
