### ISSUE TITLE
Seems like you can buy trains from other players in 2P game for $1

### ISSUE THREAD

**Issue by chrisdavis103** [tobymao/18xx#534]
We were well into the game where in the trains portion of the OR, at about train type 4 or so, i was able to buy trains from the other player for $1.   That doesn't look right, but I'm not sure.

Game ID is 1324.

**Comment by jenf** [comment]
It's legal but seldom used. Unfortunately your game is pinned otherwise you'd see the new "Show other players trains" which hides other players trains by default.

From 18Chesepeake rules:
The train may be from another company, with
its president’s consent. In this case, the price is any amount, at
least $1 and not exceeding the active company’s treasury

**Comment by chrisdavis103** [comment]
thanks!
