### ISSUE TITLE
[ 1862 ] Hex B13 London Connectivity Issue

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#5373]
When I built track on B13 and the connection to London was connected via the SW offboard arrow. It didn't seem to register that my company was connected to London. When I built it so the connection was directly south. London lit up as if I were connected to it.

**Comment by roseundy** [comment]
It would be helpful to reference a specific game you saw this on.

However, I was able to reproduce this, and this isn't a bug that affects game play. That fact that London lights up or not doesn't affect anything. At most, this is a UI issue where London shouldn't light up at all. It lights up because part of the code thinks London can be tokened, even though it's not legal to do so if you built track in the current turn.
