### ISSUE TITLE
[1862] error when unable to buy an additional share after parring a chartered corporation

### ISSUE THREAD

**Issue by otdewiljes** [tobymao/18xx#5383]
![image](https://user-images.githubusercontent.com/4226724/118713640-7833ed80-b822-11eb-952d-234d50ecdb01.png)

Can't par on anything other than 54 in PR3. Pressing another button results in the error above.

**Comment by KevinR1000** [comment]
I think the bug is here:
https://github.com/tobymao/18xx/blob/0d975831d60a6c8eaec0252acc6cc9117a3efdac/lib/engine/game/g_1862/step/charter_auction.rb#L143

`def process_par` does not have `entity` defined, but the log message uses `entity.name` if there is insufficient cash to buy a share.  In this case, oddman has 4x the lowest par but only 3x the higher pars, so cannot buy a share after parring.

**Comment by roseundy** [comment]
Yep, just came here to post that I found the bug. It's exactly as @KevinR1000 says. I'll take care of it.
