### ISSUE TITLE
1862 - after prompted to sell, could not sell share to fund new train

### ISSUE THREAD

**Issue by MarcusBatty** [tobymao/18xx#5400]
42507
[11:16]MarcusBatty: "blocking step - buy trains cannot process action 579"
[11:17]MarcusBatty: trying to sell 1 share of N&B for $220 for forced train purchase
[11:17]MarcusBatty: is this a bug?

https://18xx.games/game/42507
https://18xx.games/game/42507?action=578

**Comment by roseundy** [comment]
The game should not be offering you the opportunity to sell your own shares since that is against the rules. That is a vestige of other games.

The only legal option is the one shown at the top. I'll fix the buy_train step.

Note that you can't actually break the game rules. It will give you an error. But it shouldn't even give you the option.

**Comment by MarcusBatty** [comment]
Thanks!  I was wondering about that entire sequence.   Refinancing is the way to go there.
Your work is much appreciated!
