### ISSUE TITLE
[1862] Placing on corps Home in yellow phase

### ISSUE THREAD

**Issue by joeyd4329** [tobymao/18xx#5413]
https://18xx.games/game/42802?action=126

Is this legal, and does the ENR get to boot the WNRs token after? I've heard different views,

**Comment by roseundy** [comment]
Yes this is legal. If the game was in the green phase, then ENR would be compelled to upgrade to make room. But since it's in the yellow phase, WNR gets booted.

From the rules (7.2):

"If the home station hex has a track tile on
it which does not contain space available for the token, then the
director must upgrade the home station hex as its track build for
the first turn if it can. Such a tile lay or upgrade will count as the
company build for the operating turn. If there is still insufficient
space on the company home station hex for the company to place
its station marker then it displaces one of the tokens already there,
which is sent back to the company owning it"
