### ISSUE TITLE
1873 Harzbahn Issued Company Shares

### ISSUE THREAD

**Issue by knauman** [tobymao/18xx#5445]
Shares of a company after splitting are placed into an IPO and do not reside in the treasury. Using "Treasury" as the description for where the shares are located may make players believe the company will receive income from shares during pay-outs - They do not. Shares may never be in the treasury of a company. The coding is correct as what is paid.
![image](https://user-images.githubusercontent.com/51214001/119258714-ec5ef000-bb98-11eb-97c1-669226333a02.png)

**Comment by roseundy** [comment]
First, I don't know what you mean by "splitting". There is no such thing in the rules I have.
Second, it seems like you are unhappy by the word "Treasury" here. There are many different rules across 18xx games about how shares pay out in the IPO, treasury and market.

**Comment by knauman** [comment]
Sorry, wrong word there. Not split but convert.

**Comment by roseundy** [comment]
@KKiermeier @KlausKiermeier  do you have an opinion on this?

**Comment by KlausKiermeier** [comment]
Steve, 

personally I have no problems with the term "treasury" for shares in the initial offering. But I see that people may have problems, thinking there would be init cash available, which isn't the case as you know. 
The rules of Harzbahn use the terms "initial offering" and "bank pool" and of course I think it would be better to use these terms here too. 
On the other hand, I have the impression that the terms "treasury" and "market" are generally used on 18xx.games to specify the state of available shares,  and that's why I am not going to insist on a change here. And more so since I have no idea how complicated such a change would be.

Cheers, Klaus
 
 
 
-----Original-Nachricht-----
Betreff: Re: [tobymao/18xx] 1873 Harzbahn Issued Company Shares (#5445)
Datum: 2021-05-30T20:36:02+0200
Von: "Steve" ***@***.***>
An: "tobymao/18xx" ***@***.***>
 
 
 
 
@KKiermeier @KlausKiermeier do you have an opinion on this?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/tobymao/18xx/issues/5445#issuecomment-851042319", "url": "https://github.com/tobymao/18xx/issues/5445#issuecomment-851042319", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]﻿
