### ISSUE TITLE
1861 - Must hit Skip (Companies) twice   (when at train limit)

### ISSUE THREAD

**Issue by MarcusBatty** [tobymao/18xx#5473]
https://18xx.games/game/41460?action=467

Minor Bug - must hit Skip (Companies) twice...probably because I am at the train limit?
Note the log states that I skipped train buys after I hit skip companies the first time, but trains were never presented to me.
It might not be obvious, because I had a few undos during the turn.

**Comment by Maxwell-Frank** [comment]
You are skipping the "buy companies" phase *before* you pay your loan interest and pay off loans, then you are skipping the train buy phase automatically (because you are at train limit, then you are skipping the "buy companies" phase *after* you've paid your interest.  There are two buy companies phases to allow you to buy your companies in before you pay off your loans/interest.

**Comment by scottredracecar** [comment]
Sure, but it makes sense to skip the second “buy companies” step if all intervening actions were also skipped.

**Comment by Maxwell-Frank** [comment]
It wasn't, though. The company had loans (and interest) that it paid off. One could argue that if a player could have done math and bought the company in before the loans and interest were paid, but I'm not sure that's the issue at hand.

**Comment by scottredracecar** [comment]
Yeah, I suppose so. I meant “automatically processed” instead of skipped. I suppose the alternative is no better. I suggest to close as “not a bug.”

**Comment by scottredracecar** [comment]
I now realize that since loans are auto-repaid in 1861, these two passes are completely discrete and it is essential to provide separate windows for the company buy here. If you do it before, you may change the repay the loan step. And if you do it after, you will know how much cash remains after loan repayment so that is another important window.

So it is definitely not a bug.
