### ISSUE TITLE
[1862] company with no open route to London is still allowed to token London

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5484]
https://18xx.games/game/42532?action=342

In this game, WStL was able to drop a token in London, despite not having an open route to London. (We’ve undone and corrected the action, but it can still be performed from there in hot seat mode. 

Issue was reproduced by other players on their respective computers/phones.

**Comment by roseundy** [comment]
Sigh, another deficiency of my first edition rules. My rules don't say either way whether a company needs to be to trace a route to London in order to token it. Since it's in the GMT rules and Mike Hutton didn't list this as a change between editions, I have to abide by the GMT rules and add the check.
