### ISSUE TITLE
[1846] unable to proceed after upgrading Dayton with Little Miami

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#5490]
https://18xx.games/game/43634

I’ve activated LM to upgrade Dayton. This connects it to Cincinnati. At this point, if I click Pass, I get an error saying “H12 and G13 are already connected, can’t use little Miami.” Prior to the upgrade, the tiles weren’t connected. 

If I try also upgrading Cincinnati I also get this error. 

It’s also worth noting that if I try upgrading Cincinnati first, it allows that upgrade (which it probably shouldn’t), and then still gives the same error when I try to upgrade Dayton. 

reproduced error on multiple machines.

**Comment by michaeljb** [comment]
Hopefully I’ll have time to look at it this evening.

> It’s also worth noting that if I try upgrading Cincinnati first, it allows that upgrade (which it probably shouldn’t)

FWIW I am not going to change this behavior, that would require calculating all possible Cincinnati/Dayton tile lay combos that are legal for Little Miami from the current state which is a lot harder than just checking before and after if the move was legal. I believe the “Implementation Notes” section in the wiki mentions this, but if what’s there is unclear, suggestions are welcome 🙂

**Comment by michaeljb** [comment]
Think I found the problem, it's related to the `loading` check (which impacts things like Undo actions and loading the game to a specific point), should be a quick fix this evening.

@philcampeau before then you should be able to undo the first Little Miami tile lay (so that the last action is C&O buying it in), refresh, and then manually do the tile lay again, and then pass.
