### ISSUE TITLE
[1846]

### ISSUE THREAD

**Issue by TomdeGre** [tobymao/18xx#5513]
B&O has to emergency fundraise to buy a brown train (OR2.2), but is only allowed to buy a 5T while the director contributes from hand, with no option to instead get the 4/6 train (which is cheaper and should be the default purchase?).

https://18xx.games/game/43914

**Comment by dfannius** [comment]
https://18xx.games/hotseat/hs_hdmeuhlj_43914?action=290

**Comment by dfannius** [comment]
I assume that this because B&O could have bought a 4/6 with Boris's cash without Boris having to sell any stock. Once Boris sells stock, I guess he has to use the money he made.

6.87:

> However, once a corporation has to use cash from its President to purchase a required train, then it may freely buy from the bank any available phase or type of train.

6.88:

> A President who doesn’t have the needed cash must raise it by selling stock shares. The President may sell any shares, subject to the normal restrictions, except shares that would cause a Presidency change in the corporation currently operating.
> Once the amount needed has been raised, no further sales may be made.


So I think B&O is allowed to buy a 5T (by 6.87), but if they were going to buy a 4/6T, then by 6.88 the president already has enough money for it to buy the 4/6T (without selling any stock), and he can't make any more sales (than zero).

Leaving it open for now to let other people confirm or argue.

**Comment by michaeljb** [comment]
> So I think B&O is allowed to buy a 5T (by 6.87), but if they were going to buy a 4/6T, then by 6.88 the president already has enough money for it to buy the 4/6T (without selling any stock), and he can't make any more sales (than zero).

Yep, this is all correct.

I imagine a solution for #2219 would have avoided the confusion here. I really would like to get to that one some day..
