### ISSUE TITLE
[Harzbahn 1873] Buying Trains/Switchers across incurs maintenance a second time.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5533]
Env: Chrome
Hotseat: https://gist.github.com/physic/c41d8454196a7d92c3e1ffb02dae55dd
see action 514, action 530

Repro:
Run a company, pay maintenance on a train.
Run another company in the same Operating Round, buy the train from the first company.

Expected: Maintenance is not owed again on the train bought across, because it has already been paid.
Observed: Maintenance was charged twice.

**Comment by roseundy** [comment]
I need a ruling from @KlausKiermeier on this.  It's not clear to me what the rules dictate here. I can see your point completely, but looking at the specific rule it makes no mention of whether the company that formerly owned the train has operated or not.

**Comment by KlausKiermeier** [comment]
Yes, in the situation described by physic above the maintenance costs are charged twice.
And this is intended.
 
 
 
-----Original-Nachricht-----
Betreff: Re: [tobymao/18xx] [Harzbahn 1873] Buying Trains/Switchers across incurs maintenance a second time. (#5533)
Datum: 2021-05-31T16:47:27+0200
Von: "Steve" ***@***.***>
An: "tobymao/18xx" ***@***.***>
 
 
 
 
I need a ruling from @KlausKiermeier on this. It's not clear to me what the rules dictate here. I can see your point completely, but looking at the specific rule it makes no mention of whether the company that formerly owned the train has operated or not.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/tobymao/18xx/issues/5533#issuecomment-851538139", "url": "https://github.com/tobymao/18xx/issues/5533#issuecomment-851538139", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]﻿
