### ISSUE TITLE
[Harzbahn 1873] Tiles reserved for Concession Routes cannot be laid, even on that hex.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#5534]
Env: Chrome
Hotseat: https://gist.github.com/physic/c41d8454196a7d92c3e1ffb02dae55dd
See action 668 (among others). Try to lay Blankenburg.

Per 4.2.1, when laying a tile over top of a concession route, the appropriate upgrade tile is reserved "for this hex". I should only be prevented from laying it *elsewhere*. Currently, I am prevented even from laying it on that hex.

Repro:
In the above hotseat game, try to lay Blankenburg.

Expected: 1. I can lay brown Blankenburg in a way that completes the concession route. 2. I can lay Blankenburg another way, causing the grey upgrade tile to become "reserved"
Observed: Blankenburg can never be laid until the WBE runs and lays it as part of its first turn.

I assume this bug also exists for any concession route track, not just Blankenburg.

**Comment by roseundy** [comment]
That's my understanding of what "reserved" means. I need @KlausKiermeier to comment:

Once a tile is reserved, are other companies allowed to lay that tile on the concession hex, or only the concession company?

**Comment by KlausKiermeier** [comment]
There is a sentence in 4.4.1 of the rules that may be misleading in this respect, namely:
"If the corresponding company later builds its concession route, such reserved tiles are then used even if tiles of that colour are generally not yet available in the current game phase." 

This is not meant to mean that the reserved tile can only be built by the respective company whose concession route is to be completed. Rather, it is reserved for the hex and can be built there in the pre-determined way by other companies. The sentence above is merely intended to allow the respective company to build this tile even if "tiles of that colour are generally not yet available in the current game phase." 
 
 
 
-----Original-Nachricht-----
Betreff: Re: [tobymao/18xx] [Harzbahn 1873] Tiles reserved for Concession Routes cannot be laid, even on that hex. (#5534)
Datum: 2021-05-31T17:01:15+0200
Von: "Steve" ***@***.***>
An: "tobymao/18xx" ***@***.***>
 
 
 
 
That's my understanding of what "reserved" means. I need @KlausKiermeier to comment:
Once a tile is reserved, are other companies allowed to lay that tile on the concession hex, or only the concession company?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/tobymao/18xx/issues/5534#issuecomment-851545520", "url": "https://github.com/tobymao/18xx/issues/5534#issuecomment-851545520", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]﻿

**Comment by KKiermeier** [comment]
And only the concession company is allowed to build such a tile in an earlier phase.

**Comment by roseundy** [comment]
OK, I'll reopen this code.

**Comment by physic** [comment]
Klaus, In this case, the game was in brown phase already (phase 4 and 5 broke in the same OR set and WBE had not yet run). The Blankenburg brown tile could not be laid by the SHE because it was reserved for the WBE.

The SHE should be able to lay the brown Blankenburg, even pointing away from WBE's concession route, correct?

**Comment by KlausKiermeier** [comment]
Hi, thanks very much for finding this bug! Since: in fact, the brown Blankenburg tile was, as I already mentioned earlier, not reserved for the WBE but for the Blankenburg hex. So, you are right, in the game state you describe, for the SHE it should have been possible to use the reserved brown tile in order to upgrade Blankenburg. Moreover, yes, you are right again, this upgrade should have been possible even pointing away from WBE's concession route -- thus reserving the grey Blankenburg tile for the completion of the WBE concession route. 
 
 
 
-----Original-Nachricht-----
Betreff: Re: [tobymao/18xx] [Harzbahn 1873] Tiles reserved for Concession Routes cannot be laid, even on that hex. (#5534)
Datum: 2021-05-31T17:56:09+0200
Von: "physic" ***@***.***>
An: "tobymao/18xx" ***@***.***>
 
 
 
 
Klaus, In this case, the game was in brown phase already (phase 4 and 5 broke in the same OR set and WBE had not yet run). The Blankenburg brown tile could not be laid by the SHE because it was reserved for the WBE.
The SHE should be able to lay the brown Blankenburg, even pointing away from WBE's concession route, correct?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/tobymao/18xx/issues/5534#issuecomment-851573416", "url": "https://github.com/tobymao/18xx/issues/5534#issuecomment-851573416", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]﻿

**Comment by physic** [comment]
My pleasure! I, for one, am delighted that you have your eye on people's bug submissions, and weigh in so quickly.

**Comment by roseundy** [comment]
Don't worry. Klaus keeps a close eye on me :-)
