### ISSUE TITLE
[18Ireland] Able to lay BG though only connected by NG

### ISSUE THREAD

**Issue by skizelo** [tobymao/18xx#5576]
Players are able to lay Broad Gauge track in hexes they are only connected to via Narrow Gauge.
From the rulebook, section 6.5: "When laying a yellow tile that includes broad gauge track, at least one section of that track must be connected by broad gauge track to one of the company’s station markers"

https://18xx.games/game/39623?action=655
![sligo](https://user-images.githubusercontent.com/77389765/120543435-37bc9e00-c3e4-11eb-85fe-6873de49ccee.png)

**Comment by dfannius** [comment]
@jenf [`tile_uses_broad_rules?`](https://github.com/tobymao/18xx/blob/866f8edf468661e78d8227683ac5dff2be6f61d8/lib/engine/game/g_18_ireland/game.rb#L430) looks suspicious to me. It is returning `false` for the track lay in question but I think the intent is that it return `true`.

In particular, the comment says "Broad gauge lay is if any of the new exits broad gauge?" but the code is doing an `all?` rather than an `any?`; it looks like it's asking "are all paths either broad or old?" when my expectation is that it would say "are any paths both broad and new?" But I'm not that familiar with 18Ireland, or its code, or the map system in general.

**Comment by dfannius** [comment]
Changing the line in question from
```
new_tile_paths.all? { |path| path.track == :broad || old_paths.any? { |p| path <= p } }
```
to
```
new_tile_paths.any? { |path| path.track == :broad && old_paths.none? { |p| path <= p } }
```
fixes this issue, as expected. But I want to make sure that that truly matches the intended semantics of this method.

**Comment by dfannius** [comment]
I tried it out and it seems to work as intended. There does need to be one special case for the IR9 tile since it doesn't have any new track. Three out of the most recent 18Ireland games to have finished have exactly this kind of illegal tile lay; they were caught by the new code and there were no other false positives.
