### ISSUE TITLE
1856: Allowed to full cert when only half cert below limit

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#5712]
https://18xx.games/game/46189?action=845#tools

**Comment by dagibbs** [comment]
This issue seems to have recurred/come back.

Game: https://18xx.games/game/100214 after action 920 (I would guess action 921) -- Dagrim is at 10.5 of 11 certificates, but is not allowed to buy another share.

The linked rules, in the "CGR Share Limits" section, include the line: "Players may hold one half certificate above the current stock limits, but players may not purchase a half share if they are as their limit."

At 10.5 of 11, I should not be at my limit -- and so I should be able to purchase a full share, and end up 1/2 share above my limit.

**Comment by outsidePasser** [comment]
There is discussion on boardgamegeek about this here:  https://boardgamegeek.com/thread/1747103/extra-05-share

The conclusion seems to be that the revised rules deleted that line - and therefore you should not be able to purchase a full share.

**Comment by dagibbs** [comment]
The rules linked from the 1856 wiki (https://github.com/tobymao/18xx/wiki/1856) include the (later) deleted rule.  I made in-game decisions based on the linked rules.  

I would suggest, then, that the "Implementation Notes" section clarify which rule-set was being followed in this situation.
