### ISSUE TITLE
[1856] Lots of decimals shown on charters

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#5921]
Here is how the game looks right now:
![image](https://user-images.githubusercontent.com/2631151/124344789-d2bbba00-dbd4-11eb-99dd-611867b6a44c.png)

This is https://18xx.games/game/44377

I checked some other titles (1817, 18MEX, 1862) but these did not contain any fractional display.

**Comment by KevinR1000** [comment]
The problem might be `CURRENCY_FORMAT_STR = '$%f'` in PR https://github.com/tobymao/18xx/pull/5913 .

If the various `def format_currency` work as intended, then integer shares are formatted as `'$%f'` which will presumably give six digits after the decimal point (since this looks rather C-like).  Non-integer shares are formatted as `'$%.1f'` which has only one digit after the decimal point.

Maybe the default needs to be `'$%.0f'`?

**Comment by ventusignis** [comment]
The default needs to be `%d`; if you use %f` this happens as I found out. You can do '%0.1f` but then you'll always see a zero. In `currency_format` there's some logic to determine which format to use and I missed reverting this '%f' back to a '%d'
