### ISSUE TITLE
1840 illegal action

### ISSUE THREAD

**Issue by Andrewey** [tobymao/18xx#5949]
47544 all actions including pass result in an illegal blocking action message

**Comment by Zwergenpunk** [comment]
Yeah I have the same. Not sure what's happening. 

Toby did not deploy anything, and somehow it stopped working =(

**Comment by amartinsola** [comment]
Hi, we are experiencing similar problems I think. The game is #46451. Linie 4 is operating and trying to lay tile on F28 but appears a message of illegal move. But the movement is not illegal.
![7AF50816-CF8D-4931-9575-F7ABD5D535D1](https://user-images.githubusercontent.com/74565870/124581949-dc9e2100-de51-11eb-9f51-9854a33fec6b.png)

**Comment by amartinsola** [comment]
The game finally crashed: https://18xx.games/game/46451?action=138

And another one when placing a token and I suspect it is a similar problem: https://18xx.games/game/46981?action=127

**Comment by tobymao** [comment]
@Zwergenpunk isn't it because you did this 

https://github.com/tobymao/18xx/commit/8053a1ded199cb09307ce17e9380be9ce41b0727

**Comment by Zwergenpunk** [comment]
Nah its because of https://github.com/tobymao/18xx/pull/5947

This breaks nearly all games

**Comment by Zwergenpunk** [comment]
@tobymao you have to either pin or delete all those gsmes

**Comment by tobymao** [comment]
get me a list of all the games? why aren't they failing on the server side?

**Comment by McGill31** [comment]
Similar for our game 46947
We had reached stock round 2 but when I enter the game, it is back in in line round 1.1 and shows this message

We're sorry this game cannot be continued due to GameError: Blocking step Place a Token or Lay Track cannot process action 156
Broken action: { "type": "run_routes", "entity": "10", "entity_type": "corporation", "id": 156, "created_at": 1625047045, "routes": [ { "train": "Y1-0", "connections": [ [ "C3", "B2" ], [ "D4", "C3" ] ], "hexes": [ "B2", "C3", "D4" ], "revenue": 60, "revenue_str": "B2-C3-D4" } ] }
Please raise a bug report and include this link (https://18xx.games/game/46947?action=155)
