### ISSUE TITLE
1893 initial auction possible bugs

### ISSUE THREAD

**Issue by cw67q** [tobymao/18xx#5956]
Hi just starting a game of 1893 I think there might be a couple of things off in the start packet:

- 2 items FSD & KBE are priced at 190M but are both only 180M in my copy of the game (it is possible this is a deliberately change / errata)
- two different minors (EKB, KFBE) are credited with translating into the 20% president certificate of AGV. They both should be 20% but only EKB is a presidents cert.

Regards, Chris

**Comment by cw67q** [comment]
Game 48272

**Comment by perwestling** [comment]
Have now created a correction.

Weird - the 190M are from my rulebook. But it is the same version as the official online one, which do contain the 180M number? (Despite both being release 2.0)

But 180M was the price on the physical components, and in the official rulebook, so that was what was chosen.

Private text corrected.
