### ISSUE TITLE
[1893] game crashed in SR6

### ISSUE THREAD

**Issue by amartinsola** [tobymao/18xx#6111]
The following message appeared and the game crashed

We're sorry this game cannot be continued due to GameError: Blocking step Sell then Buy Shares cannot process action
Broken action: { "type": "buy_shares", "entity": 173, "entity_type": "player", "created_at": 1627114988, "shares": [ "RSE_1" ], "percent": 10 }

Game link: https://18xx.games/game/49063?action=369

**Comment by perwestling** [comment]
The game is broke as it used to allow buying shares and exceeding share limit, and this has recently been corrected.
In this case player Thistlegorm is at cert limit (9/9) so Thistlegorm cannot buy any more certs. 
As a previous version of the game did allow this the game is now broken and cannot be completed.

I suggest deleting this game as it cannot be fixed.

**Comment by perwestling** [comment]
@amartinsola Let me know if you need help deleting the game.

**Comment by amartinsola** [comment]
Sorry, I do it just now. I suppose I have simply to click on "end game", or do I have to do anything more?

**Comment by amartinsola** [comment]
Sorry, I am learning how this platform is used. I realised that you probably have a million projects you are in and its better to mention you @perwestling

**Comment by perwestling** [comment]
No worries. I think I get a notification for all issues for any comments on issues I have created or commented, without needing to do notifications. But yes, it is always good to notify just to be sure...

Yes, I think click on "end game" should be enough. If it does not work to end it, then you might need help from e.g. me to delete it (which will remove it completly). But do try it and see if it ends the game. 

BTW, I have changed 1893 to Beta. I hope the problem you noticed was an older bug so that it wont appear again.

**Comment by amartinsola** [comment]
@perwestling I’m afraid it didn’t work. I attach photo of the error message. By the way, given that you seem to be the developer of the game in the platform, I take the opportunity to thank you for making it possible to have it available to play on line. It is awesome all the work that all developers have done to make this dream come true. Specially in pandemic time, when on line gaming is more needed.

![3DFBE57F-D2AF-4F43-B4DF-FCB63CD586E6](https://user-images.githubusercontent.com/74565870/127500728-33c74868-b4a0-4f25-9171-0b2d3c3629e7.png)
