### ISSUE TITLE
1856, GT can use WRSC-ability, while WRSC is closed.

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#6158]
game: https://18xx.games/game/46748
GT bought the WSRC (ID 288).
GT uses in the brown phase the abilties of the WRSC, when companies are closed, tile 59 on I12 (ID643) and places a Marker on I12.
The GT-Token is visible on I12 before laying Tile 59.

From my understanding the rules, the abilities of the WRSC are not available, when the company is closed through Phase-changing.

**Comment by ventusignis** [comment]
I don't think this is a bug; 
https://18xx.games/game/46748?action=292
Here, GT uses the ability to put a token in the Waterloo OO hex and chooses not to lay a tile there (you can see the WSRC symbol referenced in the log to indicate the private is used)

https://18xx.games/game/46748?action=643

In the log here it doesn't show the private's symbol; here it looks like since GT already has a token in the Waterloo hex from before it can legally lay the tile without a power

**Comment by volker18xxdev** [comment]
weired. Placing a token on a yellow preprinted tile.
