### ISSUE TITLE
1870 Company share redemption does not disable auto pass

### ISSUE THREAD

**Issue by zalasta524** [tobymao/18xx#6169]
Not sure if this is an enhancement request or a bug, but I am in an 1870 game and had put on auto pass.  Prior to my turn someone performed a share redemption on a certificate I owned, shouldn’t that have disabled the auto pass as it was a direct action that affected me?  Furthermore, I am now unable to undo the pass because it will roll back everyone else that auto passed as well, which means I lost my turn to be able to buy?

**Comment by magnusrk-ch** [comment]
There's a number of scenarios here.

1) Share redemption from yourself (non-president). Clearly shenanigans.
2) Share redemption from yourself (president). Clearly not shenanigans, but also irrelevant since it can't happen while you're auto passing.
3) Share redemption from someone else. Shenanigans, since it's functionally a sale by that player, and sales are shenanigans.
4) Share redemption from market. Probably not shenanigans, but I'm sure we could come up with a scenario.

So we have three real cases, two of which are shenanigans and one maybe shenanigans. Since share redemption is limited to once per SR I think we should keep it simple and always treat share redemption as shenanigans.

**Comment by magnusrk-ch** [comment]
There's also a related scenario where a company buys shares _other than its own_ from a player. This is also functionally a sale and should be shenanigans.

I'm not sure this is actually possible in any implemented titles, but it would be easy to support as part of the same change.

**Comment by crericha** [comment]
I agree with @magnusrk-ch's proposal. It's the safer route. We can always remove scenario 4 later if people complain.
