### ISSUE TITLE
[18CZ] Game fail to load: (undefined method `each' for nil)

### ISSUE THREAD

**Issue by perwestling** [tobymao/18xx#6177]
https://18xx.games/game/50211

When trying to load game it is stuck - and the following is seen in the console:
![image](https://user-images.githubusercontent.com/2631151/128134251-6acde009-945e-4a0d-9df9-a168ebeade44.png)

**Comment by perwestling** [comment]
Sorry, 18CZ

**Comment by mb1898** [comment]
18CZ from the tournament cannot be opened again: 45723

**Comment by Tin-Whisker** [comment]
Same with game: 46612

**Comment by amartinsola** [comment]
Hi, we have experienced the same problem here, I think: the game fail to load. Game ID #48145, also of 18CZ. But I am currently playing another game of 18CZ and it works perfectly. It’s only that one.

**Comment by benjaminxscott** [comment]
These appear to be pinned now, so games should load

**Comment by mb1898** [comment]
Thank you, works again.


Von: Toby Mao ***@***.***>
Gesendet: Mittwoch, 4. August 2021 17:30
An: tobymao/18xx ***@***.***>
Cc: mb1898 ***@***.***>; Comment ***@***.***>
Betreff: Re: [tobymao/18xx] [18CZ] Game fail to load: (undefined method `each' for nil) (#6177)


Closed #6177<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftobymao%2F18xx%2Fissues%2F6177&data=04%7C01%7C%7Cc79130d469624bb754e308d9575cbe6d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636878104402541%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IY9G7jQvxHcVcPXM1JzEhya%2Bwy62AuuPp7kWTD4CmsM%3D&reserved=0>.

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftobymao%2F18xx%2Fissues%2F6177%23event-5111994302&data=04%7C01%7C%7Cc79130d469624bb754e308d9575cbe6d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636878104402541%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6P5r3omZZXV0p%2BwkeHDkKqulKC1JPe7MPNEF8aSPEEQ%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUHKRCDUN6YVTYREJQVQYALT3FMIBANCNFSM5BQMGUJQ&data=04%7C01%7C%7Cc79130d469624bb754e308d9575cbe6d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636878104412499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ed%2Bxk4zSjvtko%2BQIm5U095eXRi2gAqXyNLDB0otZ6N8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc79130d469624bb754e308d9575cbe6d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636878104412499%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VfUr8NMjyzhFv9rDm0XfOdAxcV960MM859%2F8bDoazvc%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cc79130d469624bb754e308d9575cbe6d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637636878104422453%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r16F1blQvVMwfdSgCGJCW%2BNrvW98XnCLgFZi62nIOUU%3D&reserved=0>.

**Comment by amartinsola** [comment]
Yeah, it works, thank you.
