### ISSUE TITLE
Use Done instead of Pass in appropriate places

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#63]
Currently, the button that you push to indicate that you (player or corporation) are done performing actions is labeled Pass, but this should be reserved for cases when you are really doing nothing at all; otherwise the button should be called "Done" (or maybe something even more specific like "Lay no track") so as not to imply that you're forfeiting your entire turn.

**Comment by jenf** [comment]
I'll try to pick this one up.

I'd prefer to go with the more explicit "Lay no track" style approach as I get confused what i'm passing otherwise.

**Comment by jenf** [comment]
Can see which parts of the code to change, but leaving the 'done' or 'pass' at the start makes it easier to grok rather than 'Lay no track'.

Done however suggests you have done something towards laying track
'Don't Lay Track' would be my suggestion.
'Don't Place a Token'

Since you can buy more than one train, rephrasing it slightly would work
'Don't Buy Trains' could become 'Done buying trains' if the previous action is buying trains. Same wi
'Don't Buy and Sell Shares' -> "Done Buying or Selling Shares"
