### ISSUE TITLE
Icons, starting with port icon for 1889 and 1846

### ISSUE THREAD

**Issue by michaeljb** [tobymao/18xx#647]
- 1889: render icon on port cities, replace 437's "P" with port icon, fix 437 upgrading logic
- 1846: render steamboat hexes with the same port icon, ensure the icon is still visible after tile lay (e.g., Wheeling and Toledo, also applicable for LSL in Cleveland and Toledo)

(related: #613)

**Comment by scottredracecar** [comment]
It would be nice if icons could prefer a given position within the hex instead of simply floating wherever. In 1882, there are several NWR hexes and it will look disorienting to see the icons dynamically placed in various positions within the hex rather than in a consistent location, such as on the far right corner of the hex.

**Comment by tobymao** [comment]
you can prefer locations, but it has to be dynamic and not manually stated
