### ISSUE TITLE
18Mag - Show an indication on the Buda & Pest hex to show that it has a fixed orientation

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#6506]
In this 18Mag (this is 2p), I was confused because Hex C8 is only allowed to upgrade like this, but it looks like a clockwise rotation should be allowed. It is not per the rule  "The appropriate tile must be laid onto the Budapest hex in a way that the river on the tile covers the river on the map board in the same way."

![image](https://user-images.githubusercontent.com/29106780/141159043-4150fe16-d514-45f3-826f-a685e44c3344.png)

It would be nice if there were some indicator that the orientation is fixed, such as displaying the river on that hex and maybe on the yellow tile too.

**Comment by pstone1** [comment]
A general indicator for fixed orientation tile upgrades would be useful. 18NY also has the NY Green and Brown tiles that must be oriented in a particular location that is not otherwise obvious. The physical game has a small North arrow on the tile, that as a symbol on the tile would clear up confusion in this case as well.
