### ISSUE TITLE
1830 did not deactivate autopass

### ISSUE THREAD

**Issue by misterallentrains** [tobymao/18xx#6529]
Game #62394.

I set autopass in SR3 and it did not deactivate at the start of OR3.1.  It didn't deactivate until OR4.1 started, which meant that I missed all of SR4 (and I had company starting money, too!). 

I'm not complaining, I just don't want this glitch to happen again, ha ha.

Thanks for running such a great site!
Michael

**Comment by magnusrk-ch** [comment]
Based on the action log, the following happened.

* 10407 (ConstantineXIII) has an auction action to buy NYC. Then they pass (103) and set up an auto pass (104).
* 105: 2419 (MeepleSteve) passes and 9007 (Orgak) auto passes.
* 106: 3799 (SwanofTrumpeter) passes.
* 107: 2522 (misterallen) sets up auto pass, which immediately triggers a pass, and then 10407's (ConstantineXIII) auto pass triggers.
* **At this point we're at all pass, SR is over, OR has begun. The auto action is cleared and should have produced a log message saying so.**
* **108: 2522 (misterallen) sets up auto pass again.**
* 109: NYC operates
* [...]
* No further round changes until next SR starts, and auto action is still valid.

My guess to what happened is that you
1) set up your auto action the first time
2) noticed it was not enabled 
3) didn't realize that it had immediately taken effect, triggered an all pass and then cleared itself because the SR was over 
4) set it again to fix it

**Comment by tobymao** [comment]
closing then as user error

**Comment by crericha** [comment]
I suggest we highlight the auto menu when the player has an auto order activated, so that it's obvious. Maybe change the color from black to green? Thoughts?

**Comment by magnusrk-ch** [comment]
There is a green checkmark next to Auto when you have a program enabled.
