### ISSUE TITLE
1822 autopass problem

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6626]
On action 749, AlienBishop overbid me on Minor 1. On action 751, I clicked autopass. I immediately got this message:

[07:25]-- Enabled programmed action 'Pass in Stock Round'
[07:25]-- Disabled programmed action 'Pass in Stock Round' due to 'No longer winning bids on M1'

**Comment by magnusrk-ch** [comment]
Can you add a game link?

**Comment by ChrisTheCat** [comment]
Sorry, I would have sworn I did...

https://18xx.games/game/63243?action=751

**Comment by ChrisTheCat** [comment]
<img width="747" alt="Screen Shot 2021-12-13 at 10 20 24" src="https://user-images.githubusercontent.com/8732435/145866909-e1b18040-ef32-42d8-b8c9-68092b47414e.png">

**Comment by magnusrk-ch** [comment]
The problem here is that the 1822-specific code checking for being outbid operates on the entire round, rather than per action. That means it bypasses the code that ignores actions prior to program enabling.

It seems doable to convert it to per-action checking, but this would mean only displaying the first box you were outbid on, rather than all of them. This is how it works for other programs. Would it work here too?

**Comment by ChrisTheCat** [comment]
Sure, all I want to know is "I was outbid." It's not difficult to then scan
to see which items were outbid.
