### ISSUE TITLE
18Ireland: Director allowed to pay out of hand for 6H when 1H was available in bank pool

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#6639]
Game: https://18xx.games/game/64061?action=546

There is a message about this game being pinned to version 5ed71b20e of 18xx.games.   Not sure if that's affecting this issue or not...

The director of the CBSCR was allowed to pay out of hand for a 6H train, even though the CBSCR had enough money to afford the 1H train in the bank pool.  This appears to violate rule 6.10, which only allows a director to enter emergency fund raising if the company cannot afford a train from the bank or the bank pool.  Since the CBSCR can afford the bank pool train, it should not have been allowed to enter emergency fund raising.  I consulted the general chat on this rules interpretation, and two or three folks there agreed with my understanding of this rule.  

I recognize that there is an arguable ambiguity in Rule 6.10, in the meaning of "or" in "bank or bank pool".  Does this mean that emergency fund raising is available if the company cannot afford any selected one of the bank or bank pool train?  Or is emergency fund raising available only if the company cannot afford either the bank or bank pool train?  The former interpretation does not make much sense, since the bank pool train will never be more expensive than the bank train.  

I am running Chrome on a Windows 10 box, but this isn't a technical problem, it's an implementation issue.

**Comment by dfannius** [comment]
@scottredracecar  Can you give a ruling? In short:

If a company does have the money to buy a train from the bank pool but does not have the money to buy a train from the bank, which is true?

1. The company must buy the cheap train from the bank pool that it can afford, or
2. The director can contribute money so that it can buy the expensive train from the bank.

Like @ddaybell, I would guess that the correct answer is 1, but I'd like to confirm it before changing code.

**Comment by scottredracecar** [comment]
Better to look to the designer for a ruling like that, but luckily I remembered that there is already such a reference here:
https://boardgamegeek.com/thread/1937562/article/28256271#28256271
