### ISSUE TITLE
[1889] Route creation- cannot draw legal route

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#6667]
**What's your Game ID?**
https://18xx.games/game/65326?action=382

What steps cause the unexpected behavior?

-I layed tile #205 on hex F3 with the new link going into F1.
-I tried to trace a route from F1-F3-E2-etc
-It would only let me create an illegal route, going from F1-F3 AND F1-E2
(Ignore the illegal route beyond the attempted F1-F3-E2... I took this screenshot a little later while I was messing around. My first attempt at the route was the above stated link, my the time I realized the mistake in the screenshot, I had already moved on)

![1889glitch](https://user-images.githubusercontent.com/77583169/147275466-dcc1fc14-13f0-45cb-89da-0b08651b563d.png)

**Which Browser / Platform?**
- Browser Version
Brave Browser - Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
- Platform (Mobile, Tablet, Desktop)
Desktop- Linux Fedora 34, KDE Desktop

**Comment by benjaminxscott** [comment]
I was able to repro this by clicking Saijou first, then Imabari offboard, then Matsuyama
![image](https://user-images.githubusercontent.com/1711810/147289527-9df677a1-0ea0-4640-8974-2b7bf8c9387a.png)

I don't think it's a bug though, since you can click the Imabari offboard first and then Saijou, then Matsuyama to do what you're trying to do

![image](https://user-images.githubusercontent.com/1711810/147289568-6f9eb574-d0c1-408f-a4bf-965bde846b2e.png)

**Comment by dfannius** [comment]
This looks like another instance of #2599 / #3915.

**Comment by tobymao** [comment]
closing as dup
