### ISSUE TITLE
Given option to par corporation I can't afford

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#671]
Game 1955, my second action in SR2. I have only $65 in cash, but if I click on SRR I get options to par it at $70 / $85 / $95. When I do I get a red bar saying "Cannot buy a share of SRR", but I should not be given the option in the first place to buy a certificate I can't afford.

**Comment by scottredracecar** [comment]
I think you should be offered the option, but the unavailable ones could be styled differently, such as making them a different color, red or pink for example.

**Comment by ChrisTheCat** [comment]
I dunno Scott. When purchasing regular old single shares, if I can't afford the share, the game doesn't offer me the share. Why should a presidency be different? The idea of "clean interface" means not offering players options they can't take.

**Comment by scottredracecar** [comment]
Yeah, I see both sides of this. I can live with hiding them. It would be nice if the par values were displayed somehow as well to keep from needing to reference the stock market tab, but it's not that big of a deal.

A new player might attempt to open a corp it and it either doesn't show anything or shows maybe half the options. How do they know what is going on here? At least the current interface gives a clue of what possible options exist.

I will also note that this rarely even comes up because often when a player is looking to par a company, they often have a lot of cash--not always, but often.

**Comment by ChrisTheCat** [comment]
Well, we have to think to the future when players can start companies with only 2 shares. And there are 1830 style games where people reserve presidencies.

<img width="673" alt="Screenshot 2020-06-21 11 26 32" src="https://user-images.githubusercontent.com/8732435/85232216-1d93d680-b3b2-11ea-977a-b5427812d41d.png">

I think the main issue is that the above image shows the prices for B&O shares, but not for SRR shares. Why not just list the possible par prices on the charter shown? Here's a (badly drawn) example:

<img width="673" alt="Screenshot 2020-06-21 11 26 32" src="https://user-images.githubusercontent.com/8732435/85232282-a3b01d00-b3b2-11ea-8b64-f23a35008926.png">

**Comment by scottredracecar** [comment]
Sure, when you go to par it, then that is the type of thing I was thinking. Maybe where you put 70/80/95, it says "Par Values: 70/80/95" and then just gives the legitimate current options based on the player's cash. Then that Par values text goes away after it is parred.

**Comment by ChrisTheCat** [comment]
Right, that's exactly what I was suggesting. But I want it to be visible even *before* I "go to par it." The prices for the B&O are always visible before I choose to click it to buy a share. Why not have the potential prices for unfloated companies always visible too?

**Comment by scottredracecar** [comment]
Sure, I wasn’t thinking of that. Good idea.
