### ISSUE TITLE
[18New England] Cannot run in Quincy

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#6717]
Don't have a json, but the game isn't allowing a 2T run between the large and small cities in Quincy (L7). It gives an error that a train cannot run to two cities in a hex. However, the rule is, " For hexes which have two separate *disconnected* city spaces, a route may not include both such spaces." (my emphasis) The cities are connected, not disconnected, so a train should be able to run between the two. Albany (B3), New Haven (F13), Springfield (G8), and Boston (L5) are hexes the with disconnected city spaces.

You might want to look at Lowell & Wilmington (K4) which also has connected cities in a single hex.

**Comment by scottredracecar** [comment]
I agree, this should be runnable and probably the "can't run multiple disconnected cities" code is probably messing it up. The BL minor's Boston to Wilmington works fine because they are in different hexes.

Here is a gist with both of those cases in play:
https://gist.github.com/scottredracecar/35a980940a6db2d73a321942e9d7e30d

It would be possible to run Lowell to Wilmington (within the same hex like Quincy), but that scenario is harder to construct so here is another gist:
https://gist.github.com/scottredracecar/5536a1d06ddbb61b0163c0e2b14fc5e9

**Comment by scottredracecar** [comment]
1822 has a similar hex and here is how that is handled:
https://github.com/tobymao/18xx/blob/ea871fa55767e197fd75089c54eaecaa51cd3e57/lib/engine/game/g_1822/game.rb#L1040

**Comment by roseundy** [comment]
Whoops. Forgot to check Quincy after I implemented that rule. I can use either the 1822 code or a modified version of the 1860 code.

**Comment by jtamplin** [comment]
We ran into this in a game today, and had to restart repeatedly until the GR wasn't in the initial set.
