### ISSUE TITLE
18NewEngland player colors for reservations

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#6736]
It would be nice if during the first stock round, the reserved company home tokens were color coded by player when Player Colors is turned on.

**Comment by roseundy** [comment]
Current the code only allows player colors for tokens and not reservations.  One fix would be to allow the minors to lay the home token upon formation instead of the start of the next OR. I'm not sure if there would be a functional difference.

@scottredracecar what do you think?

**Comment by scottredracecar** [comment]
RAW, the tokens are supposed to be placed at the end of the "First Stock Round." I think there is value in showing some indication of the reservation as Chris suggests, but doing this through the player color rings will be lost on a lot of people because they don't use that feature regularly.

I think Chris is mostly asking for an indication that a reservation has been placed. This came up in the game I played today. Once half the reservations are made, it is useful to visually see what is left, especially if you are not familiar with the game.

I suggest making the shading for reserved minors a different color, such as gray. Right now all "yellow" minors are shaded blue.

The player color rings for reservations could additionally be implemented, but I see that as a bit less generally useful.

**Comment by roseundy** [comment]
Proposal:
Leave the current coloring of cities the same as it is now, but color them gray when they are reserved/formed.

**Comment by scottredracecar** [comment]
I think that solves 90% of the need (understanding what is available). 

Additionally, it would be nice to have the player color rings if that is easy to add, but I don't use those generally. I think by default, they are off. So lots of people would lack this feature if this was only implemented with player color rings.

**Comment by ChrisTheCat** [comment]
Agreed, good solution
