### ISSUE TITLE
[18CZ] Stock price should not jump past end of row

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#6738]
https://18xx.games/game/67775?action=815

The rules say that when a company's token reaches the end of a row on the stock market, it does not move further.
In the game referenced above, you can see that the PR starts the turn on the 320 space,  The PR pays out, which would normally move it two spaces right.  There is only one space left on the bottom row, so the token should end there.  Instead, the implementation follows the more usual 18xx rule of moving up to the space above.  This does against the rules as written (unless I've missed a statement elsewhere in the rules).

**Comment by thepackrat** [comment]
Rules seem clear. for 100% certainty, I've emailed Lonny, then we can fix.

The problem is not jumping up, it's because the zig-zag stock market isa folded 2d, where a right is actually right then right again but non-atomically, in this case the first right jump succeeds and the second fails, leaving the token moved to the top row.

**Comment by thepackrat** [comment]
Confirmed with Lonny this is a bug
