### ISSUE TITLE
[18 New England] Unable to Simultaneously Issue Shares from IPO and Treasury

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#6783]
https://18xx.games/game/68444?action=583

BAR wants to issue an IPO share and treasury shares simultaneously, but the share price drops when issuing the IPO share before Treasury shares can be issued.

**Comment by scottredracecar** [comment]
Yes, confirmed the price shouldn't drop until after the issuing step is done. With the tabletop game, this is easy because you just grab the stack and put it in the pool. Here we have to click two or more times to pick up the shares to issue. A workaround is to issue the Treasury shares first, then IPO. The IPO will always pay the par so it doesn't matter that the stock price change happened.

**Comment by Maxwell-Frank** [comment]
I updated the implementation notes in the wiki to include the workaround. I'll let you decide whether this should be left open to be fixed or just ignored.

**Comment by roseundy** [comment]
I'll fix it (not sure how, yet).

**Comment by roseundy** [comment]
Fix is to hold off on price changes until moving on to the next step (pass) and then do them all
