### ISSUE TITLE
18Ireland stopped in OR7.1

### ISSUE THREAD

**Issue by Chrisozwa** [tobymao/18xx#6806]
https://18xx.games/game/63438

**How to Reproduce the Bug?**

The game has stopped. The current player "CaptainObi" is supposed to buy a train but will go bankrupt to dop it. Sorry...I'm not sure what else to add. 

**Which Browser / Platform?**
It seems to be common across browsers.

**Comment by magnusrk-ch** [comment]
There's a 3H' available for purchase, and the player only has to contribute 30 to buy it, but as soon as the player sells the first share the 3H' disappears as an available option.

**Comment by magnusrk-ch** [comment]
At the beginning of the train buying, UR has 120 and the president has 85. The president can contribute 30 and buy a 3H' for 150, without selling shares. It is not allowed to sell more shares than necessary, so as soon as the president sells one share it is no longer possible to buy the 3H'.

In other words, there's no bug here. We could make it less confusing by displaying an explanation for why the 3H' can't be bought rather than hiding it.

(Beyond that we can compute that it's impossible for the player to sell enough shares to buy the 10H, and thus could make it clear it can't actually be bought. In fact, don't allow selling shares at all since there's no valid way to proceed with the game by selling shares.)

**Comment by magnusrk-ch** [comment]
I looked into displaying that the 3H' is unavailable because of sold shares, but it really doesn't work with the surrounding code.
