### ISSUE TITLE
[1870] President is able to price protect shares they themselves sold.

### ISSUE THREAD

**Issue by OedipussyRex** [tobymao/18xx#6854]
https://18xx.games/game/69080?action=595

President sold shares of his own company. He was then able to price protect those shares. A player cannot buy shares of a company he sold shares of until the next Stock Round, even if it is a forced sell.

**Comment by JoeB989** [comment]
It looks like the real bug is "undefined method 'operating_history' for nil", which happened when you tried to close FW in forced stock sale.  I assume the mistaken price protect was due to messed up game state after that.  So this is essentially the same bug as #6686 and perhaps #6825.  I'll retest after fixing those.
