### ISSUE TITLE
Сonfig to disable game cloning?

### ISSUE THREAD

**Issue by nionoku** [tobymao/18xx#6855]
Can you add a config that prohibits game cloning for a more "fair" game?

**Comment by magnusrk-ch** [comment]
What's unfair about game cloning? It's available to all players equally.

**Comment by scottredracecar** [comment]
What is the game supposed to test? A player's ability to run cloned
scenarios to look ahead and make the best play? Traditionally, no, but with
an async online site, then sometimes (or even often with some players?),
yes.

It can offer a "superhuman" ability to thread a line of play that would
otherwise be practically impossible in a live play, or at least maintaining
typical etiquette suggested by many rulesets.

But I find it very unlikely this suggestion would be accepted as cloning is
essential for much of the troubleshooting that happens on the site. I
would suggest to just accept this as a downside of online and/or async play.
