### ISSUE TITLE
[1862] Flotation During Receivership Fails

### ISSUE THREAD

**Issue by Jonsered777** [tobymao/18xx#6921]
Game 68478 does not open anmore...

https://18xx.games/game/68478

**Comment by perwestling** [comment]
Internal log show:
undefined method `player?' for nil

So it is likely a bug, and it looks like 1862, so I have labeled it as such.

**Comment by roseundy** [comment]
Last legal action: https://18xx.games/game/68478?action=384

Looks like action 385 was to buy a Treasury share of FDR - which is in receivership. I suspect there is a code bug around resolving a 20% presidency when, in fact, presidencies are 30% in 1862. I'll have to dig into this more.

**Comment by roseundy** [comment]
So the unusual thing happening in this game is that the FDR went into receivership before it floated. The 5th share was bought from the treasury after it entered receivership. This caused the normal post-flotation methods to be called, but it couldn't find the active player because that code always assumed a corporation had a non-nil owner.
