### ISSUE TITLE
[18Rhl] 8T allowed to count 9 stops

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#7041]
![3BA8BEA7-B6ED-402F-8D89-5FDE6D1BC81D](https://user-images.githubusercontent.com/73144084/153031605-f785fc38-81c6-42c9-bd33-d087ed4fc518.png)

8T is correctly applying the RHE bonus and not counting dits, but is allowed to run and count more than 8 stops.

**Comment by perwestling** [comment]
Do you have a link to the game you use as an example.

Presentation might also need to be improved as towns does not count so they do not need to be shown as +X.

**Comment by BellmakerSA** [comment]
> Do you have a link to the game you use as an example.
> 
> Presentation might also need to be improved as towns does not count so they do not need to be shown as +X.

https://18xx.games/game/70978

**Comment by perwestling** [comment]
Looking at the rightmost part it looks like it should be 8+4 as 4 stops are within parantheses.
Even if it were correct calculation it sure looks like the presentation can be improved. E.g. not showing towns at all in used (so it would be 8+0, or just 8). And the doubling cities should be presented somehow. E.g. with a x2 or appended at the end.

Ah, I wrote something similar above? Well, I will look into this and maybe present a suggested look in here when I have something that work.

**Comment by perwestling** [comment]
I have now changed the presentation for "Used" so that the situation above would display as
  8 (+1)
This means 8 cities/off-boards was used, and 1 was skipped, for route calculation. So the towns passed does not show up for 8 trains.

Note, all skipped revenue centers do appear in parantheses to the right. If you count it in the included picture you can see that it actually is only 8 counted.

But there was a major bug in the calculation as the RGE bonus (that is doubling of each Rhine metropolis visited) should not have been counted unless 8 train run from RGE to RGE. That has now been corrected.
