### ISSUE TITLE
[1870] non-city tiles offered on on K/L P hexes

### ISSUE THREAD

**Issue by JoeB989** [tobymao/18xx#7059]
Tile chooser allows plain track tiles to be laid on Kansas City and St. Louis, which are P and K/L tiles.  I believe this issue crept in after the recent fix for L labels not appearing on brown city tiles on those hexes.  
![non-city tiles offered on on L P hexes](https://user-images.githubusercontent.com/97056411/153224036-967811e8-c689-48b2-80b5-0796d4c46b5e.png)

**Comment by thepackrat** [comment]
On it.

**Comment by thepackrat** [comment]
Huh. It's offering those tiles, but refusing to lay them for me.

**Comment by thepackrat** [comment]
For folks following along, there's a check that disables city-count-matching for labelled tile upgrades. This lets 1 city or 0 city tiles match as viable upgrades. Normally harmless because you have to match labels, but 1870 explicitly drops the label requirement for green and yellow tiles (which are all unlabelled) and place on the labelled hexes, which are only interesting in brown/grey which is why the bug only triggered here.
