### ISSUE TITLE
21Moon: Wording of illegal route message can be improved

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#7175]
This set of routes is not allowed as per the rules, although the error message given here implies that it is a valid set of routes.

Can the error message be altered to say something like "Must visit LB or intersect with other LB route that does"/"Must visit SB or intersect with other SB route that does"

Local game gist:
https://gist.github.com/ventusignis/abd010f927281981b5907b34ba2f3f7e
![image](https://user-images.githubusercontent.com/2993555/154149382-14758b80-6cac-4825-be97-8471ff93e023.png)

**Comment by scottredracecar** [comment]
That routing isn't legal. There is no chain of routes from the LB (the token with the drop shadow) to the blue route. The teal route is housed in the SP base, so that one also needs to intersect with the SP or the pink route.

**Comment by scottredracecar** [comment]
Also, autorouting doesn't really work in most cases in this game.

**Comment by scottredracecar** [comment]
Here is what looks like a fairly reasonable routing to me.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/29106780/154150818-62af1b2b-1419-4060-a951-de1d9eb56bc4.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/29106780/154150778-b3c6f131-6567-426b-a60d-8eaf8eba6163.png">

**Comment by ventusignis** [comment]
Thanks Scott, I've updated the ticket to instead request clarify the message in the route trains step

**Comment by JoeB989** [comment]
> Also, autorouting doesn't really work in most cases in this game.

I just stumbled on this.  Who's the 21moon dev?  I'd like to fix this.

**Comment by scottredracecar** [comment]
It's Steve. I'm sure he will be on it shortly.

**Comment by roseundy** [comment]
> > Also, autorouting doesn't really work in most cases in this game.
> 
> I just stumbled on this. Who's the 21moon dev? I'd like to fix this.

It doesn't work for the same reason it is difficult in 1860 - optimal routes cannot be found by superposition. Like 1860, routes must link. I looked at this when autorouting first was implemented and 1860 wasn't compatible with how Toby originally wrote it.

**Comment by JoeB989** [comment]
I've made some recent improvements to respect each game's check_other, and I'd like to pursue this for a bit to see if there's a solution.  The overall philosophy is that train routes can always be computed properly in isolation, the complications come in combining them.  Specifically:
1. When building individual train routes, suppress the check_other check in route.revenue
2. After assembling a test combo of routes, validate it by calling check_other on the first route in the combo (because check_other normally checks all routes)
3. At the end, after choosing the highest value combo, sanity check the combo by running the full route.revenue checks on each route

This 21moon auto-route fails on step 3.  So I have two questions:
- Should step 2 call check_other on each route in the combo?  Would you expect the results to be different?  (I tried this, and the results _are_ different - combos with 3-trains are all rejected)
- Are there other route and combo considerations beyond my simple check_other test that are passing step 2 but failing step 3?

**Comment by roseundy** [comment]
@JoeB989, perhaps this discussion should be broken out into a separate issue, since this particular bug will be closed when fixed.

- In 21Moon, check_other will look at other routes if the route it is called with doesn't hit the correct city. I don't know it that answers your question.
- I think check_other covers all the routing weirdness for 21Moon

**Comment by JoeB989** [comment]
Good point, added #7201
