### ISSUE TITLE
[1852] Saved Route does not remember how St. Louis Works

### ISSUE THREAD

**Issue by Maxwell-Frank** [tobymao/18xx#7205]
https://18xx.games/game/73507?action=384

When the route run last OR is auto-populated, the system gets...creative...with which path through St. Louis was used.

**Comment by dfannius** [comment]
@roseundy Can you copy your #5279 comment here? I think it would be more useful to respond to it in the context of this issue.

**Comment by roseundy** [comment]
@dfannius

See #7205. I would have though this fix would have addressed that.

In 7205, we have this route being reconstructed:
![18mo_route](https://user-images.githubusercontent.com/8494213/154390435-deb70384-2e76-4bb4-a821-eb9da8263abf.PNG)

The previous run serialized the nodes like this:
"nodes": [
            "J4-611-0",
            "K3-K3-0",
            "K7-K7-0",
            "J8-X3-0",
            "I7-611-0",
            "J8-X3-2",
            "G9-290-0",
            "D8-6-0",
            "C7-C7-0",
            "A7-A7-0"
          ]

The tile X3 was changed for X4, but the node numbering is the same. Node 2 connects edge 2 with edge 4. But when the route is reconstructed, it is getting confused. So I think something is wrong with the deserialization that was added.

**Comment by dfannius** [comment]
Thanks. The fix for #7205 doesn't deal with tile upgrades at all; I didn't think that there was a valid way to deal with tile upgrades because I thought that node IDs weren't consistent from one tile to an upgraded tile, so it was pointless to try to hold on to them. Is that not the case?

The current code tries to look for an exact match with tile ID and node ID. If it can't find one, it falls back to the old behavior of just using the first valid set of connecting paths. Apparently `find_pairwise_chains` considers these paths to be connected; does that make any sense?

**Comment by scottredracecar** [comment]
User was reporting it wasn't saving the route between turns, even with no upgrade laid. They needed to reclick the route each turn.

**Comment by roseundy** [comment]
Right, this is a known weakness of find_pairwise_chains. So, the deserialization of nodes doesn't help here :-(

**Comment by roseundy** [comment]
It's too bad since the node numbering is preserved through the upgrade and node deserialization is one possible way to fix this.

**Comment by dfannius** [comment]
OK, so it sounds like this is a problem with `find_pairwise_chains` that is independent of the #7205 fix and would have happened with 1852 anyway. It's good to know that node numbering is preserved, since that indeed does raise the possibility of fixing this correctly. In fact, if `full_id` in `lib/engine/part/base.rb` didn't include `#{tile.name}`, it might just work as is.

**Comment by roseundy** [comment]
The problem is that there are tiles that have rotational symmetry, so just because it works here, it isn't a general solution.

**Comment by roseundy** [comment]
I think there still might be an issue with node deserialization. When use the "Show last route" feature, it's still wrong.

**Comment by dfannius** [comment]
OK, I'll take a look at the Show last route behavior for St Louis in 1852 tomorrow.

**Comment by dfannius** [comment]
When I try to look at MP's old route, `@saved_nodes` is `K5-611-0,K3-K3-0,K7-K7-0,J8-X4-0,I7-51-0,J8-X4-2,G9-290-0,C13-611-0,A15-A15-0`; note the two instances of `J8-X4`. So when `OperatingInfo` calls `Route.nodes` when serializing the route, apparently the existing chains already reference two distinct nodes on the St. Louis tile (which should not happen, of course).

**Comment by roseundy** [comment]
Wow, completely missed that!

**Comment by roseundy** [comment]
Which begs the question, how did that serialization ever get there?

**Comment by roseundy** [comment]
One of the fundamental issues I discovered is that find_pairwise_chains is not robust for tiles that have multiple nodes (cities/towns) connected to the same edge.

The upshot is that there are two changes required:
- Use :nodes instead of 'nodes' when serializing
- Allow previous run's node indices to be used even after a tile upgrade
