### ISSUE TITLE
1852 - Do not allow token private company to teleport

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#7219]
The basic implementation of the "half price token" private company allows the corporation to teleport it. This token should only be able to be placed if the corporation has a route to the slot.

**Comment by OedipussyRex** [comment]
Seems harsh. High cost, low revenue, with high long-term risk on value of share acquired. Mail Contract sticks around the entire game providing positive value, the private railroads provide a $100 train short-term, and an extra $80 token long-term. But the possibility being stuck with a share paying $100 less a round and worth $200 less than another share I could otherwise have been able to buy? I'll pay the $5/$10 to skip the private.
