### ISSUE TITLE
[1852:Mizzou] Drop removed corp ability tokens at game setup (was: Can’t upgrade St Louis)

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#7221]
In game 73472, the St Louis tile won’t upgrade to green. There is a small blue token on the tile and every token spot is taken, so it seems like there is an issue in resolving that reserved spot.

The error that comes up is “No implicit conversion from NilClass Into Integer.”

edit: I had the game number wrong.

**Comment by roseundy** [comment]
Game id? Action?

**Comment by SmithInMN** [comment]
> Game id? Action?

Sorry, I hit submit accidentally… I was just editing the comment.

**Comment by scottredracecar** [comment]
SSW is one of the removed corps on game setup here. Its reserved teleport ability is correctly removed, but that mini logo shows up for some reason I do not understand. I don’t know why the 46 code would diplay that as I can’t recall a mini logo like that coming up in 46.

**Comment by SmithInMN** [comment]
We just got to the first 7 train and the game log says that reservations have been removed...  and yet that small SSW token is still there and we still can't upgrade StL.

**Comment by scottredracecar** [comment]
I think what is happening here is that the small SSW logo is representing the extra token that will drop in with the green tile per the 1846 2-player rules. But since there is nowhere for the token to drop into, the tile is not allowed to be upgraded.

I will need to add a rule for this case.

So the additional rule is:

If there is no slot for the ability token to drop to, the token is removed.

**Comment by scottredracecar** [comment]
Updated my above posts.
