### ISSUE TITLE
Corporation playing order wrong (GameID #75)

### ISSUE THREAD

**Issue by Spobster** [tobymao/18xx#73]
At the start of stockround 6, Takamatsu's stock value was 70 (bottom), Sanuki 75 and Tosa Electric at 80. All above each other. Order of selling:
Sanuki sold: drops to 70
Tosa sold: drops to 75
Tosa sold: drops to 70
Takamatsu sold: stays at 70.
At the start of the next operating round (6.1), the playing order is Sanuki, Tosa E., Takamatsu. While Takamatsu should have been first, isn't it?

**Comment by dfannius** [comment]
Yeah. I presume that when an attempted token move is made, the token is put at the bottom of the stack of the square in the stock market that it ends at, even if that move was a no-op because it's at the floor of the stock market. It should only sink to the bottom of its stack if it has actually moved.
