### ISSUE TITLE
Add percentages to more games

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#7335]
18GB, 18CZ and possibly other games show the percentage owned, which is useful for 5 share, 10 share companies and similar.

https://18xx.games/game/74811?action=277#entities

<img width="344" alt="Screen Shot 2022-02-26 at 09 43 47" src="https://user-images.githubusercontent.com/8732435/155853580-032b8f47-3dbd-4190-b780-d81acb783eac.png">

It would be nice if this was implemented in other games with variable percentage shares, like 1817.

**Comment by andypymont** [comment]
I checked and currently only 18CZ and 18GB set `SHOW_SHARE_PERCENT_OWNERSHIP = true`.

I believe Ryan is looking into 18CO already, so the main games that could potentially benefit from this are the 1817 family:
- 1817
- 1817NA
- 1817WO
- 1877
- 18DE

I'll clone some live games and see how it looks in these games if this constant is set.

**Comment by andypymont** [comment]
Here's what it would look like in 1817 - does this look clear? Especially given the existence of shorts?

![image](https://user-images.githubusercontent.com/8403378/155981445-0bdb7495-bf58-49ba-a3c5-58e07a6b9856.png)

**Comment by slapphappyjazz** [comment]
I was the person who originally requested this for 18CZ, following comments from other players in my local group when we played 18CZ online.  With the different sizes of companies (4-share, 5-share and 10-share), some players found it difficult to track the percentage ownership.  By contrast, the physical certificates do have this information.
It only benefits games where companies have different numbers of shares.  I'd have thought it would benefit 1817 but you'd need to try it.
I think other games with a 20%/10% conversion include 18Ardennes and 1858.  Possibly also 18VA but I haven't played that.

**Comment by ventusignis** [comment]
This may be a good case for making a module and having games that want this behavior include it, like the standard "plus train" stop counting

**Comment by andypymont** [comment]
> This may be a good case for making a module and having games that want this behavior include it, like the standard "plus train" stop counting
This has been done - there's a constant, `SHOW_SHARE_PERCENT_OWNERSHIP` - which can be set to true and the UI code will then reflect this as I've shown above. I assume this was done by the 18CZ dev - it's a great change which made this easy to apply to other games, but I don't think it was then reviewed if any existing games could benefit.

I'm with @slapphappyjazz in that I agree 18CZ is far more playable with this change. I then included it in 18GB because I felt it also made it easier in that game to see where you owned differing amounts in different 5-/10-share corporations.

Chris then saw this in 18GB and asked (by raising this issue) whether it could be rolled out to other games. It can be done easily from a technical POV, but the question is more whether it is the right change for players of those games.

I'm not an 1817 player so I can't really comment authoritatively on whether or not it'd be a good change for those games. It'd be great to hear from those who do have a strong opinion either way.
