### ISSUE TITLE
21MOON: Blocking step Run Routes cannot process action 91

### ISSUE THREAD

**Issue by soulyogurt** [tobymao/18xx#7371]
(https://18xx.games/game/73678?action=90)

I’m iOS on an iPad Pro, Safari, but the error was there when I opened the game.

**Comment by roseundy** [comment]
This game should have been archived due to a bug fix.

@tobymao can you pin or archive this game?

**Comment by roseundy** [comment]
https://18xx.games/game/73749 is in the same boat.

**Comment by l33twash0r** [comment]
We're sorry this game cannot be continued due to GameError: Blocking step Run Routes cannot process action 64
Broken action: { "type": "pass", "entity": "LP", "entity_type": "corporation", "id": 64, "created_at": 1645553613 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/73447?action=63)


Same for this game as well
