### ISSUE TITLE
18USA Broken Loans Bug

### ISSUE THREAD

**Issue by Narvinyar** [tobymao/18xx#7381]
We're sorry this game cannot be continued due to GameError: Blocking step Take Loans cannot process action 578
Broken action: { "type": "lay_tile", "entity": "SLSF", "entity_type": "corporation", "id": 578, "created_at": 1646356691, "hex": "G3", "tile": "X11-0", "rotation": 3 }

**What's your Game ID?**

https://18xx.games/game/75088?action=577

**Comment by crericha** [comment]
Obsolete trains were incorrectly counting against the train limit, which caused UP to automatically pass on the buy trains step. Now that that bug is fixed, UP still has a possible train action (the 3+ doesn't count anymore), which has caused the game to get out of sync. I will look into trying to restore the game.

**Comment by crericha** [comment]
Sorry, I was unable to fix your game. There were more issues than just the one I mentioned above.

**Comment by Narvinyar** [comment]
Thanks Chris, no problem! We'll just start a new one and see what else breaks this time.
