### ISSUE TITLE
18USA - company still exists after liquidation (IC was liquidated)

### ISSUE THREAD

**Issue by edfactor29** [tobymao/18xx#7411]
Game ID 75424

https://18xx.games/game/75424

After the IC was liquidated I do not see any settles with shareholders line. the company and all its shares and shorts still exist.

**Comment by edfactor29** [comment]
Update
Apparently this happened in the previous M&A  (M&A 4.1) round with the MP also.
In M&A 4.2 MP was liquidated again and it actually went away (after running for 0) IC was liquidated and it still exists, presumably will disappear after running for 0 and being liquidated in M&A 5.1 maybe

**Comment by crericha** [comment]
Companies are liquidated if they do not own a train at the end of their operating turn. In OR 4.1, the IC had a 3T and in OR 4.2, the IC had a 4T and pullman. Since it had a train at the end of its turn in OR 4.1 and O4.2, the IC is still in acquisition and not liquidation.

If I missed something, please reopen the ticket with what I missed.
