### ISSUE TITLE
[18NY] Purchasing minors at any point during an operating round

### ISSUE THREAD

**Issue by shamblen** [tobymao/18xx#7433]
In the rules of 18NY, companies are allowed to initiate mergers or takeovers at any point during their operating turn; currently in the implementation, they are only allowed to do so at the end of their turn.

In the game
https://18xx.games/game/74912
the current player planned on buying in M8 before the train-buying step in order to afford a new train, but the game is only giving him the option to do so after the train-buying step.

**Comment by crericha** [comment]
The 18xx.games engine does not support anytime actions, so it would be a significant effort to allow mergers anytime. 

I spoke with the designer, and based on his plays of the game, he believes that end of the OR is sufficient for the online implementation.

I don't have any plans to resolve this issue at this time.

**Comment by shamblen** [comment]
Hmm, okay.  What makes this different from, say, taking a loan in 1817 or buying in a private company in 1830?  Those would appear to be "anytime" actions.

**Comment by crericha** [comment]
To answer your question, taking loans, is a button, so that's easy and private companies are purchased in almost every game, so it provided a high amount of value for the effort.

Regarding this bug, the designer believes buying a minor is rarely seen before end of turn and it would only be useful to this game, so the value vs effort isn't there. If I was going to do anything, I'd design a generic approach to making anytime actions, but I don't have the time for that currently in my life.

**Comment by shamblen** [comment]
Thanks for the clarification.  Makes sense, I see where the difference is.  And certainly understand the lack of time...

We've backtracked in the game so the player could account for the option not being available.  For what it's worth, this action is something I've seen in a couple of times in face-to-face 18NY games, where a minor company has a bunch of cash, and the major company wants to buy in the minor early in order to use that cash to buy a train.
