### ISSUE TITLE
Seed specification not functional.

### ISSUE THREAD

**Issue by ryandriskel** [tobymao/18xx#7465]
The game json has the specified seed, but it is not loading the same information on new game creation. Despite using the same seed, I am getting different random shares for the random share ability.

**Comment by perwestling** [comment]
Would still be useful for games that have random setup, especially to try combinations.

**Comment by ryandriskel** [comment]
Oh, I absolutely want to get it working. It just involves a migration that touches many games and I don't have the time available to do it right now.

**Comment by michaeljb** [comment]
I've done a little bit of tinkering on this in https://github.com/michaeljb/18xx.games/commit/7faa51f663ba750451dd1b76bfc5ee26b98ecbfe, including adding a helper function [`find_seed`](https://github.com/michaeljb/18xx.games/commit/7faa51f663ba750451dd1b76bfc5ee26b98ecbfe#diff-e4498b81a5214647340858fb4072f6062e6a60d1de2bebbebe9b61662559dfbb) to find a random seed that meets arbitrary specifications.

In the current implementation, the `seed` stored in a game's `settings` in the DB is used for determining initial player order and nothing else, so I think the seed specification is functional for at least that small piece - https://github.com/tobymao/18xx/blob/7f59be3f4bb10a1ad663744aeee34b7fb09d3499/models/game.rb#L116

The game ID actually ends up as the initial `@seed` value - https://github.com/tobymao/18xx/blob/622a8d41e6c277c391d2c088d69ee59386c5259f/lib/engine/game/base.rb#L509

In my commit the `seed` is used for both, but doing that breaks all old games where their numerical ID was actually their initial `@seed`, so I tried moving `seed` to `legacy_seed`, and for only the player ordering step, prefer `legacy_seed`. That gets most of the tests to pass but there are still some failures, noted in the commit message (and I didn't check in the migrated fixtures).

Another to thing to consider is that games cloned from multiplayer games before the `legacy_seed` migration is applied will break, they copy the `seed` value but use the ID, so they'll be out of sync.

----

I'm probably putting this down for now, but wanted to dump my thoughts here before I abandon. A slightly different `find_seed.rb` has still been useful for me on #9211 (returning the game ID instead of `game.seed`).
