### ISSUE TITLE
18CZ Vaclav - running trains

### ISSUE THREAD

**Issue by pzieske** [tobymao/18xx#7532]
The rules state the Vaclav's companies must run for maximum and pay dividends, but in the game, the player running the company may choose not to run train which should be prohibited.
p. 23: "Running trains: Vaclavs companies run their trains for maximum and always pay out."

**Comment by Zwergenpunk** [comment]
This is true for alot of games like 1846 etc. 

This is a little bit different because the operator does not benefit. But to enforce the maximum is impossible and enforcing > 0, while possible, does not improve the situation.

I'm sorry to close this, but I'm 99% sure this will never be implemented.

**Comment by dfannius** [comment]
I will just add that the general way to deal with this sort of issue on the 18xx.games site is via chat and undo, which I know is not ideal but is better than nothing.

**Comment by pzieske** [comment]
Okay, I thought this could be programmed into the game.
Paul
