### ISSUE TITLE
Race condition with undo

### ISSUE THREAD

**Issue by KevinR1000** [tobymao/18xx#7621]
See actions 300-303 here https://18xx.games/game/77564?action=306

300: User 2336 did pass at epoch 1649886064.
301: User 2336 did undo at epoch ..079.
302: User 8054 did pass at epoch ..080.
303: User 2336 did buy_shares at epoch ..084.

So, for display and game purposes, the actions appear out of order.

It might be worth confirming that this is close to spec.  I'm slightly surprised that action 302 didn't get rejected on submission (I saw no topbar warnings/errors as user 8054).

But preventing a race condition is likely to require a major refactoring with minimal benefit.  I expect this report to be unresolved.

**Comment by tobymao** [comment]
there's no race condition here, from the perspective of the code, it handled it well and your action was legal, it may not be what you wanted though because a player undid something right in front of you. the game engine will never allow an illegal move and there's a lock on the DB so that we can never have a true action race condition
