### ISSUE TITLE
18USA - cash subsidy

### ISSUE THREAD

**Issue by edfactor29** [tobymao/18xx#7677]
when a cash subsidy is used to start a company if the player puts in to much from private companies from their hand - excess cash is being put back in their hand from the subsidy. Any extra cash should be going to the bank. 

The rules example:
The new company’s treasury would receive $30 from the bank and the $76 in equity from the player.

- the subsidy cash is never actually in the players hand it goes from the bank to the company - and any excess should go back to the bank.

**Comment by crericha** [comment]
@edfactor29, what I'm hearing is something like:
- The player's winning bid is 148 on a city location with a $30 subsidy
- The player contributes 140 worth of privates
- The player gets back 8, but since the $30 subsidy was used, it should go to the bank instead?

If that isn't correct, can you please walk me through an example because I'm not quite getting it.

I know you are one of the designers, so I'm sure you're right, but I don't see anything in the rules to support the example I have above. What I see in version 1.4 is:

> The $30, $40, and $50 subsidy bonuses are treated as additional cash in a player’s hand for starting a company in the
> cities which are offering the subsidies. For example, if Portland has a $30 subsidy, a player may start a company in
> Portland at $106 (resulting in a $53 share price) using $76 in equity from their hand and the $30 city subsidy. The new
> company’s treasury would receive $30 from the bank and the $76 in equity from the player.

There isn't anything I can find that says private value first comes from player cash and then the subsidy. Is there errata somewhere I can reference?

**Comment by crericha** [comment]
"a:" is very clear. For "b:", I recommend adding something like "The player must contribute the non-subsidy amount in cash and/or privates and any unused subsidy cash is returned to the bank."

I'll make the code change on the site. Hopefully it doesn't break too many games.
