### ISSUE TITLE
1822 games: loans may be partially paid, player option (not just because they don't have enough to pay it off entirely)

### ISSUE THREAD

**Issue by AlejandroPrudente** [tobymao/18xx#7688]
This was discussed and implemented the current way on purpose but (#4731) 4.3.2 allows for partial payment and doesn't add any qualifiers.

**Comment by michaeljb** [comment]
[Relevant rules are on page 9](https://boardgamegeek.com/thread/2100280/article/30562663#30562663):

> 4.3.2 After their “sell shares” step, a player may make a payment on outstanding loans. This may be for the full amount or a partial amount. The money is paid to the bank.
>
> 4.3.3 A player is not obliged to sell shares to raise money to pay off loans.

The current implementation allows for paying either $0 off or as much as possible, with no in-between. A player may want to pay off part of the outstanding balance but keep some cash on hand in order to fund a Minor acquisition and gain more shares of their Major. [Comments from the designer in 2018 supporting this tactic](https://boardgamegeek.com/thread/2100280/article/30562663#30562663):

> I've never done it, but I think the rules allow you to sit on both cash and loans during an SR, so you don't have to pay off a loan just because you can. You could then use the cash in a subsequent OR to fund acquisition shares. Of course the loan interest makes this strategy rather too expensive to be viable. I haven't read the rules just now to check whether this is true or not, but it was my intent. 

----

I don't plan to implement this immediately, but I have some thoughts after looking at the code for a little bit:

The `payoff_player_debt` action currently does not support an amount, nor does the stock round view. 1866 and 1880 also use the `payoff_player_debt` action, so something will need to be added to the game class to support paying off an arbitrary amount in the 1822 family without affecting the other games, and ideally the engine will still support not having an amount on the action so that old 1822 games don't break.
