### ISSUE TITLE
1822 - P2 (Remove Town) and P11 (Advanced Tile Lay) cannot be used in combination

### ISSUE THREAD

**Issue by brianbirmingham** [tobymao/18xx#7709]
https://18xx.games/hotseat/hs_suvbkioa_81239
In this hotseat game, the Minor Company 14 has acquired P2 and P11, and is trying to use them to remove Hertford.  This appears impossible, since only one or the other can be used at once, preventing the town from being removed, since it requires both minors to be used in combination.  According to the rules, both powers should be able to be used together, but there does not appear to be a way to do so.

From page 7 of the [1822 rules](https://boardgamegeek.com/file/download_redirect/a9bebac70f8d040f147e5ded650b69db43a347ee1e05e92f/1822+Rules.pdf):

> EXAMPLE. The left and center diagrams show that the SECR has used the powers of private company P11 to place plain
> brown track before Phase 5, and has also used the powers of private company P2 to upgrade a green tile with a small town to
> a plain brown track tile with no town. The tile replaced is highlighted in diagrams. 

![image](https://user-images.githubusercontent.com/71911016/167277336-5d20ca93-758c-4a2e-ba6d-e557077afad9.png)

As near as I can tell the only difference between the game link and the rules example is that the game link is a minor doing the upgrade to green before phase 3, while the rules example is a major doing the upgrade to brown before phase 5, but I can't see any reason why that difference should matter.

Thanks for the great game!

**Comment by magnusstjarnhild** [comment]
Thank you for you issue. It is a know issue and have been reported a few times. Orginal issue is #4469 and it is still open. Like you said, if you push one private it will unselect another if you have it selected, this is the problem and would require a big rewrite of the core code to handle it. And so far none have been intrested to do so.

I will close this since its a duplicate.

**Comment by magnusstjarnhild** [comment]
Thank you for you issue. It is a know issue and have been reported a few times. Orginal issue is #4469 and it is still open. Like you said, if you push one private it will unselect another if you have it selected, this is the problem and would require a big rewrite of the core code to handle it. And so far none have been intrested to do so.

I will close this since its a duplicate.

**Comment by brianbirmingham** [comment]
Thanks for the explanation!  It ultimately didn't affect our actual game, though we thought it might at first.
