### ISSUE TITLE
[1822+] Bids Disappeared mid SR

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#7730]
All bids disappeared during SR6

Game ID 82806

Game state immediately before bids disappeared: https://18xx.games/game/82806?action=484
Game state immediately after bids disappeared: https://18xx.games/game/82806?action=485

Edited to add: bids re-appear after Master Mode pass by player up at action 485 - this player is currently in debt and has no bids, in case that is relevant

**Comment by magnusstjarnhild** [comment]
Thank you for the issue.

This is a known "problem", it is because the player has a loan that the bids dissapears. There is a text on this issue in the wiki [https://github.com/tobymao/18xx/wiki/1822](url) under Known Problems.

`During SR, if the active player is in debt, the bids done on privates and minors are not shown. They will appear again when a non-debt player becomes active.`
