### ISSUE TITLE
18USA Company Town 

### ISSUE THREAD

**Issue by chanmancan** [tobymao/18xx#7735]
https://18xx.games/game/79838

https://18xx.games/game/79838?action=313

In game 79838, a company other than the owner of the CT private was able to place a token in the CT station circle, though this is not the intent of the rules. See 2nd paragraph, pg 23, for private 27 in the newly released AA copy of 18USA rules.

**Comment by benjaminxscott** [comment]
Looks like the UP used Free Station to lay on Company Town's tile

To me it's not entirely clear whether this is allowed, looking at these rules

https://boardgamegeek.com/filepage/238949/18usa-rules-all-aboard-games-2022

Free Station says "can lay on any tile", but Company Town says "no other corp can lay on this tile", not sure which one takes precedence

**Comment by crericha** [comment]
@edfactor29, legal or no?

**Comment by edfactor29** [comment]
Ok I think that is something that slipped by us during playtesting. 
It should probably read "no other regular station may be placed on the CT" 
but in the case of a suem and wynn type station, only the owner of the CT would get the full value of the city, everyone else, should still get the -10.  And the -10 station cannot be occupied.

**Comment by chanmancan** [comment]
In this case, perhaps consider allowing the private company to remain on the company after the CT is placed for an easy indicator of who the CT private was owned by. Or maybe some icon o. The station itself.

**Comment by crericha** [comment]
Okay, so you can place a station, but its still -10? The station would be for routing only?

**Comment by edfactor29** [comment]
Yes that is correct, the station can go there, but it doesn't coopt the CT ability to generate a little extra revenue.

**Comment by chanmancan** [comment]
Hi, was looking to see about connectivity for the last firm private and found this. 



The thread is here.

https://boardgamegeek.com/thread/2001571/may-i-ask-about-102-private-companies-rules-14

**Comment by crericha** [comment]
@edfactor29, according to the thread @chanmancan found, Shawn ruled you get full value for the company town (at least how I read it). Would you be able to confer with Shawn to make sure you guys are in agreement before I make this change?

![image](https://user-images.githubusercontent.com/67359577/170633842-86467191-7c51-4f2e-b95b-91da8d0b3861.png)

**Comment by crericha** [comment]
@edfactor29 please check my comment above from May 27th. I'm hoping you can talk to Shawn and let us know what the correct implementation is. We got different answers from you and what Shawn has posted.

**Comment by crericha** [comment]
Looks like this issue is dead. Feel free to reopen if the above rule disagreement is resolved.

**Comment by ryanrozy** [comment]
[https://boardgamegeek.com/thread/1965150/article/28656647#28656647](url)
From Shawn Fox:
<img width="2428" height="302" alt="Image" src="https://github.com/user-attachments/assets/d9451ade-ab34-41af-8580-7419ba7390d6" />

[https://boardgamegeek.com/thread/2001571/article/29196727#29196727](url)
From Shawn Fox:
<img width="2452" height="740" alt="Image" src="https://github.com/user-attachments/assets/994ccb66-5b05-4de0-b53f-61eb41185d6a" />
<img width="2444" height="268" alt="Image" src="https://github.com/user-attachments/assets/057bf220-5123-4ece-b051-1b6730573e68" />
Per BGG forums, Shawn Fox above on the March 2018 FAQ and again in a May 2018 Q&A, can't use Suem & Wynn private to token Company Town tile. This restriction would presumably extend to the free station subsidy as well since Shawn Fox immediately states in the second link that the Suem & Wynn Law Firm and the free station subsidy work identically except that the subsidy gets a free token.

[https://boardgamegeek.com/thread/2828507/company-town-can-other-companies-run-and-build-thr](url)
<img width="2668" height="714" alt="Image" src="https://github.com/user-attachments/assets/ceaf1a55-042e-4095-b231-d8ae712a6f6b" />
^In March 2022, Shawn Fox states that no other company can token the Company Town tile according to the written rules.

**Comment by ollybh** [comment]
@ryanrozy How does this differ from the rules implementation on 18xx.games? What needs to be changed? I don't know 18USA at all.

If there are changes that need to be made please reopen this issue.
