### ISSUE TITLE
Add an auto command for auctions

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#7750]
Allow a player to set a max bid and increment for any auction of a single item.  E.g. when two or more players have bid on a private in an 1830-style auction, a player could specify increment a bid by $5 until a maximum of $160 (or whatever).  The same process could be used for bidding on a acquisition or launching a new corporation in 1817.  

Auctions are one of the more boring aspect of any 18xx game, and they're even more boring when done in an async game.  Speeding them up would be a boon.  

This probably wouldn't work for simultaneous auctions as in 18Neb and 18GB, nor for the mechanism in 1848 Australia.  A similar mechanism might work for the dutch auction in 18EU, but I expect that would have to be coded specially.

**Comment by damerell** [comment]
I was thinking about this during a 12p auction round. I'd propose that such an option would be more useful if the player could set whether they should pass when outbid (because they put in their absolute maximum) or not (because they put in the point at which they want to seriously consider the situation).
