### ISSUE TITLE
[18USA] Perhaps a problem starting companies

### ISSUE THREAD

**Issue by BlackMarmote** [tobymao/18xx#7850]
In the game https://18xx.games/game/82814, I have just started ATSF and I had not the option to use privates as part of the starting capital. This created a strange situation, where I have negative cash.

**Comment by crericha** [comment]
Definitely a bug. Since there is no combination of privates that can be used to pay the bid, without going over the bid value, the game gets confused.

You do not need to wait for a bug fix to continue your game. Just back up and change the bid to a valid value that allows for the ATSF bid to be paid for by privates without going over the bid value (and doesn't result in negative cash).

Meanwhile, I will fix the bug. Thanks for reporting.
