### ISSUE TITLE
[RSS] Auto pass in investment phase

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#7934]
When a player does not have enough cash to purchase a private and does not want to sell their company shares, it would be nice if they could auto pass.

**Comment by roseundy** [comment]
Now that I'm trying to implement this, I remember why I didn't add it originally: the base game code assumes that there is only one programmed action per entity instead of a list. Because we need auto-passing on the Close Company phase persists from round to round, trying to set auto-pass on the Investment phase breaks this.

This can be fixed, but it will require a much larger re-factoring effort than I'm prepared to do right now.
