### ISSUE TITLE
18moon does not enforce track lays on behalf of base after tab change or browser refresh

### ISSUE THREAD

**Issue by johnplanow** [tobymao/18xx#8010]
**What's your Game ID?**

https://18xx.games/game/87824

See SM's operating turn in OR 3.2

**How to Reproduce the Bug?**

Map at the start of SM's OR 3.2 turn:
<img width="751" alt="Screen Shot 2022-06-25 at 12 41 07 PM" src="https://user-images.githubusercontent.com/20933061/175786908-c7108da5-1836-46f3-bbd5-9775ffdb1006.png">

Map after J2 tile lay on behalf of SM's LB. Note that the game correctly prevents another tile lay in the northeast area because SM's SP doesn't have a route to there:
<img width="679" alt="Screen Shot 2022-06-25 at 12 41 29 PM" src="https://user-images.githubusercontent.com/20933061/175786937-d944f41e-dcae-4ab0-9f39-84e7528b130f.png">

Map after refreshing the browser. Now the game is NOT preventing a tile lay in the northeast:
<img width="662" alt="Screen Shot 2022-06-25 at 12 41 47 PM" src="https://user-images.githubusercontent.com/20933061/175786946-ac8cd209-2599-46f9-b21e-2ffe6486a68d.png">

**Which Browser / Platform?**
Chrome desktop browser version 102.0.5005.61 (Official Build) (x86_64) on MacOS

**Comment by roseundy** [comment]
Yowsa! This is going to require a much more involved fix than I originally thought.

The straightforward fix hurts performance because it requires building a graph even when loading in order to see which base was built off of. At the moment, I'm not sure how to do this in a way that doesn't slow things down.

**Comment by roseundy** [comment]
This will come up again in 1841.

I'm thinking I will need to add an information-only action that indicates which graph was used for a tile lay. This will be similar to the auto-action added when creating a route between corporations for mergers. It will be different since will be a brand new action, rather than a auto-pass.

**Comment by roseundy** [comment]
The alternative is to add a new piece of information to the lay_tile action. That might be cleaner - but more invasive.

**Comment by roseundy** [comment]
I'm going with the first approach - a new auto-action that indicates which base a new tile connects to.
