### ISSUE TITLE
18SJ E-train issue

### ISSUE THREAD

**Issue by woodfeld** [tobymao/18xx#8067]
The OKJ has an E-train but cannot run through the national tokens like it should be able to. Game ID - 88283

**Comment by dfannius** [comment]
https://18xx.games/game/88283?action=596

**Comment by perwestling** [comment]
Can you be a bit more specific, @woodfeld?

When I entered the game, navigated to action=596, I could specify a route through Ånge, which is due to the SJ token.
Possibly it might be that you need to refresh.

![image](https://user-images.githubusercontent.com/2631151/178438208-617c2358-584a-4322-892f-b6d8baef3411.png)

**Comment by woodfeld** [comment]
Thanks for reaching out Per.  It looks like Dan fixed it.  After he
replied, I was able to go in and run the E-train as intended.
Thanks
Jerry

**Comment by dfannius** [comment]
I didn't do anything but identify the action in question! But I'm glad it's working now.

**Comment by woodfeld** [comment]
Ha!  No idea what happened then because I tried exiting and getting back in
and that didn't solve anything.

**Comment by woodfeld** [comment]
Side question to same game - should you be able to upgrade a non-Stockholm
city with the Stockholm gray tile?  You can see it in our game that it was
ok, but the rules seem to state it's reserved only for Stockholm.
Thanks
Jerry

**Comment by perwestling** [comment]
@woodfeld I think the rules are correct and the implementation is incorrect. Good catch, I will create an issue for it.
