### ISSUE TITLE
[General] Add timeout to new games

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#8091]
Many proposed new games are hanging about for months unstarted. Can we have some sort of time-out? I would suggest 1 month.

**Comment by kevind1402** [comment]
Great idea!
If we want to be kind, the system could automatically notify the owner, e.g. after 2 weeks.

**Comment by ianwilson156** [comment]
Good thought. 
I suspect they end up unstarted either because the creator has lost interest in playing online, or because they took too long to fill up.

**Comment by kevind1402** [comment]
Agreed.
For the ones I'm looking at on 18Chesapeake (e.g. 80247, 82970) I suspect the former i.e. creator has lost interest, because I see these games fill up, people wait a few days, get bored and leave, repeat .... I've seen about 10 different people go through this cycle, just in those 2 games, which adds up to a lot of frustration and wasted time.

Notifying the owner would be a courtesy, and then if they don't respond within time the game gets deleted automatically. Maybe if they are genuinely waiting, then they can refresh the game & reset the counter.
But if they have lost interest or left the site for any other reason (even valid ones), the system needs to be able to clean up from time to time.

**Comment by ianwilson156** [comment]
This doesn't seem to be working any more! There are several games left hanging unstarted for about 2 months atm.

**Comment by kevind1402** [comment]
This feature is not working currently.
Several games have been left hanging for many months, e.g. 233003, 225368, 225367
I would re-open it but I don't have permission to do so
@tobymao
