### ISSUE TITLE
[1856] GameError cannot continue 89363

### ISSUE THREAD

**Issue by serpentium** [tobymao/18xx#8238]
We're sorry this game cannot be continued due to GameError: Blocking step Place a Token cannot process action
Broken action: { "type": "destination_connection", "entity": "LPS", "entity_type": "corporation", "created_at": [1657076861](tel:1657076861), "corporations": [] }

(https://18xx.games/game/89363?action=321)

**Comment by ventusignis** [comment]
I'm not sure what's happening here, but it's hard to help since it's a pinned game - 

I created a local environment where I removed the changes that took 1856 to production (causing games to get pinned) and cloned the entire game - the game errored, but only much, much later around step 1400 - it looks like a double undo was registered causing the game to fall out of sync:
ROUTE_TRAINS
DIVIDEND_CHOICE
UNDO
UNDO <-- duplicated undo - likely due to lag +- double clicking
DIVIDEND_CHOICE

I tried to reproduce the error that the pinned game is complaining of (blocking step on action 321) but that action is working fine

**Comment by dfannius** [comment]
The game is pinned so I expect that there's nothing to be done about it (if a fix were deployed the game wouldn't even have access to it).

**Comment by ventusignis** [comment]
The game was archived so there's nothing more that can be done in this case without it being reproducible
