### ISSUE TITLE
[1848] Info page should mention discounts for diesels

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#8261]
The info page for 1830 notes the discount in the price of a diesel for upgrading a train.  The info page for 1848 doesn't mention this.

Yes, I know I ought to read the rulebook, but I often rely on the info page instead!

**Comment by andrewzwicky** [comment]
This is happening because the discount is only at the variant level, instead of for the whole row: 

https://github.com/tobymao/18xx/blob/4a46375a76ca52f067e00a7e592df8d469154183/lib/engine/game/g_1848/game.rb#L273-L288

It might be easier to split up the two rows, which might also just be clearer in general.  The problem if that happens is that the `available_on` might be weird because the 8 & D both become available at the same time (after the last 6/6+ is purchased).  I'm not sure if adjusting the trains to become available at the same time, or if the adjustment to the info page to detect variant discounts would be easier.

**Comment by andrewzwicky** [comment]
Oh I misread the rules, you can get the discount for both 8/D, but it looks like only for the first purchase?

> When the first train (8/D) is purchased in Phase 7, the purchaser
can trade in a 4/4+ train and get a discount of 300 pounds from
the cost of a D train

**Comment by andrewzwicky** [comment]
Maybe the trading of 8 trains is just a confusing rule wording.  Seems like the player aid is more clear.

[https://boardgamegeek.com/thread/2418145/article/34685291#34685291](https://boardgamegeek.com/thread/2418145/article/34685291#34685291)
