### ISSUE TITLE
[1817] mark tile #X00 as unique / with "Pittsburgh" / annotate Steel Mill private

### ISSUE THREAD

**Issue by damerell** [tobymao/18xx#8264]
In 1817, the Pittsburgh Steel Mill lets you "place special Pittsburgh (F13) yellow tile during tile-laying". It is not obvious which tile that is to someone who has not played the game F2F. I have some proposals and hope you will accept one.

- Although the tile supply is in general infinite, make there be only one #X00, and change "special" to "unique" in the Steel Mill description.
- Mark #X00 "Pittsburgh" as well as "B".
- Have the description of the Steel Mill mention tile #X00 by number.

**Comment by benjaminxscott** [comment]
I'm kind of loathe to change the wording since 'special' is the official rules wording

I added the tile number to the private descriptions since I agree it's easier to figure out

The Volatility expansion adds other privates along with PSM: `P16 P17 P24` with identical powers (on different hexes)

Notably only one of that set of privates (incl PSM) may be in the game at a given time, so we can safely set the count of `X00` to 1
(I think that technically all tiles in 1817 are "infinite", but I don't see why we can't set this to singleton like you mention)

This means we can't mark it as "PITT" or similar, since it could be different city hexes
(seems like it's labeled `B` to match the other pre-printed big cities)
