### ISSUE TITLE
More of a request than an issue.

### ISSUE THREAD

**Issue by hamigua2000** [tobymao/18xx#828]
I'm attempting to play through a log file of an 18Chessie game with my physical copy, and I've noticed that the 0-rotation orientations of the tiles in the physical copy of the game are not always the same as that of your fine interface. For instance, tile 8 starts at the bottom and bends gently to the *right* on the physical game, whereas it bends to the *left* in your interface. Tile 2 is also "flipped" about the vertical axis.

My request would be for you to make the tiles in the interface completely consistent with those in the physical game.

In any case, I thank you for this fine work.

**Comment by tobymao** [comment]
we are creating a new standard and it based on @kelsin 18xxmaker

**Comment by kelsin** [comment]
@hamigua2000 to explain further, one of the problems is that different games use different rotations of each tile, but on 18xx.games we use the same tile definition for every game that uses that tile. Unfortunately there won't be a way to make rotations standard across all games and all physical printings.

**Comment by scottredracecar** [comment]
That is a bit defeatist :-)

The config file for each game could easily be edited to include the rotation. But I don't find it very important for the online to match the physical game--they will sometimes vary over editions and it's all tedious work for not that much benefit if the site handles all aspects of the game. 

However I do find that I don't care for some of the orientations of the current tiles.

For example, this tile is "top heavy",
![image](https://user-images.githubusercontent.com/29106780/85312646-babb4180-b47c-11ea-917e-b9584e279761.png)

Here are the rules John Tamplin provided me which I have used from time to time, but have strayed for convienence sometimes.

```
(orientations for flat-bottom tiles are A at
the top, following clockwise from there -- flat-side tiles are rotated 30
degrees [ie, A is northeast and F is northwest]).

1) if a tile may only be played on a specific place on the map in a
specific orientation, orient the tile so that up on the tile reflects up
on the map.
2) one exit must be in the D position
3) if the exits can be arranged such that they are symmetrical across the
vertical axis, it must be arranged so.
4) if the exits can be arranged to only be on A, B, C, and D, it must be
arranged so.
5) prefer orientations that leave B empty over ones that leave C empty.
```
So that scheme would end up with the tile above rotated 180 which I find more aesthetically pleasing (rule 5 rotates the tile from the shown orientation).

**Comment by tobymao** [comment]
18xx.games will never support this on principal. If you don't like the way a tile is rotated, you'll need to propose the change in 18xx maker and do a migration. But there will never be game specific rotations, it is against the design of 18xx.games.

**Comment by scottredracecar** [comment]
I'd like to understand what scheme @kelsin used when determining exits.

**Comment by hamigua2000** [comment]
> @hamigua2000 to explain further, one of the problems is that different games use different rotations of each tile, but on 18xx.games we use the same tile definition for every game that uses that tile. Unfortunately there won't be a way to make rotations standard across all games and all physical printings.

I figured that something like this was the case, but I thought I'd ask, in case it wasn't. :smile:
