### ISSUE TITLE
1817 Volatility Expansion blocked step in merger/conversion round

### ISSUE THREAD

**Issue by skoomfest** [tobymao/18xx#8281]
Game Link: https://18xx.games/game/92784

Game broken in merger/conversion round: https://18xx.games/game/92784?action=345

Broken action: { "type": "pass", "entity": "WC", "entity_type": "corporation", "id": 346, "created_at": 1660786504 }

**Comment by CraigBeee** [comment]
I am in the game, and two more games of 1817 Volatility died at the same time:
We're sorry this game cannot be continued due to GameError: Blocking step Lay/Upgrade Track cannot process action
Broken action: { "type": "pass", "entity": 136, "entity_type": "player", "created_at": 1659749033 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/91921?action=242)

We're sorry this game cannot be continued due to GameError: Blocking step Lay/Upgrade Track cannot process action
Broken action: { "type": "pass", "entity": 136, "entity_type": "player", "created_at": 1659762898 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/91092?action=264)

**Comment by crericha** [comment]
Games are now pinned. They are games where the loan shark wasn't paid interest due to a bug that has been fixed.
