### ISSUE TITLE
1861: RSR runs automated

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#8292]
In a current game #94263 the player with priority deal ran the RSR for only 320 when a 340 route was possible. The rule is: "the player with the Priority Deal card operates the RSR’s trains and _attempts_ to find the RSR’s maximum possible revenue". In face-to-face play, other players could point out a better route. Normally it doesn't matter, but in this case it made the difference between buying the 1st 8-train or not and therefore determining the length of the game.
My suggestion is: in games with auto-routing enabled, to get the auto-router to attempt to find the best run first.

**Comment by benjaminxscott** [comment]
For context the auto-routing happens client-side, so the server can't kick it off

Would it be possible in those cases to Undo back to the run and modify the route? Or was it too far past that point

**Comment by ianwilson156** [comment]
We'd gone too far to undo back to that point, and anyway we hadn't broken any rule - strictly speaking.

If it's impractical to implement my suggestion, then it will have to be left as it is. But be aware that some rulesets say something like "a company must run for the maximum possible"!

**Comment by benjaminxscott** [comment]
Totally agree w/ the issue, yeah it's not possible due to how the site is implemented (without huge refactoring)

In person you can look at the board on other people's turn and then declare a higher revenue and move a few poker chips around

It's a bit trickier online for someone to point out a higher run, since you have have awkward chat convo and then Undo back

related discussion:
https://github.com/tobymao/18xx/issues/7532#issuecomment-1079105664
