### ISSUE TITLE
Explain to the user when they have to sell down due to no longer being in the orange/yellow

### ISSUE THREAD

**Issue by Thistlegorm** [tobymao/18xx#830]
Our game is 2113. I have 22 certificates, but cannot buy a share. Is this right?

**Comment by jenf** [comment]
You need to sell down in IR, your above the cert limit as the corp exited orange.

(It should really explain this)

**Comment by Thistlegorm** [comment]
Jen, thanks. You are absolutely right.
I should know this.

Thanks again,

Stephen

**Comment by jenf** [comment]
It's not good if we leave a user confused

**Comment by jenf** [comment]
For bug fixing, can reproduce at this point.
https://www.18xx.games/game/2113?action=861

**Comment by KillerOrca** [comment]
I think this should be expanded to a color legend that is displayed next to the market explaining each zone and the effects. Since not every game has the same zones it would have to be done per game. Below is a bad mock-up
![bad legend](https://user-images.githubusercontent.com/67166181/85422512-8d2cd180-b52a-11ea-9083-ba13245e04c5.png)
