### ISSUE TITLE
1822PNW

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#8323]
After stock round, the price didn't move up if 100% hold by players.

After Phase 5, Major company can float at 20% (not 50%)

Major can merge with Asso Minor

https://18xx.games/game/97131

**Comment by benjaminxscott** [comment]
> After stock round, the price didn't move up if 100% hold by players.

This was [fixed recently](https://github.com/tobymao/18xx/pull/8316/files#diff-9bbea57173c44b525c6bb4cb4fd4e1253432fd969dcdef85a24eefb365176d7aR25)

> After Phase 5, Major company can float at 20% (not 50%)
Fixed in #8329

Test cases here, both for directly floating a major and for merging into a major (to make sure both still work)
https://gist.github.com/benjaminxscott/e97e2e8605f6fa274e1f050b88a5fcd9

> Major can merge with Asso Minor
I'm not sure how this works, perhaps @outsidePasser

**Comment by outsidePasser** [comment]
Majors are not supposed to be able to do that, I will take a look.

**Comment by outsidePasser** [comment]
@familiar-hk I do not see in that game where a major can merge with an associated minor.  Do you have an example of that being allowed?

**Comment by familiar-hk** [comment]
In Operation Round 7.2, My SWW is allowed to merge with Asso Minor 1, but in the real game, i just choose not to do so. You can try clone the game and replay from there.

**Comment by outsidePasser** [comment]
I'm not seeing that behavior.  At action 1111, I'm seeing this:

![image](https://user-images.githubusercontent.com/11219077/189730368-569d31ae-9a21-4e65-acdf-bfb722922969.png)

Clicking "forward" to 1112, I'm seeing this:

![image](https://user-images.githubusercontent.com/11219077/189730523-dfa12e7d-1f9f-49af-a886-9c05487170fb.png)

It never asked if the SWW wanted to merge in Minor 1 from the bid boxes.

**Comment by familiar-hk** [comment]
you need to half pay then SWW will get enought $ to merge

**Comment by outsidePasser** [comment]
I see it now.  Thank you.
