### ISSUE TITLE
[1822PNW] Should P19 block mergers between minors?

### ISSUE THREAD

**Issue by setrajonas** [tobymao/18xx#8351]
https://18xx.games/game/97938?action=453

M2 has P19 and built the mountain pass to connect with M1, but was unable to merge in the subsequent merger round. From the rules it seems like this merger should still be allowed.

**Comment by setrajonas** [comment]
Update: it seems like the mountain pass is glitchy in general, M2 also can't lay track beyond it or run through it.

**Comment by outsidePasser** [comment]
It was deliberately written so that you cannot lay track through it.  There is now clarification from the designed that you can lay track through it.

I have seen it reported that the owner cannot run through it, but I have not been able to reproduce it.

Regardless, a fix is being worked to address both of these issues.
