### ISSUE TITLE
18GB - Incorrect Upgrades Shown

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#8488]
Go to this link:
https://18xx.games/game/99513?action=0#tiles

Extra (incorrect) upgrades are shown for the yellow XX and OO tiles. I think the others are correct.

For example, this one should not upgrade to G06 or G11.

<img width="244" alt="image" src="https://user-images.githubusercontent.com/29106780/199080569-80916d23-1339-451b-95bb-8f79a24aa692.png">

**Comment by scottredracecar** [comment]
There are other problems, for example G04 only upgrades to G13 and G15, not G14. I'm guessing whatever fixes this will fix everything. So far, I only see problems with XX and OO tiles.

**Comment by andypymont** [comment]
This isn't actually an 18GB issue and it probably exists in obscure places in other games' manifests too - it's just more obvious in 18GB because there are so many of these multi-city tiles.

The issue is that the `tile_manifest` view only currently checks `all_potential_upgrades?` in the game, whereas much of the tile placement logic is actually handled in `legal_tile_rotation?` in the Tracker step (which is the base for track-laying steps in all games). In effect, tiles are only being checked for the label, number of cities, and which edges are connected, and not for whether all of the paths match up in some rotation or another.

I think to fix this, the logic to check for a valid rotation will have to be moved from the Tracker step into the base game definition, and then the tile manifest view will have to check that logic and reject tiles with no valid rotation. All custom track-laying steps and `legal_tile_rotation?` methods in all games will then need to be reviewed to make sure their logic is still correct based on this change.

This will be quite a big change to the current structure, I can try and tackle it at some point but I need to get more familiar with the UI code and with a number of other game implementations to do it cleanly.
