### ISSUE TITLE
[1861] error in calculating total values before the game end

### ISSUE THREAD

**Issue by ozgurbulbul** [tobymao/18xx#8573]
Game id is 103966, https://18xx.games/game/103966#tools 
Right before the end of the game, the total values of three players were much higher than they should be (oz, strange8ractor, and MarkS), and with the last move of the last corp, their values go down. Trying to figure out whether the final values are wrong, but it looks like they were right. 

To reproduce the issue, please rollback one move, check the final values of all players.
Please note that, these three players’ net worth went down in the last OR.

(https://gist.github.com/ozgurbulbul/d9f08110bd62a0c487a29bab07615df4)

**Comment by ianwilson156** [comment]
I've got the same issue (mid-game value is too high)
https://18xx.games/game/104241 (one player is correct)
https://18xx.games/game/105949 (all players are incorrect)

**Comment by ddaybell** [comment]
The same thing is happening in another 1861 game, and my 1867 game.  It appears to be tied to the merger rounds somehow. 

In  https://18xx.games/game/105367, the discrepancy first appeared at the end of MR3.2, which was the first MR where a merger actually happened.

In my 1867 game, https://18xx.games/game/103654, I noticed that when I bought a share of a new company, in the merger round, the game inflated my score (when my score should have stayed the same).  Note that the inflation isn't a constant, it changes depending on which company is being bought and even which player buys.  But it's got something to do with the merger code it appears.

I attach a chat log excerpt below with additional findings I made.

14:37:43[glenmarcpearce](https://18xx.games/profile/9251)can someone look at [game 105367](https://18xx.games/game/105367) and tell us why our values went down at the end? None of us can think of a reason.
14:46:26[Krongar](https://18xx.games/profile/9793)that is strange, glen. The final values appear to be the correct ones. I calculated BJBehan's total share value plus cash and 7593 is the number I got.
So it's the immediately prior value of 9293 that is the incorrect one (since nothing changed from the penultimate step to the last step of that game.
14:47:31[glenmarcpearce](https://18xx.games/profile/9251)Exactly. What we are now trying to figure out is why the midgame values listed in the spreadsheet were so far off
I mean I don't mind if I actually won that game... I just was so certain before that that I wasn't
14:50:31[Krongar](https://18xx.games/profile/9793)It's kind of like the game is giving the president credit for the value of some asset that the president doesn't actually own.
And then as part of the final score computation the game "catches" that fact and removes that asset from the asset list.
14:51:12[Bellmaker](https://18xx.games/profile/2292)Unpaid loans count against the President
In 1861
14:52:01[Latro](https://18xx.games/profile/2141)there are none at the end of that game
also isn't that only during nationalization anyway?
14:52:35[Krongar](https://18xx.games/profile/9793)Note that Millie's score actually goes up a little bit, whereas everyone else's scores drop, by large numbers.
14:55:44[Bellmaker](https://18xx.games/profile/2292)Hmm could be a bug related to loans counting against that were paid off? Dunno
14:57:53[Krongar](https://18xx.games/profile/9793)I think it has something to do with mergers.
I checked the math for one of the players, at the end of each OR,MR and SR, starting at the beginning of the game.
The values reported were accurate, up until the end of MR 3.2.
That's the first MR that a merger happened, and Millie's value was inflated by $70 after the merger happened.
And Zacharid's score is inflated by 380.
and glen's score is still accurate, and glen has no shares of merged companies at the start of SR4.
dfwinfi... score is inflated by 165, and he also has one share of MKV. So it's not a simple matter of the game inflating the value of a company share by a set amount.
Or Millie and dfw would have the same inflation factor.
But it's somehow tied to mergers.
The same kind of thing is happening in my 67 game. https://18xx.games/game/103654
My value in my 67 game should be $1015 right now, and the game says it is $1185.
Interesting....after I merged to form my company, I then bought another treasury share. The game increased my score by the value of that share when I bought it.
Odd...when PennPacific bought shares of his newly merged company, his value went up, but by far less than the value of a share.
So it's not as simple as the game is failing to deduct the price of a newly-bought merged share from your score.
