### ISSUE TITLE
[1861] does not end if 3 train not bought

### ISSUE THREAD

**Issue by Dave4B** [tobymao/18xx#8660]
If no 3 train is bought, the game will report that it will end at the end of an OR when the bank breaks, but it does not.
This appears to be caused by the code which skips the Merge Round also skipping the check for game end due to broken bank at the end of the Operating Round.
[1861_2trains.txt](https://github.com/tobymao/18xx/files/10418712/1861_2trains.txt)

**Comment by michaeljb** [comment]
gist link for text file - https://gist.github.com/michaeljb/5b10fc191161b5f39f11b05795da8444

**Comment by michaeljb** [comment]
@Dave4B do you have a link to a multiplayer game where this happened, or the game JSON for the game you used to generate this log file? You can go to Tools > Game Data > Copy, and then paste the data into a new [gist](https://gist.github.com/) and share the link to the gist here. That will be much more helpful to work with than just the game log.

**Comment by ollybh** [comment]
@michaeljb I've replicated this bug. Here's a JSON for the game: https://gist.github.com/ollybh/8d482d195f434b236b6e9b0cf29a214c.

The bank has broken in OR12.1, but the check in `end_now?` is not picking up this is the end of the game because `round_end` is saying that this should happen after the end of a merger round. The fix is to get rid of the overridden version of `round_end` and just use the base class's version, which always returns `Round::Operating`. This method is only called for determining the end of the game, and this will never be after a merger round.

Of course this is *never* going to happen in a sensible game, but it is a bug.
