### ISSUE TITLE
[1867] Starting minor in SR1 pushes token placement to game owner

### ISSUE THREAD

**Issue by g3oknight** [tobymao/18xx#8952]
Id: 114511
https://18xx.games/game/114511
https://18xx.games/game/114511?action=74

- player X floated company CA in SR1 for $135
- during the place token step where I would expect player X to get to choose token placement, it shows "CA" on the bar of players getting to choose that token, and the action to place that token is being given to me (game owner)
- it appeared that player X also encountered a similar issue as the 'undo' button was clicked as I was watching real-time to try to bypass the error and allow player X token placement
- current game state has the token placed; unsure of how player X bypassed the issue

Browser: Firefox 110.0 (64-bit)

<img width="1133" alt="1867bug" src="https://user-images.githubusercontent.com/126637308/222034830-eb6968a8-4e80-4817-b724-58aa9ec6471d.png">

**Comment by ollybh** [comment]
Commit 4c65c1f has changed the game behaviour in the HomeToken step. Before that commit the player starting the minor was the active entity, but now it is the new corporation that is active, but the corporation does not yet have a president.

@bentziaxl could this changed be moved to 1880 specific code, instead of affecting the shared code?

**Comment by bentziaxl** [comment]
yes, undo the change, and i'll put it in 1880/home_token
