### ISSUE TITLE
NBDS/Erie token laying bug

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/18xx#896]
On NBDS's first operation, the green tile was not available. The log is from its second operation where now the green tile is available and can be laid, but then the token cannot be re-placed.

[2928.txt](https://github.com/tobymao/18xx/files/4839815/2928.txt)

**Comment by michaeljb** [comment]
This was broken in 436353f1. It survived undiscovered this long because this behavior will only occur if NBDS has no action available besides moving the token, i.e., they are train tight so get auto-passed through train buying, and no companies are available to buy or use. Here's a sample game - [436353f1.json.txt](https://github.com/tobymao/18xx/files/4839995/436353f1.json.txt)

**Comment by jenf** [comment]
This will probably need to wait until after whatever Toby's rewrite is.

**Comment by jenf** [comment]
Fixed in Toby's rewrite branch

**Comment by jenf** [comment]
Fixed in or rewrite
