### ISSUE TITLE
[1846] Does not allow me to pass when only one private remains

### ISSUE THREAD

**Issue by peterh58** [tobymao/18xx#9070]
_3.22 If the deck is reduced to one Private Company, the player who draws the last Private Company reveals it and may either buy it at full price or pass it on to the next player with its price reduced by $10. This player then has the same choice: buy it at its current (reduced) price or pass it on, reducing its price by another $10. Repeat this until a player chooses to buy it. (A player must take it for free if its price is reduced to $0.)_

In 1846 game id 117543, at 06:16 on 25 March, we were in the distribution of privates, and the private deck had only Michigan Southern remaining. When it's price was down to $90, on my turn I pressed Pass(Buy) and instead of play passing to the next player , it had me buy Michigan Southern for $80. This seems to contradict the rules (3.22, see above).

**Comment by benjaminxscott** [comment]
It's possible this was clarified in [the updated rules](https://gmtwebsiteassets.s3.us-west-2.amazonaws.com/1846/1846-RULES-2021.pdf)

since `3.22` now reads:

>  A player must take it for free (and pay any debt it has) if its price falls to $0.

In this case, the player before you (`Bikesnob`) was presented with MS at 90 and passed, so the site helpfully auto-buys it for your player since it's now 80 (which is "free" / the minimum it can be bought for, since it has 80 in debt)

https://gist.github.com/benjaminxscott/d313d464aa2505f14915e475ffc20876
