### ISSUE TITLE
[1822PNW] P11 Allowing extra yellow tile lay followed by an extra upgrade

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#9085]
Game ID: 116839
Link: https://18xx.games/game/116839?action=947 (game state after laying 1 extra yellow)

ORNC laid 2 yellow using its normal track lay, then activated P11 to lay a 3rd yellow (game state in move linked above), and is then able to activate P11 again to upgrade G16 (Park Place) from Green to Brown (I undid this move after doing it, as I'm fairly certain this is not intended and don't want to cheat in an active game).

**Comment by MrSkinny** [comment]
Reviewing the README descriptions and options for [tile_lay](https://github.com/tobymao/18xx/blob/master/lib/engine/ability/README.md#tile_lay), I believe the functionality for the 22PNW needs is not provided and may need extending. 

Right now, it appears the `count` var tracks "lay" and "upgrade" as equal actions. Thus, a `count` of `2` will allow lay+lay; lay+upgrade; upgrade+upgrade.

Someone here probably has greater familiarity with private powers across many 18xx, so I'm not sure if this power config is needed? For 18PNW it appears we need to restrict to: lay(+lay) OR upgrade.

Would you recommend an approach of an entirely new `type` power or keeping `tile_lay` but adding a new option that interacts with count differently?

**Comment by michaeljb** [comment]
@MrSkinny maybe in [`G1822PNW::Step::SpecialTrack#process_lay_tile`](https://github.com/tobymao/18xx/blob/aa8351a6ae1998895b98dcb16881dab9c2d57820/lib/engine/game/g_1822_pnw/step/special_track.rb#L119) you chould check if the action is being done by P11 and the new tile is not yellow, and if so, use up the ability an extra time? That would at least get rid of upgrade+lay and upgrade+upgrade, would still need to address lay+upgrade...

Maybe these lines in `Engine::Step::SpecialTrack` could be extracted to a function that 1822PNW overrides, so that after performing one lay, P11 only gets yellow tiles as potential options:

https://github.com/tobymao/18xx/blob/9f14e1b4ee24c0a39e130224d9c3d08e04afab4b/lib/engine/step/special_track.rb#L125-L126

**Comment by outsidePasser** [comment]
It might be worth checking the other 22 variants as well - they all have a 'lay extra tile' minor.

**Comment by michaeljb** [comment]
Confirmed the same behavior is happening in 1822 and 1822MX
