### ISSUE TITLE
[1880] HKR has "extra" token in display

### ISSUE THREAD

**Issue by outsidePasser** [tobymao/18xx#9093]
HKR has an "extra" token in it's display on P5 (which isn't actually a hex) - I'm wondering if it's a coincidence that the owner of the HKR is the owner of the "P5" private.  

![image](https://user-images.githubusercontent.com/11219077/230736252-07ceb4f4-c2b9-4b66-8633-cc5f2dd498e2.png)

https://18xx.games/game/116883

**Comment by outsidePasser** [comment]
Also - P5 is the private that gives a D permit, and that permit was given to the HKR.  So that seems really likely to be related.

**Comment by yoyoson** [comment]
Here's another example. https://18xx.games/game/114879?action=1127

At action 1126, the charter for JHA was fine; it only had 3 tokens (as is normal). 

Action 1127 was placing P5 into JHA:
```
Jeme Tien Yow Engineer Office is assigned to JHA
```

and that is when the "extra" P5 token showed up on the charter.

**Comment by benjaminxscott** [comment]
The icon gets added as a pseudo-token with intent to indicate that the private has been assigned to that corp

(see also: meatpacking/steamboat in '46)

https://github.com/tobymao/18xx/blob/4523b91876ef1d55cd639a52a55a353cd2b9df6d/assets/app/view/game/corporation.rb#L287

I added an icon so it wouldn't render a broken image, I think that works well since it'll be more apparent which corp has the power assigned
