### ISSUE TITLE
[18Rhl] Forced Train Purchase forces you to buy the cheapest train.

### ISSUE THREAD

**Issue by edvinvoneuler** [tobymao/18xx#9219]
**What's your Game ID?**
Game ID: https://18xx.games/game/123190

When in Forced Train Purchase with a train in the bankpool the director is forced to buy the train from the pool even though the rules explicitly say you do not have to.

![image](https://github.com/tobymao/18xx/assets/39345445/8baf0575-e466-4886-8be7-da3a8cdbbfeb)
![image](https://github.com/tobymao/18xx/assets/39345445/833b649b-d57c-4f8b-b1f0-515d23354017)

**Which Browser / Platform?**
- Chrome, 113.0.5672.126 (Official Build) (arm64) 
- Platform: Desktop

**Comment by philcampeau** [comment]
The problem here is that in this case, the director doesn't have to make up the difference from his own cash reserves. The corporation has enough money to buy the train in the bank pool. 

If the corp had 199M, you'd be able to force fund the 6 train from the Depot, but since the corp can afford the 3 train, you are not in a Forced Train Purchase.
