### ISSUE TITLE
[1846] minors not interactable in 2p game (hotseat)

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#9222]
Hotseat game

Not sure why, but the MS and BIG4 were not able to lay track / etc

Home tokens don't seem to be laid on the map

Repro'd in another hotseat game as well

https://gist.github.com/benjaminxscott/c2944dbd62325f5e1313162be16e4148

**Comment by michaeljb** [comment]
This is a 2p Variant game, but the game title in the hotseat JSON is `1846` and not `1846 2p Variant`.

Importing a new hotseat game with the actions removed from your JSON and the title set to `1846 2p Variant` shows the minor tokens placed on the board, as well as a bunch of other setup--removing some of the private companies (including the one drafted on action 1, which is why I said the actions need to be removed), and placing tokens for the removed corporations.

How did you create a 2p `"title": "1846"` game? That's the real problem here. We should probably change this to `raise GameError` instead of `return`:

https://github.com/tobymao/18xx/blob/e5c9c01e61395a8529d34452bd8455862cd16ba8/lib/engine/game/g_1846/game.rb#L270-L271

**Comment by benjaminxscott** [comment]
Huh weird yeah I don't know how it got into that state, I wasn't fuzzing
the logic or anything

Yeah that guard clause should probably throw if somehow the user was able
to convince a game to start with bogus params (eg POSTing directly to the
newgame endpoint instead of thru the frontend)

-_Ben

**Comment by michaeljb** [comment]
Weirdly enough that case is covered:

https://github.com/tobymao/18xx/blob/cc5113b4a2543b465cc0abef31b1c1e37a111394/routes/game.rb#L145-L148

I don't know how this is possible outside of importing a hotseat game where you've messed with the JSON, 🤷
