### ISSUE TITLE
18CZ route includes town when running a 5E train

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#9278]
https://18xx.games/game/124453?action=858

The PR runs a 5E from B19 - D17 - G20 - G22 - G24 - I24 which should be 320 but it is 350. I think G22 is added but it shouldn't.

**Comment by philcampeau** [comment]
PR is running a 6E from what I see. E trains _can_ skip towns, but aren't required to. Since it's only counting 5 other revenue locations, the 30 value town is added to the run. 

As per the rules:

> (E-trains) may travel through the number of revenue locations up to the
number stated on the card. The actual length of the track is
immaterial. As many towns (and only towns!) on the route as you
wish may be omitted; omitted towns do not count toward the
number of revenue locations.

**Comment by mb1898** [comment]
Sorry, my mistake.

Michael

Von: philcampeau ***@***.***>
Gesendet: Montag, 26. Juni 2023 21:21
An: tobymao/18xx ***@***.***>
Cc: mb1898 ***@***.***>; Author ***@***.***>
Betreff: Re: [tobymao/18xx] 18CZ route includes town when running a 5E train (Issue #9278)


PR is running a 6E from what I see. E trains can skip towns, but aren't required to. Since it's only counting 5 other revenue locations, the 30 value town is added to the run.

As per the rules:

(E-trains) may travel through the number of revenue locations up to the
number stated on the card. The actual length of the track is
immaterial. As many towns (and only towns!) on the route as you
wish may be omitted; omitted towns do not count toward the
number of revenue locations.

-
