### ISSUE TITLE
[1841] Unable to purchase concession from Bank in Phase2

### ISSUE THREAD

**Issue by zexine** [tobymao/18xx#9367]

**Comment by roseundy** [comment]
Game id?

**Comment by zexine** [comment]
It's easily reproduceble via hotseat.
https://docs.google.com/document/d/1yqf4sB3QAOISwRdt2HIYuEZYP4Uerc8IWO6QT6xLmRk/edit?usp=drivesdk

**Comment by zexine** [comment]
BTW, game crashes if all players just pass in Auction round.

**Comment by roseundy** [comment]
As far as that last issue is concerned, the RAW doesn't cover this case. If no concessions are bought, then no one can do anything in SR1 and there can't be an OR1. TBH, crashing isn't a bad response.

**Comment by scottredracecar** [comment]
Crashing is kind of bad because the interface doesn't allow you to back up
to fix it.

But of course it is bad that there is no such rule.

How about just ending the game in that case so it doesn't crash?

**Comment by roseundy** [comment]
Probably I should just not let the auction round end until an actual concession is bought (and not just the Bayard).

**Comment by roseundy** [comment]
Actually, the rules say the first player "chooses a Concession to put up for bid". It doesn't say they can pass. Subsequent concessions, yes, but not the first. Unfortunately, if the only concession bought is the Bayard, then we still can't have a SR or OR.

**Comment by roseundy** [comment]
In any case, the first issue is the one I'm going to focus one.

**Comment by roseundy** [comment]
So the first issue was caused by my checking if we were passed the first phase, instead of the first round. I missed this because when I tested this I was in a game where we made it to phase 3 by the 2nd SR.

By the way, this is why I asked for a specific game. Many bugs are like this, they need specific conditions to be true to manifest.

**Comment by roseundy** [comment]
Interestingly, fixing the first issue takes care of the 2nd. Apparently the crash was caused by an infinite loop where SR2 was auto-passed since no-one could by anything, which skips OR2, and then SR3 auto-passes. Rinse and repeat.
Now when everyone passes in the auction, we skip SR1 and OR1, but land in SR2 where players have an opportunity to buy concessions from the bank. If people want to keep passing, that's their problem, but the code doesn't crash.
