### ISSUE TITLE
[1841] Cannot Buy President's Cert from Market

### ISSUE THREAD

**Issue by djanyreason** [tobymao/18xx#9379]
Game ID: https://18xx.games/game/130760

After the Ferdinandea Succession, the SFL is frozen with 3 shares in the OM and 7 shares in the company. SFL also owns a share of a company that is owned by the SB. The currently operating company is a child of the SFTG, and has no cross-ownership with the SB or SFL. It has sufficient money to buy the presidency of the SFL from the OM - however, the only options presented are to buy a share from IPO or a single share from the OM; there is no option to purchase the Presidency from the OM.

**Comment by roseundy** [comment]
Except for player-to-player purchases of concessions before phase 4, you are never allowed to buy a president certificate directly. This is true for the vast majority of 18xx games. If you want to unfreeze a corporation you must buy multiple single shares. Once you have 20% of a major corporation (40% of a minor), the president certificate will be swap for your pair of shares. Since a corporation can only buy one share per OR, it will take two ORs for a corporation to take over another frozen corporation.

**Comment by djanyreason** [comment]
I don't believe this is correct. Rule 4.7.2 states "the Corporation, using its own Corporate money, may: but one **_Stock Certificate_** of another non-controlling Corporation at the current market value from the Bank Pool" (emphasis added). A President's Certificate is a stock certificate - the rules specify certificate, not share.

Playing face-to-face many times this rule has always been interpreted to mean certificate, not share, and allowed purchases of a frozen presidency (often times the SFL).

**Comment by roseundy** [comment]
The 1841 ruleset is notorious for it's vagueness. I need to see an official ruling on this.
