### ISSUE TITLE
Switch in Presidency during Tuscan Merge

### ISSUE THREAD

**Issue by WayneWWms** [tobymao/18xx#9408]
**What's your Game ID?**  131172

**How to Reproduce the Bug?**

[22:13] Moving 2 share(s) of SB from ATFA to SFLi treasury
[22:13] SFLi becomes the president of SB

TN and SFLP each had 2 shares of the SB.  TN was president per the Secession rules.  During the merger SFLi picked up the 2 shares and somehow took over the presidency of the SB.

**Which Browser / Platform?**

**Comment by WayneWWms** [comment]
![image](https://github.com/tobymao/18xx/assets/80569227/d154eed1-5e49-4e78-b6e8-e7ff53fd717d)
SB is missing a share in the display.

**Comment by roseundy** [comment]
Likely a dup of #9389 and/or #9401

**Comment by Hewhite2003** [comment]
Not a duplicate of #9389 or #9401.

Now has game ending error.

We're sorry this game cannot be continued due to GameError: Blocking step Choose token to remove cannot process action 412
Broken action: { "type": "remove_token", "entity": 14294, "entity_type": "player", "id": 412, "created_at": 1692102615, "city": "13-0-0", "slot": 0 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1841,%22needs%20triage%22) and include this link (https://18xx.games/game/131172?action=411)

**Comment by roseundy** [comment]
Still a dup. New error is caused by bug fixes that invalidated your game.

**Comment by Hewhite2003** [comment]
Cool. Thanks for fixing the bugs. Sent from my iPhoneOn Aug 15, 2023, at 12:58 PM, Steve ***@***.***> wrote:﻿
Still a dup. New error is caused by bug fixes that invalidated your game.
