### ISSUE TITLE
[1841] 11 shares and incorrect token price of new corp

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#9417]
https://18xx.games/game/132008?action=372

ISSUE 1
In OR2.2, there are 11 shares of SFTN showing.  2 in Ethinroe, 8 IPO, 1 Market.

ISSUE 2
Additionally, I tried to start a corporation in Brescia.  It was making me pay 100L instead of 50L for tokens.  Per rules: "ignore track on the other side of an active border as well as pre-printed track which is not connected to a city"  Since D10 was not connected, to Bergamo, it should have been 50.

**Comment by roseundy** [comment]
1. Clearly something went wrong when SFTN became frozen. I'll debug in detail tonight.
2. This is also a bug, but it doesn't have anything to do with borders. The problem is the section of my code that is trying to determine if the pre-printed track next to Brescia is connected to a city.

**Comment by roseundy** [comment]
1. The bug is that the game allowed you to sell one share of SFTN when all you had was the president's certificate. Since there wasn't anyone that could take over the presidency, this was an illegal move and should have been prevented by my code. I suspect that the problem is that many rules of stock sales are relaxed during EMR, but that one should always be enforced.

**Comment by roseundy** [comment]
Both issues were correctly identified. Fix is ready.
