### ISSUE TITLE
[1841] Unable to emergency buy minor token

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#9423]
https://18xx.games/game/132093

Unable to issue shares to emergency fund initial token.

**Comment by roseundy** [comment]
It's difficult for me to debug this when you move on in your game. Which corp started which minor on which OR?

**Comment by roseundy** [comment]
Was there an error message, and what was it?

**Comment by roseundy** [comment]
I just tried to construct a case based on your game and it worked for me. There must be something else going on. Without knowing the specifics of your failure, I can't debug it.

**Comment by roseundy** [comment]
Just on the off chance you're misinterpreting what's happening in the game: when a token purchase (when starting a corp) requires EMR, the game does it for you, since there are no real choices to be made. You _must_ issue shares to pay for the token. For token purchases when starting a corporation, this _always_ covers the cost. 

Token purchases when converting a minor to a major is a different matter altogether and will cause an EMR much like a mandatory train purchase.
