### ISSUE TITLE
[1841] Ferdinandea Secession with frozen company leaves no way to view that company.

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#9439]
https://18xx.games/game/132499?action=450

During the Secession, there was nowhere to view the frozen SB's treasury. It did not appear on Entities. I had to look in spreadsheet to see its treasury, and in other companies, to see which ones owned shares.

**Comment by roseundy** [comment]
I decided to not mark corporations as frozen during the share exchange because it could be confusing when it was just temporary. But that means the corp doesn't show up in the Entities tab if its president share is in the Market.

The fix is to modify what corps show up under the Bank on the Entities tab.
