### ISSUE TITLE
18Texas duplicate train

### ISSUE THREAD

**Issue by saccenti** [tobymao/18xx#9467]
SAA is about to buy MP's 3T. We are here: https://18xx.games/game/131086?action=292

SAA buys MP's 3T for $1. Now SAA has a 3T. And MP still has a 3T.

**Comment by philcampeau** [comment]
The issue seems to happen at this step https://18xx.games/hotseat/hs_kyuheqre_131086?action=236

MP has two 3 trains and buys the first 5. The log says "MP discards 3 and it is removed from the game", however, on [action 292](https://18xx.games/hotseat/hs_kyuheqre_131086?action=236), the game still shows MP as having two 3 trains in addition to the 5. 

It looks like the log is saying that the train is discarded, but the train still exists in the code for MP somewhere. 

I'll take a look and see if I can find a reason.

**Comment by philcampeau** [comment]
I've submitted a fix for this issue, but it won't help your game unfortunately.
