### ISSUE TITLE
1866 Track rights in Italy minor nationals not recognized

### ISSUE THREAD

**Issue by DFritsch56** [tobymao/18xx#9639]
1866: I am running SFAI and own I1 K2S, I2 SAR, and I4 PAP. It lets me lay track or place tokens in I2 SAR, but not in I1 or I4. Also when running the IFT it would not let me lay track in I2, but could in I1 or I4.

**What's your Game ID?**
132720
Description: Teaching 1866 to RichO

https://18xx.games/profile/11362

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by DFritsch56** [comment]
Can someone look at this bug. Game has been on hold.

**Comment by ollybh** [comment]
This was seen in phase 3, operating round 4: https://18xx.games/game/132720?action=532.

I think the problem here is that the graph isn't including the ferry route between Sardinia and Rome. The hexes on the Genoa–Sardinia ferry are shown as available, but not the ones for the Rome–Sardinia ferry.
![image](https://github.com/tobymao/18xx/assets/11144854/7dabf17d-da7a-4037-b942-035bb6e4befd)

By operating round 5 (phase 4) this had fixed itself. https://18xx.games/game/132720?action=747.
