### ISSUE TITLE
[1850] I sold five shares of MILW and the stock price did not decline. Game Id 132733

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#9659]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment]
https://18xx.games/game/132733?action=196

Confirmed that the price is not on a shelf, and does not drop after 5 shares are sold and corp is dumped on another player.

**Comment by benjaminxscott** [comment]
I believe the issue is here: https://github.com/tobymao/18xx/blob/9e1f1ca9f3761d96353cb45c3ebc829f5f919e18/lib/engine/game/g_1850/game.rb#L339

Because sell_shares() changes the president, at the time of this check the former president is not the current president

It seems like the current codepath only drops the price if the president sells AND the president doesn't change

I removed that clause but it seems to have broken some price protection logic, so I don't feel comfortable PR'ing that until/unless I grok the price protection code more

**Comment by Rupre** [comment]
Are you still trying to resolve this issue?

**Comment by benjaminxscott** [comment]
I'm not actively looking at it, I had posted above to make finding a fix easier (hopefully)

**Comment by Rupre** [comment]
Will the bug be worked on eventually?  Should I delete the game?

**Comment by philcampeau** [comment]
Issue also occurs in https://18xx.games/game/136290?action=252

**Comment by m4rt1n2d** [comment]
This is not fixed.  SR7 no price change.
https://18xx.games/game/136745

**Comment by philcampeau** [comment]
Yep, well aware. Still looking into what's causing the issue.

**Comment by KinnairdGames** [comment]
Same issue with RI: https://18xx.games/game/137179 at 22:07 on 18/10/2023

**Comment by m4rt1n2d** [comment]
This same issue affects 1870 as well.

**Comment by andrewzwicky** [comment]
Does anyone have an example from an 1870 game?  I think I have an idea what might be sorting it out for 1850, but 1870 appears to be working correctly in the case of selling shares, president changes, price drops.  It seems to happen 100% of the time in 1850.

https://18xx.games/game/136919?action=152
