### ISSUE TITLE
[18VA] Tredegar Iron Works doesn't give discount

### ISSUE THREAD

**Issue by dtschirmer** [tobymao/18xx#9686]
**What's your Game ID?**

https://18xx.games/game/135758

Here's the game data as a gist
https://gist.github.com/dtschirmer/c8e66ccfbea4cbfd56b60705069bee2c

**How to Reproduce the Bug?**

During OR 4.2,  while operating VR, I clicked on the Tredegar Iron Works ability button, and the price of the train I was going to buy did not change (should be -$200).
I'm not sure how the price change is actually supposed to happen in the game, but I wasn't able to purchase a train for a lower value. Looking at another game's data where it did work, the json just showed a lower price. No matter what I tried (clearing browser cache, logging out and in, updating browser, taking off Firefox protection) I couldn't get a lower price.

**Which Browser / Platform?**

Firefox 117.0.1 (64-bit)
Mac OSX 12.6.1

**Comment by philcampeau** [comment]
Strange. The code is in place, and when I create a new game in hotseat mode, the discount works on this train. I've also played many games of 18VA and never encountered this issue. But when I create a hotseat game using the game data from this game, I can confirm the issue occurs on my end too.

**Comment by dtschirmer** [comment]
I guess I'm cursed! lol.

Thanks for looking into this, it's really weird. I couldn't see anything
(from what little I know) in the data that would point to an error.

**Comment by magnusrk-ch** [comment]
Stepping through it in a debugger I found the following:

1. The ability doesn't work because `@selected_company` is actually nil at the time of the purchase.
2. `@selected_company` is nil because `render` in app/view/game/round/operating.rb sets it to nil after determining it doesn't have any abilities.
3. It doesn't have any abilities because `ability_right_time?` looks for when = `buy_train`, but the ability has when = `buying_train`.

The check in 2) is relatively new, from early September: https://github.com/tobymao/18xx/commit/7ea0f186b56f06525f85d544e66822429bcb6d0e
Based on the commit description, it seems entirely possible this is yet another case of clearing `@selected_company` when it shouldn't be, due to the mismatch in 3). E.g. the render time check might expect `buy_train` while the buy action processing check might require `buying_train`, so if we didn't clear the company it would Just Work.

The actual mismatch in 3) is weird. 18NY and variants use `buy_train` and everything else uses `buying_train`. I don't see any reason these should be different, but I am not at all familiar with train buying abilities.

**Comment by JaySixA** [comment]
Any idea when this will be addressed?

**Comment by jasonbegy** [comment]
Same bug here: https://18xx.games/game/146806

**Comment by ChrisTheCat** [comment]
> Same bug here: https://18xx.games/game/146806

I don't see the bug in that game. When VR acquired Tredegar Iron Works, it had ~450 and needed 800 to buy a train from the depot.

**Comment by magnusrk-ch** [comment]
https://github.com/tobymao/18xx/blob/master/assets/app/view/game/round/operating.rb#L40

This is the code that wipes out @selected_company and prevents the ability from working.

The bug only triggers when there are zero purchasable companies. In the buggy game there are zero player owned companies. In the functional game there is one.

So it comes down to https://github.com/tobymao/18xx/commit/7ea0f186b56f06525f85d544e66822429bcb6d0e again. That's attempt #3 to get it right, and it turns out didn't work that time either.

Exactly why the train discount doesn't register as an available ability is still puzzling, but we should revert the change above to unbreak games first.

**Comment by ventusignis** [comment]
I'm uploading a fix soon; changing the timing from `buying_train` to `buy_train` fixes Tredgar; looking at the `ability_right_time?` implementation it looks like `buying_train` isn't the name of a step or explicitly stated so it doesn't get past this

https://github.com/tobymao/18xx/blob/master/lib/engine/game/base.rb#L3082
