### ISSUE TITLE
18zoo market details

### ISSUE THREAD

**Issue by serpentium** [tobymao/18xx#9693]
Hi,
I ask if it will be possible to code more numbers in each cell of market tab.
What 18zoo needs is three numbers (share value,revenue, threshold) for each cells like in this pic

![](https://cf.geekdo-images.com/KGlFUsaWc3P_4TQEUPGIWw__imagepage/img/l0dTWH1jFaO7v5IRFyBByoFsNnM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6153038.png)

i know it is the only 18xx with this feature, so I hope I can get the “ok” and ask my coder to see how to do it

**Comment by crericha** [comment]
The `SharePrice` class already has an `info` attribute that is used to display additional information at the bottom of the share price box. I suggest using this and putting a comma between the two values. Something like `50, 1` for the 4 value in the second row from the bottom.

**Comment by carlorusso1984** [comment]
I saw there is no usage of info for 2d Stockmarket
I would like to update the 2d StockMarket to show this
<img width="1590" alt="image" src="https://github.com/tobymao/18xx/assets/147172862/deba19ad-7c1d-4bbc-81d5-f665f79cf8c3">
@crericha can you share what do you think?

**Comment by crericha** [comment]
@carlorusso1984 sorry, I didn't see this until now. If you don't hear back from me, please contact me on Slack because I probably missed it.

Why is the 2D stock market harder than what was done to the 1D? I didn't do the original changes, so I don't know much about them other than there is no issue with them.
