### ISSUE TITLE
[1847AE] 2 sold shares being counted as double share

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#9701]
SR7, 2 10% RNB shares sold, player trying to buy one, but its being forced to buy both 10% shares.

https://18xx.games/game/136352

**Comment by m4rt1n2d** [comment]
There are actually 2 buttons when selling the RNB for selling 2 shares.  One let me sell the president's share, while keeping 40%.  One allowed me to sell 2 regular shares.  The bug is in that step.

**Comment by philcampeau** [comment]
Interesting. For reference, the issue comes up here: https://18xx.games/game/136352?action=304

The president has 60% ownership, but both of the additional 20% shares are held by other players. This player has the president's cert and 4x10%. When they click on RNB, they're given the options here: 

![image](https://github.com/tobymao/18xx/assets/26125362/3ca601d9-7957-46fb-a5fa-1813cb05ecdb)

**Comment by Galatolol** [comment]
I have a fix for this particular issue.

However, there may be a trouble with presenting Sell options to a player owning two non-president double certs, I'll have to look into that too I haven't yet.
