### ISSUE TITLE
[1868 Wyoming] Game will not load 

### ISSUE THREAD

**Issue by fcboyd** [tobymao/18xx#9714]
**What's your Game ID?** 134425 https://18xx.games/game/134425

**How to Reproduce the Bug?** Try to open the game link, not sure what game actions potentially caused it because I am unable to see the game log.

**Which Browser / Platform?** Google Chrome Version 116.0.5845.187

**Comment by magnusrk-ch** [comment]
Game sees an assign action during SR, which triggers 1817-style subsidiary rendering, which 1868 doesn't support. Assign action is showing because LHP needs to be assigned, because phase 5 triggered via train export after the OR.

The LHP assignment should definitely happen before the SR starts. Separate from that, it's not clear that SR ever needs the Assign step.

**Comment by michaeljb** [comment]
> The LHP assignment should definitely happen before the SR starts. Separate from that, it's not clear that SR ever needs the Assign step.

In the PR I have the assignment working during the stock round. The end-of-OR-set train export doesn't happen until `next_round!` is called, so it can't happen during the operating round. Maybe I could get this to work during the BUST round which follows the OR set.

**Comment by michaeljb** [comment]
On second thought, I think I will do this in the BUST round, probably would be technically better to have the LHP assignment occur before the NO BUST private anyway, and then I get OR rendering for free.
