### ISSUE TITLE
1858 wording on V&J P5 minor is wrong

### ISSUE THREAD

**Issue by Chrisozwa** [tobymao/18xx#9719]
Very minor issue: P5 V&J home hex is L13 not L11 as written on the "card".

**Comment by ollybh** [comment]
This was spotted a while ago and fixed in #9643, so I'm not sure why you're still seeing the wrong location. Here's what it looks like to me:
![image](https://github.com/tobymao/18xx/assets/11144854/5ca32c89-7e71-4443-9956-42801bf7e8fd)
Can you make sure you're running the latest code in your browser by doing a hard refresh (Shift+F5, or whatever is appropriate for your browser and OS) and see if this fixes it?

**Comment by Chrisozwa** [comment]
Thx, it looks right now.
