### ISSUE TITLE
1830 sales of private companies between players

### ISSUE THREAD

**Issue by Krk1968** [tobymao/18xx#9735]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by Krk1968** [comment]
Question on player to player sales of private cos in 1830. The rules say this is possible, but I can’t figure out if the 18xx.com coding allows for it [rule 3.1 Private companies may be sold between players for any mutually agreed price at any time during the buyer’s or the seller’s turn of a stock round (other than the first).]

**Comment by benjaminxscott** [comment]
It doesn't look like we implement this in 1830, 1841 [seems to have logic for this](https://github.com/search?q=repo%3Atobymao/18xx%20allow_player2player_sales%3F&type=code)

**Comment by Krk1968** [comment]
Thank for checking Benjamin.

Understood.  

I am new to the site and really appreciate all the work that has been done to make it run.

**Comment by roseundy** [comment]
Other games besides 1841 allow player-to-player sales of private companies.

**Comment by philcampeau** [comment]
This could be something to insert into the base code defined as a constant, with False as the default.

**Comment by philcampeau** [comment]
After looking at this again, I'm realizing a constant doesn't really work, since the phases this would be possible might vary from game to game. 

Digging deeper, there's already a status checked in the base code, :can_buy_companies_from_other_players: 
https://github.com/tobymao/18xx/blob/55fdacbbb73ab5d976eaf1c56c7aff49debce129/lib/engine/step/buy_sell_par_shares.rb#L301

I'll implement this as a variant for 1830

**Comment by philcampeau** [comment]
After reading both the avalon hill and mayfair rules, this isn't a variant rule at all, but a standard rule for the game. I implemented it into the default rules.
