### ISSUE TITLE
1844 P2 Track Lay Blocked

### ISSUE THREAD

**Issue by Lime-Turtle** [tobymao/18xx#9766]
1844.  Attempt to use P2 to lay track blocked.

1844 137304

`https://18xx.games/game/137304`

**How to Reproduce the Bug?**

- During Operating Round 4.1 the JS laid track in G3 and attempted to use P2 to lay track in F4.
- red banner message to say that the action is blocked.

Android

**Comment by benjaminxscott** [comment]
Looks like that game proceeded, the relevant action step seems to be https://18xx.games/game/137304?action=236

In hotseat I was able to lay G4 and then F5 with P2 (in any configuration) on the JS 
(those seem to be the hexes in question rather than G3 and F4)

![image](https://github.com/tobymao/18xx/assets/1711810/24994af9-2a47-455d-bdf4-735d4a4f2d17)

![image](https://github.com/tobymao/18xx/assets/1711810/d54a661b-563a-4135-aba7-a34f54e27672)

**Comment by Lime-Turtle** [comment]
Yes in a hotseat cloned game it worked fine.  Can you see the chat in the
log between me and mkttimer?

Hopefully its closed because fixed, not closed because perceived to not be
a problem as it works in the cloned hotseat game.

Simon.

**Comment by scottredracecar** [comment]
Simon, whenever it says “completed via” when closed, that means it was
“closed because fixed” and you can open the linked number to see what code
was changed to fix it.
