### ISSUE TITLE
1844 could not continue due to GameError: Blocking step Sell then Buy Shares cannot process action 759

### ISSUE THREAD

**Issue by KenBoucher** [tobymao/18xx#9784]
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by KenBoucher** [comment]
https://18xx.games/game/137848?action=758

**Comment by crericha** [comment]
There was a bug with the SBB formation where sometimes you wouldn't get all your shares. In your game, both you and Pierre should have received an additional 5% share of SBB that you did not get. When the bug was fixed, you got the additional 5% share, which caused you to become share tight and the AB share purchase is now illegal.

I can revert your game to just before the illegal share purchase or delete it. Let me know which you prefer.

**Comment by KenBoucher** [comment]
Please revert to the illegal share purchase.

Thanks,
Ken
________________________________
From: Chris Rericha ***@***.***>
Sent: Sunday, October 15, 2023 1:07 PM
To: tobymao/18xx ***@***.***>
Cc: Ken Boucher ***@***.***>; Author ***@***.***>
Subject: [Ext] Re: [tobymao/18xx] 1844 could not continue due to GameError: Blocking step Sell then Buy Shares cannot process action 759 (Issue #9784)


There was a bug with the SBB formation where sometimes you wouldn't get all your shares. In your game, both you and Pierre should have received an additional 5% share of SBB that you did not get. When the bug was fixed, you got the additional 5% share, which caused you to become share tight and the AB share purchase is now illegal.

I can revert your game to just before the illegal share purchase or delete it. Let me know which you prefer.

**Comment by crericha** [comment]
All set!
