### ISSUE TITLE
[1862] Buying shares of company in receivership after LNER formation

### ISSUE THREAD

**Issue by VaiKai** [tobymao/18xx#9817]
Game Id  : 136412

Hello,

We encountered a problem in our 1862 game.
When LNER launched (SR after buying first H train), one company was in receivership, but we weren’t able to buy 30% and thus become president.
We read the rules again, and we have seen nothing that should forbid it. As the company is already launched, we should be able to buy shares to change presidency.
I guess that the rule has been coded like «It is not allowed to buy a president share» but this seems to be a situation where we should be allowed :)

Olivier

**Comment by VaiKai** [comment]
One of the players tried a hotseat copy and told me that you need 3 times the price in cash to be able to buy the presidency share even if you already have 20% and should need only 10%

**Comment by philcampeau** [comment]
I've just loaded the game locally at the start of SR5, and I was able to have jonajuwon buy a third share to become president, or to have any other player buy a share on three consecutive turns to gain the presidency.

I'm not sure where the issue is? Can you clarify a bit?

http://18xx.games/game/136412?action=744

**Comment by VaiKai** [comment]
Hello,
During the SR, we were blocked when everyone had 2 shares, and I had one (Olivier). Then Bapts tried to buy one more share and it was not possible. 
I also tried, and I could’nt either. 
Olivier

**Comment by VaiKai** [comment]
First round of the SR was :
21:04] Olivier buys a 10% share of EUR from the market for £110
[23:38] Docteurslump buys a 10% share of EUR from the market for £110
[23:41] Jonajuwon buys a 10% share of EUR from the market for £110

And then we all bought a share of WNR (except jonajuwon), and next round we were blocked.

**Comment by philcampeau** [comment]
This is actually a consequence of rule 6.3:
![image](https://github.com/tobymao/18xx/assets/26125362/c37008d7-1da9-4105-89cf-e47b314faac1)

So you can't buy the director's cert directly from the Bank Pool. You have to buy 3 individual certs, which are then exchanged for the director's cert. 

Because three players held two shares, and a fourth player holds one share, there are no remaining single shares left to buy. As such, no one can buy a third individual cert. Since the Director's cert can't be bought directly, there is no purchasing option. 

I'm a bit confused from an earlier comment where you said that someone did a hotseat and found they could buy the director's cert if they had enough money for 3 shares. I just tried, and that is not the case.

**Comment by VaiKai** [comment]
You’re right. Literally it was like that. 
We never faced this situation, and would probably have played it an other way. 

With the hot seat, I think he bought simply a third share and hadn’t played the game like we had with no more 10% share in the market. 

Sorry to have bothered you, and many thanks for the explanation !
