### ISSUE TITLE
[18GB] Missing E-W bonus for London to Plymouth

### ISSUE THREAD

**Issue by ianwilson156** [tobymao/18xx#9869]
https://18xx.games/game/139077

OR7.1 LNWR is running a 4X London-Birmingham-Bristol-Plymouth for 300.
This should be 70+60+50+50+7 hexes + EW bonus = 340, but the E/W bonus is not being applied.
Its other train is also running EW (London - Pembroke).

"A company may claim both of these bonuses, _or the same
bonus more than once_, if the routes traced to claim the bonuses
do not share any track."

**Comment by andypymont** [comment]
The current algorithm for route bonuses is successfully creating networks from the players' trains (so that e.g. you can connect 2 trains together to get the EW bonus), but is not accounting for the possibility that one network could actually contain two sets of routes, which pass through the same cities but not the same track.

I have a solution in mind but not much time in December to implement and test.

**Comment by ianwilson156** [comment]
Great!
