### ISSUE TITLE
[18USA] Bug on PRR private

### ISSUE THREAD

**Issue by GTMDTTKP773** [tobymao/18xx#9999]
https://18xx.games/game/144294

#In OR3.2 the NYC has $800 and wants to buy 2 4T
#It buys the 1st 4T, since it is the 1st 4T to be bought in this game. It cause 2T rust.
#as the train rust, the owner of the PRR private was asked if he want to use the private company's ability. He choose pass.
#then the game go straight to the next company,and to make the NYC not be able to but its 2nd 4T

**Comment by MrSkinny** [comment]
The issue is caused by [this line](https://github.com/tobymao/18xx/blob/master/lib/engine/game/g_18_usa/game.rb#L906). If you allow the inherited `rust_trains!` method to run, then all trains rust as normal and the player can continue buying trains. However, P13 does not get a chance to interrupt.

I'm having trouble following the flow, though. I'm not sure how bypassing the superclass' `rust_trains!` method results in the "interrupt action" being presented and then evidently never returning to the original player's step of buying trains.

**Comment by crericha** [comment]
I think the issue is that NYC is at the train limit when the question is asked and the code incorrectly thinks the NYC cannot buy more trains and skips to the end of their turn.

Without looking at the code, I think the fix is to not skip steps when waiting for an answer.

**Comment by crericha** [comment]
If that doesn't work, then maybe we rust every train except one that can be saved and process that last train after the question is answered.
